/**
 * Tool import map + prefetch helpers.
 *
 * Calling import() for an already-loaded module costs nothing — the browser
 * module registry returns the cached module instantly without any network hit.
 */

const prefetched = new Set<string>();

export const toolImportMap: Record<string, () => Promise<any>> = {
  // ── Privacy & Security ───────────────────────────────────────────────────
  "/tools/temp-mail":                    () => import("@/pages/tools/TempMail"),
  "/tools/password-generator":           () => import("@/pages/tools/PasswordGenerator"),
  "/tools/password-strength-checker":    () => import("@/pages/tools/PasswordStrengthChecker"),
  "/tools/hash-generator":               () => import("@/pages/tools/HashGenerator"),
  "/tools/text-encrypt-decrypt":         () => import("@/pages/tools/TextEncryptDecrypt"),
  "/tools/exif-remover":                 () => import("@/pages/tools/ExifRemover"),
  "/tools/password-brute-force-calculator": () => import("@/pages/tools/PasswordBruteForceCalculator"),
  // ── Image ────────────────────────────────────────────────────────────────
  "/tools/image-compressor":             () => import("@/pages/tools/ImageCompressor"),
  "/tools/image-resizer":                () => import("@/pages/tools/ImageResizer"),
  "/tools/image-cropper":                () => import("@/pages/tools/ImageCropper"),
  "/tools/image-to-pdf":                 () => import("@/pages/tools/ImageToPDF"),
  "/tools/image-to-base64":              () => import("@/pages/tools/ImageToBase64"),
  "/tools/jpg-to-png":                   () => import("@/pages/tools/JPGtoPNG"),
  "/tools/png-to-jpg":                   () => import("@/pages/tools/PNGtoJPG"),
  "/tools/favicon-generator":            () => import("@/pages/tools/FaviconGenerator"),
  "/tools/background-remover":           () => import("@/pages/tools/BackgroundRemover"),
  "/tools/image-upscaler":               () => import("@/pages/tools/ImageUpscaler"),
  "/tools/image-grayscale":              () => import("@/pages/tools/ImageGrayscaleTool"),
  "/tools/image-blur":                   () => import("@/pages/tools/ImageBlurTool"),
  "/tools/image-pixelator":              () => import("@/pages/tools/ImagePixelator"),
  "/tools/image-mirror":                 () => import("@/pages/tools/ImageMirrorTool"),
  "/tools/image-rotate":                 () => import("@/pages/tools/ImageRotateTool"),
  "/tools/image-darken":                 () => import("@/pages/tools/ImageDarkenTool"),
  "/tools/image-lighten":                () => import("@/pages/tools/ImageLightenTool"),
  "/tools/image-invert":                 () => import("@/pages/tools/ImageInvertTool"),
  "/tools/dominant-color-finder":        () => import("@/pages/tools/DominantColorFinder"),
  "/tools/gif-compressor":               () => import("@/pages/tools/GIFCompressor"),
  "/tools/gif-to-mp4":                   () => import("@/pages/tools/GIFtoMP4"),
  "/tools/heic-to-jpg":                  () => import("@/pages/tools/HEICtoJPG"),
  // ── PDF ──────────────────────────────────────────────────────────────────
  "/tools/pdf-merger":                   () => import("@/pages/tools/PDFMerger"),
  "/tools/pdf-splitter":                 () => import("@/pages/tools/PDFSplitter"),
  "/tools/pdf-compressor":               () => import("@/pages/tools/PDFCompressor"),
  "/tools/pdf-watermark-adder":          () => import("@/pages/tools/PDFWatermarkAdder"),
  "/tools/pdf-watermark-remover":        () => import("@/pages/tools/PDFWatermarkRemover"),
  "/tools/pdf-password-remover":         () => import("@/pages/tools/PDFPasswordRemover"),
  "/tools/pdf-to-image":                 () => import("@/pages/tools/PDFToImage"),
  "/tools/pdf-rotator":                  () => import("@/pages/tools/PDFRotator"),
  "/tools/html-to-pdf":                  () => import("@/pages/tools/HTMLtoPDF"),
  "/tools/excel-to-pdf":                 () => import("@/pages/tools/ExcelToPDF"),
  // ── Text ─────────────────────────────────────────────────────────────────
  "/tools/word-counter":                 () => import("@/pages/tools/WordCounter"),
  "/tools/text-case-converter":          () => import("@/pages/tools/TextCaseConverter"),
  "/tools/text-summarizer":              () => import("@/pages/tools/TextSummarizer"),
  "/tools/text-to-speech":               () => import("@/pages/tools/TextToSpeech"),
  "/tools/text-to-file":                 () => import("@/pages/tools/TextToFile"),
  "/tools/text-diff":                    () => import("@/pages/tools/TextDiff"),
  "/tools/text-cleaner":                 () => import("@/pages/tools/TextCleaner"),
  "/tools/text-reverser":                () => import("@/pages/tools/TextReverser"),
  "/tools/text-repeater":                () => import("@/pages/tools/TextRepeater"),
  "/tools/text-spacer":                  () => import("@/pages/tools/TextSpacer"),
  "/tools/text-rotator":                 () => import("@/pages/tools/TextRotator"),
  "/tools/text-highlighter":             () => import("@/pages/tools/TextHighlightMarker"),
  "/tools/word-frequency-counter":       () => import("@/pages/tools/WordFrequencyCounter"),
  "/tools/word-shuffler":                () => import("@/pages/tools/WordShuffler"),
  "/tools/word-splitter":                () => import("@/pages/tools/WordSplitter"),
  "/tools/line-number-adder":            () => import("@/pages/tools/LineNumberAdder"),
  "/tools/line-break-remover":           () => import("@/pages/tools/LineBreakRemover"),
  "/tools/fancy-text-styler":            () => import("@/pages/tools/FancyTextStyler"),
  "/tools/glitch-text-generator":        () => import("@/pages/tools/GlitchTextGenerator"),
  "/tools/ascii-art-generator":          () => import("@/pages/tools/ASCIIArtGenerator"),
  "/tools/ascii-converter":              () => import("@/pages/tools/ASCIIConverter"),
  "/tools/morse-code-translator":        () => import("@/pages/tools/MorseCodeTranslator"),
  "/tools/palindrome-checker":           () => import("@/pages/tools/PalindromeChecker"),
  "/tools/pangram-generator":            () => import("@/pages/tools/PangramGenerator"),
  "/tools/case-mixer":                   () => import("@/pages/tools/CaseMixer"),
  "/tools/case-randomizer":              () => import("@/pages/tools/CaseRandomizer"),
  "/tools/remove-duplicate-words":       () => import("@/pages/tools/RemoveDuplicateWords"),
  "/tools/extract-numbers":              () => import("@/pages/tools/ExtractNumbers"),
  "/tools/sentence-sorter":              () => import("@/pages/tools/SentenceSorter"),
  "/tools/silent-text":                  () => import("@/pages/tools/SilentText"),
  "/tools/symbol-combiner":              () => import("@/pages/tools/SymbolCombiner"),
  "/tools/emoji-counter":                () => import("@/pages/tools/EmojiCounter"),
  "/tools/emoji-remover":                () => import("@/pages/tools/EmojiRemover"),
  "/tools/prefix-suffix-tool":           () => import("@/pages/tools/PrefixSuffixTool"),
  "/tools/character-map":                () => import("@/pages/tools/CharacterMap"),
  "/tools/character-paragraph-counter":  () => import("@/pages/tools/CharacterParagraphCounter"),
  "/tools/advanced-text-shadow":         () => import("@/pages/tools/AdvancedTextShadow"),
  "/tools/title-case-converter":         () => import("@/pages/tools/TitleCaseConverter"),
  "/tools/sentence-case-converter":      () => import("@/pages/tools/SentenceCaseConverter"),
  "/tools/superscript-generator":        () => import("@/pages/tools/SuperscriptGenerator"),
  "/tools/subscript-generator":          () => import("@/pages/tools/SubscriptGenerator"),
  "/tools/funny-roast-generator":        () => import("@/pages/tools/FunnyRoastGenerator"),
  "/tools/instagram-caption-generator":  () => import("@/pages/tools/InstagramCaptionGenerator"),
  "/tools/ingredient-health-analyzer":   () => import("@/pages/tools/IngredientHealthAnalyzer"),
  // ── Developer ────────────────────────────────────────────────────────────
  "/tools/json-formatter":               () => import("@/pages/tools/JSONFormatter"),
  "/tools/url-encoder":                  () => import("@/pages/tools/URLEncoder"),
  "/tools/url-parser":                   () => import("@/pages/tools/URLParser"),
  "/tools/base64-encoder":               () => import("@/pages/tools/Base64Encoder"),
  "/tools/base64-to-image":              () => import("@/pages/tools/Base64ToImage"),
  "/tools/file-to-base64":               () => import("@/pages/tools/FileToBase64"),
  "/tools/regex-tester":                 () => import("@/pages/tools/RegexTester"),
  "/tools/markdown-editor":              () => import("@/pages/tools/MarkdownEditor"),
  "/tools/code-beautifier":              () => import("@/pages/tools/CodeBeautifier"),
  "/tools/html-beautifier":              () => import("@/pages/tools/HTMLBeautifier"),
  "/tools/html-minifier":                () => import("@/pages/tools/HTMLMinifier"),
  "/tools/html-encoder-decoder":         () => import("@/pages/tools/HTMLEncoderDecoder"),
  "/tools/html-table-generator":         () => import("@/pages/tools/HTMLTableGenerator"),
  "/tools/css-minifier":                 () => import("@/pages/tools/CSSMinifier"),
  "/tools/css-grid-generator":           () => import("@/pages/tools/CSSGridGenerator"),
  "/tools/css-animation-generator":      () => import("@/pages/tools/CSSAnimationGenerator"),
  "/tools/css-clamp-generator":          () => import("@/pages/tools/CSSClampGenerator"),
  "/tools/js-minifier":                  () => import("@/pages/tools/JSMinifier"),
  "/tools/json-csv-converter":           () => import("@/pages/tools/JSONCSVConverter"),
  "/tools/json-yaml-converter":          () => import("@/pages/tools/JSONYAMLConverter"),
  "/tools/json-tree-viewer":             () => import("@/pages/tools/JSONTreeViewer"),
  "/tools/csv-viewer":                   () => import("@/pages/tools/CSVViewer"),
  "/tools/uuid-generator":               () => import("@/pages/tools/UUIDGenerator"),
  "/tools/slug-generator":               () => import("@/pages/tools/SlugGenerator"),
  "/tools/meta-tag-generator":           () => import("@/pages/tools/MetaTagGenerator"),
  "/tools/og-preview":                   () => import("@/pages/tools/OGPreview"),
  "/tools/open-graph-tag-generator":     () => import("@/pages/tools/OpenGraphTagGenerator"),
  "/tools/robots-text-generator":        () => import("@/pages/tools/RobotsTextGenerator"),
  "/tools/sitemap-xml-generator":        () => import("@/pages/tools/SitemapXmlGenerator"),
  "/tools/utm-builder":                  () => import("@/pages/tools/UTMBuilder"),
  "/tools/keyword-density-checker":      () => import("@/pages/tools/KeywordDensityChecker"),
  "/tools/api-snippet-builder":          () => import("@/pages/tools/APISnippetBuilder"),
  "/tools/canonical-url-generator":      () => import("@/pages/tools/CanonicalUrlGenerator"),
  "/tools/meta-robots-tag-generator":    () => import("@/pages/tools/MetaRobotsTagGenerator"),
  "/tools/border-radius-generator":      () => import("@/pages/tools/BorderRadiusGenerator"),
  "/tools/box-shadow-generator":         () => import("@/pages/tools/BoxShadowGenerator"),
  "/tools/button-css-generator":         () => import("@/pages/tools/ButtonCSSGenerator"),
  "/tools/outline-css-generator":        () => import("@/pages/tools/OutlineCSSGenerator"),
  "/tools/flexbox-playground":           () => import("@/pages/tools/FlexboxPlayground"),
  "/tools/variable-font-viewer":         () => import("@/pages/tools/VariableFontViewer"),
  "/tools/signature-pad":                () => import("@/pages/tools/SignaturePadTool"),
  "/tools/excel-viewer":                 () => import("@/pages/tools/ExcelViewer"),
  "/tools/xlsx-to-csv-converter":        () => import("@/pages/tools/XLSXToCSVConverter"),
  "/tools/xlsx-viewer":                  () => import("@/pages/tools/XLSXViewer"),
  "/tools/audio-noise-remover":          () => import("@/pages/tools/AudioNoiseRemover"),
  // ── Color ────────────────────────────────────────────────────────────────
  "/tools/color-picker":                 () => import("@/pages/tools/ColorPicker"),
  "/tools/hex-rgb-converter":            () => import("@/pages/tools/HexRgbConverter"),
  "/tools/hex-color-picker":             () => import("@/pages/tools/HexColorPickerTool"),
  "/tools/gradient-generator":           () => import("@/pages/tools/GradientGenerator"),
  "/tools/gradient-text-generator":      () => import("@/pages/tools/GradientTextGenerator"),
  "/tools/color-palette-generator":      () => import("@/pages/tools/ColorPaletteGenerator"),
  "/tools/color-palette-shuffler":       () => import("@/pages/tools/ColorPaletteShuffler"),
  "/tools/random-hex-color":             () => import("@/pages/tools/RandomHexColor"),
  // ── Generators ───────────────────────────────────────────────────────────
  "/tools/qr-maker":                     () => import("@/pages/tools/QRMaker"),
  "/tools/barcode-generator":            () => import("@/pages/tools/BarcodeGenerator"),
  "/tools/invoice-generator":            () => import("@/pages/tools/InvoiceGenerator"),
  "/tools/receipt-generator":            () => import("@/pages/tools/ReceiptGenerator"),
  "/tools/username-generator":           () => import("@/pages/tools/UsernameGenerator"),
  "/tools/random-number-generator":      () => import("@/pages/tools/RandomNumberGenerator"),
  "/tools/random-word-generator":        () => import("@/pages/tools/RandomWordGenerator"),
  "/tools/random-hashtag-generator":     () => import("@/pages/tools/RandomHashtagGenerator"),
  "/tools/fibonacci-generator":          () => import("@/pages/tools/FibonacciGenerator"),
  "/tools/prime-number-generator":       () => import("@/pages/tools/PrimeNumberGenerator"),
  // ── Math & Calculators ───────────────────────────────────────────────────
  "/tools/emi-calculator":               () => import("@/pages/tools/EMICalculator"),
  "/tools/age-calculator":               () => import("@/pages/tools/AgeCalculator"),
  "/tools/bmi-calculator":               () => import("@/pages/tools/BMICalculator"),
  "/tools/loan-calculator":              () => import("@/pages/tools/LoanCalculator"),
  "/tools/percentage-calculator":        () => import("@/pages/tools/PercentageCalculator"),
  "/tools/percentage-change":            () => import("@/pages/tools/PercentageChangeCalculator"),
  "/tools/compound-interest":            () => import("@/pages/tools/CompoundInterestCalculator"),
  "/tools/simple-interest":              () => import("@/pages/tools/SimpleInterestCalculator"),
  "/tools/mortgage-calculator":          () => import("@/pages/tools/MortgageCalculator"),
  "/tools/tip-calculator":               () => import("@/pages/tools/TipCalculator"),
  "/tools/pay-split-calculator":         () => import("@/pages/tools/PaySplitCalculator"),
  "/tools/commission-calculator":        () => import("@/pages/tools/CommissionCalculator"),
  "/tools/calorie-calculator":           () => import("@/pages/tools/CalorieCalculator"),
  "/tools/average-calculator":           () => import("@/pages/tools/AverageCalculator"),
  "/tools/mean-median-mode":             () => import("@/pages/tools/MeanMedianModeCalculator"),
  "/tools/unit-converter":               () => import("@/pages/tools/UnitConverter"),
  "/tools/area-converter":               () => import("@/pages/tools/AreaConverter"),
  "/tools/height-converter":             () => import("@/pages/tools/HeightConverter"),
  "/tools/days-calculator":              () => import("@/pages/tools/DaysCalculator"),
  "/tools/age-gap-calculator":           () => import("@/pages/tools/AgeGapCalculator"),
  "/tools/countdown-timer":              () => import("@/pages/tools/CountdownTimer"),
  "/tools/timer-stopwatch":              () => import("@/pages/tools/TimerStopwatch"),
  "/tools/stopwatch":                    () => import("@/pages/tools/Stopwatch"),
  "/tools/time-difference-calculator":   () => import("@/pages/tools/TimeDifferenceCalculator"),
  "/tools/number-sorter":                () => import("@/pages/tools/NumberSorter"),
  "/tools/fraction-calculator":          () => import("@/pages/tools/FractionCalculator"),
  "/tools/exponent-calculator":          () => import("@/pages/tools/ExponentCalculator"),
  "/tools/modulo-calculator":            () => import("@/pages/tools/ModuloCalculator"),
  "/tools/circle-calculator":            () => import("@/pages/tools/CircleCalculator"),
  "/tools/triangle-area-calculator":     () => import("@/pages/tools/TriangleAreaCalculator"),
  "/tools/lcm-hcf-calculator":           () => import("@/pages/tools/LCMHCFCalculator"),
  "/tools/prime-number-checker":         () => import("@/pages/tools/PrimeNumberChecker"),
  "/tools/prime-factorization":          () => import("@/pages/tools/PrimeFactorization"),
  "/tools/matrix-calculator":            () => import("@/pages/tools/MatrixCalculator"),
  "/tools/currency-formatter":           () => import("@/pages/tools/CurrencyFormatter"),
  "/tools/nato-phonetic-converter":      () => import("@/pages/tools/NATOPhoneticConverter"),
  // ── Productivity ─────────────────────────────────────────────────────────
  "/tools/todo-list":                    () => import("@/pages/tools/TodoList"),
  "/tools/expense-tracker":              () => import("@/pages/tools/ExpenseTracker"),
  "/tools/notes-app":                    () => import("@/pages/tools/NotesApp"),
  "/tools/speech-to-text":               () => import("@/pages/tools/SpeechToText"),
  // ── Media ────────────────────────────────────────────────────────────────
  "/tools/audio-to-mp3":                 () => import("@/pages/tools/AudioToMP3"),
  "/tools/mp4-to-mp3":                   () => import("@/pages/tools/MP4toMP3"),
  "/tools/mp3-cutter":                   () => import("@/pages/tools/MP3Cutter"),
  "/tools/video-compressor":             () => import("@/pages/tools/VideoCompressor"),
  "/tools/video-to-gif":                 () => import("@/pages/tools/VideoToGIF"),
  "/tools/youtube-thumbnail-downloader": () => import("@/pages/tools/YouTubeThumbnailDownloader"),
  "/tools/instagram-profile-picture-downloader": () => import("@/pages/tools/InstagramProfilePictureDownloader"),
};

/** Prefetch one tool — silently skipped if already done. */
export function prefetchTool(path: string): void {
  if (prefetched.has(path)) return;
  const importFn = toolImportMap[path];
  if (!importFn) return;
  prefetched.add(path);
  importFn().catch(() => {});
}

/** Prefetch a list of tools — already-done ones are silently skipped. */
export function prefetchTools(paths: string[]): void {
  paths.forEach(prefetchTool);
}

/**
 * Complete ordered list of every tool path — highest traffic first.
 * The hook processes this as a rolling loop: 20 at a time, idle-only,
 * paused at 3 MB and resumed on next navigation.
 */
export const TOP_TOOLS: string[] = [
  // ── Top 20 (highest traffic) ─────────────────────────────────────────────
  "/tools/temp-mail",
  "/tools/password-generator",
  "/tools/image-compressor",
  "/tools/qr-maker",
  "/tools/json-formatter",
  "/tools/word-counter",
  "/tools/text-case-converter",
  "/tools/password-strength-checker",
  "/tools/url-encoder",
  "/tools/base64-encoder",
  "/tools/color-picker",
  "/tools/image-resizer",
  "/tools/barcode-generator",
  "/tools/pdf-merger",
  "/tools/pdf-splitter",
  "/tools/invoice-generator",
  "/tools/hash-generator",
  "/tools/username-generator",
  "/tools/random-number-generator",
  "/tools/todo-list",
  // ── Next 20 ──────────────────────────────────────────────────────────────
  "/tools/pdf-compressor",
  "/tools/pdf-watermark-adder",
  "/tools/image-to-base64",
  "/tools/jpg-to-png",
  "/tools/png-to-jpg",
  "/tools/exif-remover",
  "/tools/csv-viewer",
  "/tools/text-diff",
  "/tools/text-cleaner",
  "/tools/favicon-generator",
  "/tools/html-beautifier",
  "/tools/css-minifier",
  "/tools/text-reverser",
  "/tools/pdf-password-remover",
  "/tools/text-to-file",
  "/tools/receipt-generator",
  "/tools/percentage-calculator",
  "/tools/markdown-editor",
  "/tools/regex-tester",
  "/tools/text-summarizer",
  // ── Next 20 ──────────────────────────────────────────────────────────────
  "/tools/emi-calculator",
  "/tools/age-calculator",
  "/tools/bmi-calculator",
  "/tools/loan-calculator",
  "/tools/uuid-generator",
  "/tools/text-encrypt-decrypt",
  "/tools/image-cropper",
  "/tools/code-beautifier",
  "/tools/text-to-speech",
  "/tools/timer-stopwatch",
  "/tools/expense-tracker",
  "/tools/hex-rgb-converter",
  "/tools/gradient-generator",
  "/tools/color-palette-generator",
  "/tools/image-to-pdf",
  "/tools/pdf-to-image",
  "/tools/html-minifier",
  "/tools/js-minifier",
  "/tools/json-csv-converter",
  "/tools/json-yaml-converter",
  // ── Next 20 ──────────────────────────────────────────────────────────────
  "/tools/image-grayscale",
  "/tools/image-blur",
  "/tools/image-pixelator",
  "/tools/image-mirror",
  "/tools/image-rotate",
  "/tools/image-darken",
  "/tools/image-lighten",
  "/tools/image-invert",
  "/tools/speech-to-text",
  "/tools/audio-to-mp3",
  "/tools/mp4-to-mp3",
  "/tools/video-compressor",
  "/tools/gif-compressor",
  "/tools/number-sorter",
  "/tools/unit-converter",
  "/tools/area-converter",
  "/tools/morse-code-translator",
  "/tools/ascii-converter",
  "/tools/nato-phonetic-converter",
  "/tools/word-frequency-counter",
  // ── Next 20 ──────────────────────────────────────────────────────────────
  "/tools/ascii-art-generator",
  "/tools/fancy-text-styler",
  "/tools/glitch-text-generator",
  "/tools/text-highlighter",
  "/tools/text-repeater",
  "/tools/text-rotator",
  "/tools/text-spacer",
  "/tools/word-shuffler",
  "/tools/word-splitter",
  "/tools/line-number-adder",
  "/tools/palindrome-checker",
  "/tools/slug-generator",
  "/tools/meta-tag-generator",
  "/tools/sitemap-xml-generator",
  "/tools/robots-text-generator",
  "/tools/keyword-density-checker",
  "/tools/utm-builder",
  "/tools/og-preview",
  "/tools/mortgage-calculator",
  "/tools/compound-interest",
  // ── Remaining tools ───────────────────────────────────────────────────────
  "/tools/background-remover",
  "/tools/image-upscaler",
  "/tools/dominant-color-finder",
  "/tools/gif-to-mp4",
  "/tools/heic-to-jpg",
  "/tools/pdf-watermark-remover",
  "/tools/pdf-rotator",
  "/tools/html-to-pdf",
  "/tools/excel-to-pdf",
  "/tools/text-to-file",
  "/tools/pangram-generator",
  "/tools/case-mixer",
  "/tools/case-randomizer",
  "/tools/remove-duplicate-words",
  "/tools/extract-numbers",
  "/tools/sentence-sorter",
  "/tools/silent-text",
  "/tools/symbol-combiner",
  "/tools/emoji-counter",
  "/tools/emoji-remover",
  "/tools/prefix-suffix-tool",
  "/tools/character-map",
  "/tools/character-paragraph-counter",
  "/tools/advanced-text-shadow",
  "/tools/title-case-converter",
  "/tools/sentence-case-converter",
  "/tools/superscript-generator",
  "/tools/subscript-generator",
  "/tools/funny-roast-generator",
  "/tools/instagram-caption-generator",
  "/tools/ingredient-health-analyzer",
  "/tools/url-parser",
  "/tools/base64-to-image",
  "/tools/file-to-base64",
  "/tools/html-encoder-decoder",
  "/tools/html-table-generator",
  "/tools/css-grid-generator",
  "/tools/css-animation-generator",
  "/tools/css-clamp-generator",
  "/tools/json-tree-viewer",
  "/tools/open-graph-tag-generator",
  "/tools/api-snippet-builder",
  "/tools/canonical-url-generator",
  "/tools/meta-robots-tag-generator",
  "/tools/border-radius-generator",
  "/tools/box-shadow-generator",
  "/tools/button-css-generator",
  "/tools/outline-css-generator",
  "/tools/flexbox-playground",
  "/tools/variable-font-viewer",
  "/tools/signature-pad",
  "/tools/excel-viewer",
  "/tools/xlsx-to-csv-converter",
  "/tools/xlsx-viewer",
  "/tools/audio-noise-remover",
  "/tools/hex-color-picker",
  "/tools/gradient-text-generator",
  "/tools/color-palette-shuffler",
  "/tools/random-hex-color",
  "/tools/random-word-generator",
  "/tools/random-hashtag-generator",
  "/tools/fibonacci-generator",
  "/tools/prime-number-generator",
  "/tools/percentage-change",
  "/tools/simple-interest",
  "/tools/tip-calculator",
  "/tools/pay-split-calculator",
  "/tools/commission-calculator",
  "/tools/calorie-calculator",
  "/tools/average-calculator",
  "/tools/mean-median-mode",
  "/tools/height-converter",
  "/tools/days-calculator",
  "/tools/age-gap-calculator",
  "/tools/countdown-timer",
  "/tools/stopwatch",
  "/tools/time-difference-calculator",
  "/tools/fraction-calculator",
  "/tools/exponent-calculator",
  "/tools/modulo-calculator",
  "/tools/circle-calculator",
  "/tools/triangle-area-calculator",
  "/tools/lcm-hcf-calculator",
  "/tools/prime-number-checker",
  "/tools/prime-factorization",
  "/tools/matrix-calculator",
  "/tools/currency-formatter",
  "/tools/password-brute-force-calculator",
  "/tools/notes-app",
  "/tools/mp3-cutter",
  "/tools/video-to-gif",
  "/tools/youtube-thumbnail-downloader",
  "/tools/instagram-profile-picture-downloader",
];
