// Random Animals
export const animals = [
  "Lion", "Tiger", "Elephant", "Giraffe", "Zebra", "Monkey", "Panda",
  "Koala", "Kangaroo", "Bear", "Wolf", "Fox", "Deer", "Rabbit", "Squirrel",
  "Dolphin", "Whale", "Shark", "Octopus", "Penguin", "Eagle", "Owl", "Parrot",
  "Butterfly", "Bee", "Ant", "Spider", "Snake", "Crocodile", "Turtle"
];

// Random Objects - Categorized Dataset (1000+ unique items)
export const objectCategories = {
  "Everyday Objects": [
    "Pencil", "Pen", "Notebook", "Eraser", "Ruler", "Sharpener", "Paper", "Stapler",
    "Staples", "Highlighter", "Marker", "Clipboard", "Rubber band", "Sticky notes",
    "Calendar", "Envelope", "Folder", "Book", "Magazine", "Newspaper", "Ticket",
    "Card", "Wallet", "Key", "Keychain", "Coin", "Button", "Zipper", "Tissue",
    "Napkin", "Watch", "Bracelet", "Ring", "Necklace", "Glasses", "Sunglasses",
    "Mirror", "Comb", "Hairbrush", "Hair tie", "Hair clip", "Scarf", "Belt",
    "Glove", "Sock", "Shoe", "Slipper", "Umbrella", "Bag", "Backpack", "Purse"
  ],
  "Household Items": [
    "Chair", "Table", "Sofa", "Couch", "Stool", "Bench", "Cabinet", "Drawer",
    "Wardrobe", "Bed", "Mattress", "Pillow", "Blanket", "Bedsheet", "Lamp",
    "Light bulb", "Fan", "Ceiling fan", "Wall clock", "Photo frame", "Mirror",
    "Curtain", "Curtain rod", "Carpet", "Rug", "Door", "Door handle", "Doorbell",
    "Window", "Window screen", "Ladder", "Toolbox", "Hammer", "Screwdriver",
    "Wrench", "Pliers", "Nail", "Screw", "Drill", "Tape measure", "Extension cord",
    "Power strip", "Candle", "Vase"
  ],
  "Kitchen Items": [
    "Spoon", "Fork", "Knife", "Butter knife", "Ladle", "Spatula", "Tongs", "Whisk",
    "Rolling pin", "Cutting board", "Plate", "Bowl", "Cup", "Glass", "Mug",
    "Water bottle", "Thermos", "Lunch box", "Food container", "Jar", "Can opener",
    "Bottle opener", "Peeler", "Grater", "Strainer", "Colander", "Frying pan",
    "Saucepan", "Pressure cooker", "Wok", "Kettle", "Teapot", "Oven tray",
    "Baking pan", "Microwave", "Oven", "Toaster", "Blender", "Mixer",
    "Food processor", "Refrigerator", "Freezer", "Dish rack", "Dishwasher"
  ],
  "Technology Objects": [
    "Smartphone", "Tablet", "Laptop", "Desktop computer", "Monitor", "Keyboard",
    "Mouse", "Trackpad", "Webcam", "Microphone", "Headphones", "Earbuds", "Speaker",
    "Router", "Modem", "WiFi extender", "Hard drive", "SSD", "USB drive",
    "Memory card", "Printer", "Scanner", "Projector", "VR headset", "Smartwatch",
    "Fitness tracker", "Drone", "Camera", "Tripod", "Ring light", "Gaming console",
    "Game controller", "Joystick", "Charging cable", "Power bank", "Charger",
    "Adapter", "HDMI cable", "Ethernet cable"
  ],
  "Office Objects": [
    "Office chair", "Office desk", "Desk lamp", "Document tray", "Paper tray",
    "File organizer", "Binder", "Index card", "Whiteboard", "Whiteboard marker",
    "Chalk", "Chalkboard", "Notice board", "Pin board", "Push pin", "Thumbtack",
    "Paper clip", "Binder clip", "Rubber stamp", "Ink pad", "Calculator",
    "Time clock", "Name badge", "ID card holder", "Lanyard", "Conference table",
    "Meeting notebook", "Presentation remote", "Laser pointer", "Stapler",
    "Tape dispenser", "Telephone", "Fax machine", "Filing cabinet"
  ],
  "School Objects": [
    "School bag", "Textbook", "Notebook", "Geometry box", "Protractor", "Compass",
    "Divider", "Chalk", "Blackboard", "Whiteboard", "School desk", "School chair",
    "Lunch bag", "Water bottle", "Crayons", "Color pencils", "Paint brush",
    "Paint palette", "Eraser dust", "Graph paper", "Index notebook", "Lab coat",
    "Microscope", "Test tube", "Beaker", "Lab flask", "Bunsen burner", "Pencil",
    "Pen", "Eraser", "Ruler", "Scissors", "Glue", "Tape", "Folder", "Binder",
    "Stapler", "Calculator"
  ],
  "Nature Objects": [
    "Tree", "Leaf", "Flower", "Rose", "Tulip", "Sunflower", "Grass", "Moss",
    "Pine cone", "Acorn", "Seed", "Branch", "Log", "Rock", "Pebble", "Sand",
    "Soil", "Mountain", "Hill", "River", "Lake", "Waterfall", "Ocean", "Wave",
    "Shell", "Coral", "Cloud", "Rain", "Snow", "Ice", "Wind", "Sun", "Moon",
    "Star", "Rainbow", "Lightning", "Bird", "Butterfly", "Bee", "Ant", "Spider",
    "Worm", "Snail", "Fish", "Turtle", "Lizard", "Snake", "Frog", "Mushroom"
  ],
  "Outdoor Objects": [
    "Bicycle", "Skateboard", "Roller skates", "Helmet", "Tent", "Campfire",
    "Lantern", "Flashlight", "Compass", "Map", "Binoculars", "Fishing rod",
    "Fishing net", "Boat", "Canoe", "Kayak", "Anchor", "Life jacket", "Surfboard",
    "Beach ball", "Frisbee", "Kite", "Swing", "Slide", "Seesaw", "Sandbox"
  ],
  "Clothing Items": [
    "Shirt", "T-shirt", "Jacket", "Coat", "Sweater", "Hoodie", "Jeans", "Pants",
    "Shorts", "Skirt", "Dress", "Suit", "Tie", "Bow tie", "Belt", "Scarf",
    "Gloves", "Hat", "Cap", "Beanie", "Boots", "Sandals", "Slippers", "Socks"
  ],
  "Vehicles": [
    "Car", "Bus", "Truck", "Motorcycle", "Scooter", "Bicycle", "Train", "Tram",
    "Subway", "Airplane", "Helicopter", "Boat", "Ship", "Yacht", "Submarine",
    "Rocket", "Space shuttle", "Tractor", "Bulldozer", "Excavator", "Ambulance",
    "Fire truck", "Police car", "Taxi"
  ],
  "Animals": [
    "Dog", "Cat", "Rabbit", "Horse", "Cow", "Sheep", "Goat", "Lion", "Tiger",
    "Bear", "Elephant", "Giraffe", "Zebra", "Kangaroo", "Panda", "Monkey", "Fox",
    "Wolf", "Deer", "Camel", "Dolphin", "Whale", "Shark", "Octopus", "Penguin",
    "Eagle", "Owl", "Parrot", "Peacock", "Sparrow"
  ],
  "Food Items": [
    "Apple", "Banana", "Orange", "Mango", "Pineapple", "Grape", "Strawberry",
    "Blueberry", "Watermelon", "Papaya", "Pear", "Peach", "Plum", "Cherry",
    "Pomegranate", "Kiwi", "Lemon", "Lime", "Coconut", "Avocado", "Carrot",
    "Potato", "Onion", "Garlic", "Ginger", "Tomato", "Cucumber", "Lettuce",
    "Spinach", "Broccoli", "Cauliflower", "Corn", "Peas", "Beans", "Pumpkin",
    "Bread", "Toast", "Sandwich", "Burger", "Pizza", "Pasta", "Noodles", "Rice",
    "Soup", "Salad", "Cake", "Cookie", "Chocolate", "Donut", "Ice cream"
  ],
  "Bathroom Objects": [
    "Toothbrush", "Toothpaste", "Mouthwash", "Dental floss", "Soap", "Shampoo",
    "Conditioner", "Body wash", "Face wash", "Razor", "Shaving cream", "Towel",
    "Bath towel", "Hand towel", "Bath mat", "Toilet paper", "Toilet brush",
    "Plunger", "Sink", "Faucet", "Mirror cabinet", "Hair dryer", "Comb",
    "Hair brush", "Soap dispenser", "Laundry basket", "Washing machine", "Dryer"
  ],
  "Cleaning Supplies": [
    "Broom", "Dustpan", "Mop", "Bucket", "Cleaning cloth", "Sponge", "Scrub brush",
    "Dish soap", "Laundry detergent", "Fabric softener", "Bleach", "Glass cleaner",
    "Surface cleaner", "Vacuum cleaner", "Robot vacuum", "Trash can", "Garbage bag",
    "Recycling bin", "Lint roller", "Feather duster", "Rubber gloves", "Spray bottle",
    "Air freshener"
  ],
  "Construction Tools": [
    "Hammer", "Screwdriver", "Drill", "Electric drill", "Saw", "Hand saw",
    "Circular saw", "Chainsaw", "Wrench", "Adjustable wrench", "Socket wrench",
    "Pliers", "Needle nose pliers", "Level", "Tape measure", "Measuring tape",
    "Utility knife", "Box cutter", "Paint roller", "Paint brush", "Paint tray",
    "Ladder", "Step ladder", "Tool belt", "Tool box", "Cement mixer", "Wheelbarrow"
  ],
  "Electronics": [
    "Television", "Smart TV", "DVD player", "Blu-ray player", "Gaming console",
    "PlayStation", "Xbox", "Nintendo Switch", "Remote control", "Soundbar",
    "Subwoofer", "Home theater system", "Smart speaker", "Smart light", "Smart plug",
    "Security camera", "Door sensor", "Motion sensor", "Thermostat", "Electric kettle",
    "Coffee maker", "Espresso machine", "Air fryer", "Electric grill", "Induction stove",
    "Electric fan", "Air conditioner", "Heater", "Humidifier", "Dehumidifier"
  ],
  "Sports Equipment": [
    "Football", "Basketball", "Baseball", "Cricket bat", "Cricket ball", "Tennis racket",
    "Tennis ball", "Badminton racket", "Badminton shuttlecock", "Golf club", "Golf ball",
    "Hockey stick", "Puck", "Skateboard", "Roller skates", "Helmet", "Knee pads",
    "Elbow pads", "Boxing gloves", "Punching bag", "Jump rope", "Yoga mat", "Dumbbell",
    "Barbell", "Weight plate", "Treadmill", "Exercise bike", "Rowing machine",
    "Pull up bar", "Gym bench"
  ],
  "Musical Instruments": [
    "Guitar", "Electric guitar", "Acoustic guitar", "Bass guitar", "Piano", "Keyboard",
    "Violin", "Cello", "Drum set", "Snare drum", "Bass drum", "Tambourine", "Triangle",
    "Maracas", "Saxophone", "Trumpet", "Trombone", "Flute", "Clarinet", "Harmonica",
    "Ukulele", "Banjo", "Xylophone", "Accordion"
  ],
  "Toys": [
    "Toy car", "Toy train", "Toy airplane", "Doll", "Action figure", "LEGO bricks",
    "Puzzle", "Rubik's cube", "Yo-yo", "Spinning top", "Kite", "Water gun",
    "Bubble wand", "Stuffed animal", "Teddy bear", "Toy robot", "Toy dinosaur",
    "Board game", "Card game", "Dice", "Remote control car"
  ],
  "Garden Items": [
    "Watering can", "Garden hose", "Sprinkler", "Garden shovel", "Garden rake",
    "Garden fork", "Pruning shears", "Hedge trimmer", "Plant pot", "Flower pot",
    "Seed packet", "Fertilizer bag", "Garden gloves", "Garden bench", "Bird feeder",
    "Bird bath", "Wheelbarrow", "Garden cart", "Greenhouse", "Compost bin"
  ],
  "Travel Objects": [
    "Suitcase", "Luggage", "Travel bag", "Passport", "Boarding pass", "Travel pillow",
    "Eye mask", "Ear plugs", "Travel adapter", "Neck pillow", "Map", "Guide book",
    "Compass", "Flashlight", "Camera", "Tripod", "Water bottle", "Snack box",
    "Travel wallet", "Portable charger"
  ],
  "Office Electronics": [
    "Desktop computer", "Monitor stand", "Keyboard tray", "Printer paper",
    "Scanner lid", "Fax machine", "Telephone", "Desk organizer", "USB hub",
    "External hard drive", "Ethernet cable", "Router antenna", "WiFi router",
    "Server rack", "Network switch"
  ],
  "Random Misc Objects": [
    "Crystal ball", "Hourglass", "Magnifying glass", "Binoculars", "Flashlight",
    "Lantern", "Candle", "Matchbox", "Lighter", "Rope", "Chain", "Padlock",
    "Key ring", "Safety pin", "Badge", "Coin jar", "Piggy bank", "Shopping cart",
    "Shopping basket", "Gift box", "Gift wrap", "Balloon", "Confetti", "Party hat",
    "Mask", "Treasure chest", "Ancient scroll", "Magic wand", "Golden key",
    "Silver coin", "Dragon egg", "Crystal shard", "Enchanted book", "Floating lantern",
    "Mystery box", "Alien artifact", "Time machine", "Robot arm", "Hologram projector",
    "Space helmet", "Moon rock", "Meteor fragment"
  ]
};

// Flatten all objects for "All Objects" option
export const objects = Object.values(objectCategories).flat();

// Creative Mode - Adjectives
export const adjectives = [
  "Magical", "Glowing", "Floating", "Giant", "Tiny", "Invisible", "Flying",
  "Dancing", "Singing", "Talking", "Spinning", "Bouncing", "Rolling", "Jumping",
  "Swimming", "Running", "Walking", "Crawling", "Climbing", "Falling", "Rising",
  "Shining", "Sparkling", "Shimmering", "Glittering", "Pulsing", "Vibrating",
  "Smoking", "Steaming", "Frozen", "Melting", "Solid", "Liquid", "Gaseous",
  "Transparent", "Opaque", "Rainbow", "Silver", "Golden", "Crystal", "Metallic",
  "Electric", "Magnetic", "Mystical", "Ancient", "Modern", "Futuristic", "Broken",
  "Rusty", "Shiny", "Dull", "Smooth", "Rough", "Soft", "Hard", "Flexible", "Rigid"
];

// Creative Mode - Actions
export const actions = [
  "Flying", "Talking", "Dancing", "Singing", "Spinning", "Bouncing", "Rolling",
  "Jumping", "Swimming", "Running", "Walking", "Crawling", "Climbing", "Falling",
  "Rising", "Floating", "Sinking", "Vanishing", "Appearing", "Growing", "Shrinking",
  "Transforming", "Glowing", "Shining", "Sparkling", "Pulsing", "Vibrating",
  "Smoking", "Steaming", "Laughing", "Crying", "Whispering", "Shouting", "Screaming",
  "Humming", "Whistling", "Ringing", "Buzzing", "Clicking", "Popping", "Exploding",
  "Freezing", "Melting", "Burning", "Dripping", "Flowing", "Splashing", "Waving"
];

// Random Indian Addresses
export const indianAddresses = [
  {
    street: "45, MG Road",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560001"
  },
  {
    street: "12, Connaught Place",
    city: "New Delhi",
    state: "Delhi",
    pincode: "110001"
  },
  {
    street: "78, Marine Drive",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400002"
  },
  {
    street: "23, Park Street",
    city: "Kolkata",
    state: "West Bengal",
    pincode: "700016"
  },
  {
    street: "56, Anna Salai",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600002"
  },
  {
    street: "34, MG Road",
    city: "Pune",
    state: "Maharashtra",
    pincode: "411001"
  },
  {
    street: "67, Banjara Hills",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500034"
  },
  {
    street: "89, Satellite",
    city: "Ahmedabad",
    state: "Gujarat",
    pincode: "380015"
  }
];

// Random Movies
export const movies = [
  { title: "The Shawshank Redemption", year: 1994, genre: "Drama" },
  { title: "The Godfather", year: 1972, genre: "Crime" },
  { title: "The Dark Knight", year: 2008, genre: "Action" },
  { title: "Pulp Fiction", year: 1994, genre: "Crime" },
  { title: "Forrest Gump", year: 1994, genre: "Drama" },
  { title: "Inception", year: 2010, genre: "Sci-Fi" },
  { title: "The Matrix", year: 1999, genre: "Sci-Fi" },
  { title: "Interstellar", year: 2014, genre: "Sci-Fi" },
  { title: "3 Idiots", year: 2009, genre: "Comedy" },
  { title: "Dangal", year: 2016, genre: "Drama" },
  { title: "PK", year: 2014, genre: "Comedy" },
  { title: "Baahubali", year: 2015, genre: "Action" },
  { title: "Titanic", year: 1997, genre: "Romance" },
  { title: "Avatar", year: 2009, genre: "Sci-Fi" },
  { title: "The Avengers", year: 2012, genre: "Action" }
];

// Random Hindi Names
export const hindiNames = {
  male: [
    "Aarav", "Vivaan", "Aditya", "Vihaan", "Arjun", "Sai", "Arnav", "Ayaan",
    "Krishna", "Ishaan", "Shaurya", "Atharv", "Advaith", "Pranav", "Reyansh"
  ],
  female: [
    "Aadhya", "Ananya", "Pari", "Anika", "Diya", "Aaradhya", "Sara", "Saanvi",
    "Navya", "Angel", "Kiara", "Shanaya", "Myra", "Aishwarya", "Anaya"
  ]
};

// Random Tech Stacks
export const techStacks = [
  { name: "MERN Stack", technologies: ["MongoDB", "Express.js", "React", "Node.js"] },
  { name: "MEAN Stack", technologies: ["MongoDB", "Express.js", "Angular", "Node.js"] },
  { name: "LAMP Stack", technologies: ["Linux", "Apache", "MySQL", "PHP"] },
  { name: "JAMstack", technologies: ["JavaScript", "APIs", "Markup"] },
  { name: "Python Full Stack", technologies: ["Python", "Django", "PostgreSQL", "React"] },
  { name: "Ruby Stack", technologies: ["Ruby", "Rails", "PostgreSQL", "React"] },
  { name: "T3 Stack", technologies: ["TypeScript", "tRPC", "Tailwind", "Next.js"] },
  { name: "Serverless Stack", technologies: ["AWS Lambda", "DynamoDB", "API Gateway", "React"] }
];

// Random Startup Ideas
export const startupIdeas = [
  "AI-powered personal finance advisor for millennials",
  "Sustainable fashion marketplace connecting local artisans",
  "Mental health app with gamified therapy exercises",
  "Smart home energy optimizer using IoT",
  "Virtual interior design consultation platform",
  "Peer-to-peer skill exchange marketplace",
  "Automated meal planning based on health goals",
  "Local farmer-to-consumer direct delivery app",
  "Corporate wellness platform with remote fitness tracking",
  "AI resume builder with interview prep",
  "Subscription box for eco-friendly products",
  "Remote team building activities platform",
  "Elderly care coordination app for families",
  "Student accommodation finder with virtual tours",
  "Freelancer time tracking and invoicing tool"
];

// Random Riddles
export const riddles = [
  { question: "What has a face but no eyes, and tells time without speaking?", answer: "A clock" },
  { question: "What has keys but opens no locks?", answer: "A piano" },
  { question: "What gets wetter the more it dries?", answer: "A towel" },
  { question: "What has hands but can't clap?", answer: "A clock" },
  { question: "What can travel around the world while staying in one spot?", answer: "A stamp" },
  { question: "What has a neck but no head?", answer: "A bottle" },
  { question: "What is full of holes but still holds water?", answer: "A sponge" },
  { question: "What belongs to you but others use it more?", answer: "Your name" },
  { question: "What has cities but no houses?", answer: "A map" },
  { question: "What has a bed but never sleeps?", answer: "A river" },
  { question: "What has teeth but cannot bite?", answer: "A comb" },
  { question: "What can you break but not hold?", answer: "A promise" },
  { question: "What has one eye but cannot see?", answer: "A needle" },
  { question: "What runs but never walks?", answer: "Water" },
  { question: "What has wings but cannot fly?", answer: "A time" },
  { question: "What has legs but cannot walk?", answer: "A table" },
  { question: "What has ears but cannot hear?", answer: "Cornfield" },
  { question: "What has a thumb and four fingers but isn't alive?", answer: "A glove" },
  { question: "What goes up but never comes down?", answer: "Your age" },
  { question: "What has a heart but doesn't beat?", answer: "An artichoke" },
  { question: "What gets bigger the more you take away?", answer: "A hole" },
  { question: "What has words but never talks?", answer: "A book" },
  { question: "What has a ring but no finger?", answer: "A telephone" },
  { question: "What can fill a room but takes up no space?", answer: "Light" },
  { question: "What gets broken if you say its name?", answer: "Silence" },
  { question: "What can you hold without touching it?", answer: "A conversation" },
  { question: "What has many keys but can't open a door?", answer: "A keyboard" },
  { question: "What has a bark but no leaves?", answer: "A dog" },
  { question: "What goes up and down but doesn't move?", answer: "Stairs" },
  { question: "What has branches but no fruit?", answer: "A bank" },
  { question: "What flies without wings?", answer: "Time" },
  { question: "What has a spine but no bones?", answer: "A book" },
  { question: "What has roots that no one sees?", answer: "A mountain" },
  { question: "What is light as a feather but no one can hold for long?", answer: "Breath" },
  { question: "What has a tail but no body?", answer: "A coin" },
  { question: "What has an eye but can't cry?", answer: "A storm" },
  { question: "What has wheels and flies?", answer: "A garbage truck" },
  { question: "What has many rings but no fingers?", answer: "A tree" },
  { question: "What has teeth but no mouth?", answer: "A saw" },
  { question: "What can be cracked, made, and told?", answer: "A joke" },
  { question: "What comes down but never goes up?", answer: "Rain" },
  { question: "What has steps but can't move?", answer: "A staircase" },
  { question: "What kind of room has no doors?", answer: "A mushroom" },
  { question: "What can you catch but not throw?", answer: "A cold" },
  { question: "What has a horn but isn't loud?", answer: "A rhino" },
  { question: "What is always coming but never arrives?", answer: "Tomorrow" },
  { question: "What can be opened but not closed?", answer: "An egg" },
  { question: "What has a lock but no key?", answer: "Your hair" },
  { question: "What has feet but no legs?", answer: "A ruler" },
  { question: "What two things can you never eat for breakfast?", answer: "Lunch and dinner" },
  { question: "What has four fingers and a thumb but is not alive?", answer: "A glove" },
  { question: "What item has keys, space, and no room?", answer: "A keyboard" },
  { question: "What runs but doesn't swim?", answer: "A refrigerator" },
  { question: "What kind of band never plays music?", answer: "A rubber band" },
  { question: "What kind of tree fits in your hand?", answer: "A palm tree" },
  { question: "What can be long or short, but is not alive?", answer: "A line" },
  { question: "What gets sharper the more you use it?", answer: "Your brain" },
  { question: "What can you find in the middle of nowhere?", answer: "The letter H" },
  { question: "What has holes but still strong?", answer: "A net" },
  { question: "What has no legs but still moves fast?", answer: "A car" },
  { question: "What has a sound but cannot speak?", answer: "A bell" },
  { question: "What has no life but can die?", answer: "A battery" },
  { question: "What has a door but no house?", answer: "A car" },
  { question: "What has rivers but no water?", answer: "A map" },
  { question: "What has pages but no stories?", answer: "A notebook" },
  { question: "What can you keep only after giving it?", answer: "Your word" },
  { question: "What is always in front of you but can't be seen?", answer: "Future" },
  { question: "What goes around everything but stays in one place?", answer: "A fence" },
  { question: "What breaks and never falls, and what falls and never breaks?", answer: "Day breaks, night falls" },
  { question: "What can't talk but replies when spoken to?", answer: "Echo" },
  { question: "What has six faces but no mouth?", answer: "A cube" },
  { question: "What goes up white and comes down yellow?", answer: "An egg" },
  { question: "What comes once in a minute, twice in a moment, but never in a thousand years?", answer: "The letter M" },
  { question: "What has three feet but no toes?", answer: "A yardstick" },
  { question: "What has thousands of ears but hears nothing?", answer: "Corn" },
  { question: "What has a bottom at the top?", answer: "A leg" },
  { question: "What has stripes but isn't a tiger?", answer: "A zebra crossing" },
  { question: "What can be cracked and played but not eaten?", answer: "A code" },
  { question: "What tastes better than it smells?", answer: "A tongue" },
  { question: "What goes up when rain comes down?", answer: "Umbrella" },
  { question: "What has wheels but no engine?", answer: "A shopping cart" },
  { question: "What is always late but never early?", answer: "A delay" },
  { question: "What has a key but no lock and space but no room?", answer: "Keyboard" },
  { question: "What has a light but no bulb?", answer: "Fire" },
  { question: "What melts in the sun but isn't ice?", answer: "A crayon" },
  { question: "What has lines but no paper?", answer: "A road" },
  { question: "What has a seat but no legs?", answer: "A toilet" },
  { question: "What has a head and tail but no body?", answer: "A coin" },
  { question: "What lives where it cannot breathe?", answer: "Fish" },
  { question: "What has a face but no mouth?", answer: "The moon" },
  { question: "What becomes smaller the more you use it?", answer: "A pencil" },
  { question: "What can cut through mountains but made of water?", answer: "A river" },
  { question: "What shines but isn't a star?", answer: "A diamond" },
  { question: "What can you write with but not on paper?", answer: "Your name in the air" },
  { question: "What comes in pieces but is whole when complete?", answer: "Puzzle" },
  { question: "What eats but never gets full?", answer: "Fire" },
  { question: "What can you make but not see?", answer: "Noise" },
  { question: "What grows without water?", answer: "Shadows" },
  { question: "What doesn't ask questions but gets answered?", answer: "A phone" },
  { question: "What disappears when you say its name?", answer: "Silence" },
  { question: "What room do ghosts avoid?", answer: "Living room" },
  { question: "What has four wheels and flies?", answer: "A garbage truck" },
  { question: "What kind of cup can't hold water?", answer: "Cupcake" },
  { question: "What fruit can you never cheer?", answer: "Blueberry" },
  { question: "What clothes does a house wear?", answer: "Address" },
  { question: "What begins with T, ends with T and has T inside?", answer: "Teapot" },
  { question: "What has a head but no brain?", answer: "A pin" },
  { question: "What has keys but no typing?", answer: "A lockset" },
  { question: "What gets older the longer it lives?", answer: "A tree" },
  { question: "What walks without legs?", answer: "Time" },
  { question: "What goes through towns without moving?", answer: "A road" },
  { question: "What plays music without sound?", answer: "Sheet music" },
  { question: "What breaks if you drop it but floats if you blow it?", answer: "Bubble" },
  { question: "What smiles without lips?", answer: "A rainbow" },
  { question: "What can't walk but leaves tracks?", answer: "A snail" },
  { question: "What has a roof but no walls?", answer: "A car" },
  { question: "What flies but can't land?", answer: "Time" },
  { question: "What never asks but gets answered?", answer: "Doorbell" },
  { question: "What can't eat but has a mouth?", answer: "River" },
  { question: "What has no water but waves?", answer: "Hair" },
  { question: "What grows shorter as it grows older?", answer: "Candle" },
  { question: "What is always tired but never sleeps?", answer: "Shoes" },
  { question: "What sings without a voice?", answer: "Wind" },
  { question: "What gets longer when pulled?", answer: "Elastic" },
  { question: "What can you catch at school?", answer: "Homework" },
  { question: "What has a shell but no life?", answer: "A suitcase" },
  { question: "What is full of stars but not sky?", answer: "A movie" },
  { question: "What loses its head every morning?", answer: "Pillow" },
  { question: "What has a bow but cannot shoot?", answer: "A gift" },
  { question: "What jumps but has no legs?", answer: "A jump rope" },
  { question: "What has a cap but no bottle?", answer: "Mountain" },
  { question: "What can be opened but never shut?", answer: "A secret" },
  { question: "What falls but never slips?", answer: "Night" },
  { question: "What can run but can't walk?", answer: "Refrigerator" },
  { question: "What grows in the dark but dies in the light?", answer: "Shadow" },
  { question: "What shines without fire?", answer: "Moon" },
  { question: "What keeps running even when confined?", answer: "Nose" },
  { question: "What travels without wheels?", answer: "Cloud" },
  { question: "What waves without hands?", answer: "Ocean" },
  { question: "What sleeps without dreams?", answer: "Rock" },
  { question: "What has no brakes but stops?", answer: "Time" },
  { question: "What grows when fed but dies when watered?", answer: "Fire" },
  { question: "What can you throw but never catch?", answer: "Word" },
  { question: "What has a head but no face?", answer: "Nail" },
  { question: "What bounces but not alive?", answer: "Ball" },
  { question: "What laughs without sound?", answer: "Emoji" },
  { question: "What has no tongue but tastes?", answer: "Taste buds joke" },
  { question: "What has a tail but no movement?", answer: "Comet" },
  { question: "What bites but has no teeth?", answer: "Frost" },
  { question: "What has eyes but can't blink?", answer: "Potato" },
  { question: "What has no voice but roars?", answer: "Thunder" },
  { question: "What curls but is not hair?", answer: "Snake" },
  { question: "What rings but not a bell?", answer: "Phone" },
  { question: "What rolls without wheels?", answer: "Coin" },
  { question: "What has a center but no edges?", answer: "Circle" },
  { question: "What has leaves but isn't a tree?", answer: "Book" },
  { question: "What stops at red but goes at green?", answer: "Watermelon" },
  { question: "What gets heavier the more you hold?", answer: "Breath" },
  { question: "What shows truth but can't talk?", answer: "Mirror" },
  { question: "What hides but never leaves?", answer: "Shadow" },
  { question: "What rains without water?", answer: "Meteors" },
  { question: "What rots but never smells?", answer: "Code" },
  { question: "What burns cold?", answer: "Ice" },
  { question: "What freezes heat?", answer: "AC" },
  { question: "What has a beat but no rhythm?", answer: "Broken fan" },
  { question: "What works only when broken?", answer: "Record" },
  { question: "What walks with many legs but no body?", answer: "Millipede shadow" },
  { question: "What is lost the moment you find it?", answer: "Surprise" },
  { question: "What grows on trees but isn't leaves?", answer: "Money joke" },
  { question: "What has power but no plug?", answer: "Brain" },
  { question: "What speaks without a mouth?", answer: "Echo" },
  { question: "What dances without legs?", answer: "Flame" },
  { question: "What opens without hands?", answer: "Mind" },
  { question: "What has a hole but never leaks?", answer: "Donut" },
  { question: "What cuts but isn't sharp?", answer: "Paper" },
  { question: "What has a sound but no breath?", answer: "Drum" },
  { question: "What gets higher the more you take?", answer: "Mountain trail" },
  { question: "What spreads without touching?", answer: "Rumor" },
  { question: "What can you hear but not see?", answer: "Music" },
  { question: "What hides in daylight?", answer: "Stars" },
  { question: "What has a key but no sound?", answer: "Password" },
  { question: "What has fire but doesn't burn?", answer: "Fireworks" },
  { question: "What rises without moving?", answer: "Expectations" },
  { question: "What has a lot of words but doesn't speak?", answer: "Dictionary" },
  { question: "What gives light but is not hot?", answer: "LED" },
  { question: "What falls without touching?", answer: "Temperature" },
  { question: "What can cross oceans without swimming?", answer: "Airplane shadow" },
  { question: "What is born old and dies young?", answer: "Photograph" },
  { question: "What freezes but isn't ice?", answer: "Laptop crash" },
  { question: "What has numbers but cannot count?", answer: "Clock" },
  { question: "What waves but isn't alive?", answer: "Flag" },
  { question: "What always ends everything?", answer: "The letter G" },
  { question: "What gets lost but stays in place?", answer: "Memory" },
  { question: "What breaks but can't be fixed?", answer: "Spilled milk" },
  { question: "What glows without electricity?", answer: "Fireflies" },
  { question: "What rises without air?", answer: "Hot balloon flame" },
  { question: "What can be erased but never written?", answer: "Footsteps" },
  { question: "What comes at the beginning of everything?", answer: "Letter E" },
  { question: "What can be bright but not light?", answer: "Idea" },
  { question: "What has nothing but still fills space?", answer: "Silence" },
  { question: "What has keys but can't type?", answer: "A map key" },
  { question: "What has a mouth but never speaks?", answer: "A cave" },
  { question: "What goes up a hill but never comes down?", answer: "Your age" },
  { question: "What gets eaten before it grows?", answer: "An egg" },
  { question: "What has lights but no electricity?", answer: "The sky" },
  { question: "What runs but has no legs?", answer: "Engine" },
  { question: "What breaks every time you name it?", answer: "Silence" },
  { question: "What can bring you down but never lifts?", answer: "Gravity" },
  { question: "What has legs but can't stand?", answer: "A compass" },
  { question: "What has a window but no glass?", answer: "Computer screen" },
  { question: "What grows stronger the more you share it?", answer: "Knowledge" },
  { question: "What is invisible but makes everything visible?", answer: "Light" },
  { question: "What stands still but moves people?", answer: "A picture" },
  { question: "What touches the sky but stays on the ground?", answer: "A mountain" },
  { question: "What gets erased when it grows?", answer: "Darkness" },
  { question: "What stops all around you but keeps going?", answer: "Time" },
  { question: "What breaks without touching?", answer: "A cloud" },
  { question: "What can be near but never around you?", answer: "Tomorrow" },
  { question: "What can fly but is always tired?", answer: "A flag" },
  { question: "What comes in waves but isn't water?", answer: "Sound" },
  { question: "What has clouds but never rains?", answer: "A pillow" },
  { question: "What always goes forward but never moves?", answer: "Calendar" },
  { question: "What sings but has no mouth?", answer: "Violin" },
  { question: "What melts without heat?", answer: "Willpower" },
  { question: "What shines brightest in darkness?", answer: "Hope" },
  { question: "What follows you but isn't alive?", answer: "Shadow" },
  { question: "What can be seen once in a second, twice in a moment?", answer: "The letter M" },
  { question: "What has a heart but no veins?", answer: "A clock" },
  { question: "What cannot be seen but can be counted?", answer: "Thoughts" },
  { question: "What gets broken but people still use?", answer: "Rules" },
  { question: "What falls without dropping?", answer: "Night" },
  { question: "What shakes without moving?", answer: "Your voice" },
  { question: "What has an end but never begins?", answer: "Rainbow" },
  { question: "What is silent but tells stories?", answer: "Paintings" },
  { question: "What moves faster in winter?", answer: "Cold" },
  { question: "What has a home but never sleeps?", answer: "A laptop" },
  { question: "What grows when you feed it but dies when you share it?", answer: "A secret" },
  { question: "What comes before work but after play?", answer: "Alphabetically" },
  { question: "What lives without breathing?", answer: "Fire" },
  { question: "What has a lock that everyone can open?", answer: "Hair" },
  { question: "What has a center but no inside?", answer: "A ring" },
  { question: "What has a crown but no kingdom?", answer: "A hat" },
  { question: "What can you catch but cannot throw?", answer: "Feeling" },
  { question: "What jumps higher than a mountain?", answer: "Anything, mountains don't jump" },
  { question: "What grows up but never grows old?", answer: "Tree branches" },
  { question: "What gets stronger when broken?", answer: "Metal when forged" },
  { question: "What sleeps during the day and wakes at night but isn't alive?", answer: "Stars" },
  { question: "What lives in corners but travels the world?", answer: "Stamp" },
  { question: "What has a head but cannot think?", answer: "A matchstick" },
  { question: "What dies when you forget it?", answer: "A memory" },
  { question: "What fits in your hand but can fill a room?", answer: "Light" },
  { question: "What gets bigger the more you share?", answer: "Happiness" },
  { question: "What flows but isn't water?", answer: "Electricity" },
  { question: "What listens to everyone but never speaks?", answer: "Earbuds" },
  { question: "What burns without fire?", answer: "Friction" },
  { question: "What has a beginning but no end?", answer: "Circle" },
  { question: "What ends everything?", answer: "The letter G" },
  { question: "What rests but never sleeps?", answer: "A chair" },
  { question: "What has a top but no bottom?", answer: "Your thoughts" },
  { question: "What is yours but mostly used by others?", answer: "Your name" },
  { question: "What is always new yet always old?", answer: "News" },
  { question: "What has many layers but no skin?", answer: "An onion" },
  { question: "What can run but cannot hide?", answer: "Your nose" },
  { question: "What grows when you remove its skin?", answer: "A banana joke" },
  { question: "What is sharp but not dangerous?", answer: "Wit" },
  { question: "What has a pulse but no heart?", answer: "Electricity" },
  { question: "What gets thrown without being touched?", answer: "Light" },
  { question: "What grows but is never alive?", answer: "Crystal" },
  { question: "What bends but never breaks?", answer: "Light" },
  { question: "What can fill a room but leave it empty?", answer: "Air" },
  { question: "What shakes the more you hold it still?", answer: "Jelly" },
  { question: "What breaks when you don't use it?", answer: "A habit" },
  { question: "What has a neck but no voice?", answer: "A vase" },
  { question: "What spreads the more you step on it?", answer: "Carpet" },
  { question: "What grows on you but isn't alive?", answer: "Clothes" },
  { question: "What can run forever without tiring?", answer: "A clock" },
  { question: "What always arrives and never stays?", answer: "Wind" },
  { question: "What disappears when you close your eyes?", answer: "Vision" },
  { question: "What grows faster than speed?", answer: "Rumor" },
  { question: "What follows everywhere but can't enter a room?", answer: "Sound" },
  { question: "What holds water without touching it?", answer: "Cloud" },
  { question: "What goes up with heat but down with cold?", answer: "Hot air" },
  { question: "What grows but remains hollow?", answer: "Bamboo" },
  { question: "What shines without being lit?", answer: "Glitter" },
  { question: "What flows but never moves?", answer: "A river drawn on a map" },
  { question: "What rises without climbing?", answer: "Smoke" },
  { question: "What comes twice in life and once in death?", answer: "The letter E" },
  { question: "What increases the more you look at it?", answer: "Curiosity" },
  { question: "What comes before morning but after night?", answer: "Alphabetically" },
  { question: "What hits you but leaves no mark?", answer: "A shadow" },
  { question: "What bends but never snaps?", answer: "Time" },
  { question: "What travels without footsteps?", answer: "Sunlight" },
  { question: "What has a home but no parents?", answer: "Apps" },
  { question: "What grows on walls but isn't alive?", answer: "Shadows" },
  { question: "What moves around you but never leaves?", answer: "Time" },
  { question: "What gets louder the more you silence it?", answer: "Thoughts" },
  { question: "What becomes clear when broken?", answer: "Clouds" },
  { question: "What can break mountains?", answer: "Earthquakes" },
  { question: "What moves the world but sits still?", answer: "The sun" },
  { question: "What makes you rich without money?", answer: "Experience" },
  { question: "What gets clearer the more you remove?", answer: "Fog" },
  { question: "What can cut but isn't sharp?", answer: "Ice" },
  { question: "What has no size but fills space?", answer: "Idea" },
  { question: "What hides inside numbers?", answer: "Patterns" },
  { question: "What grows roots but not in soil?", answer: "Knowledge" },
  { question: "What exists between words but isn't spoken?", answer: "Space" },
  { question: "What melts without heat?", answer: "Snowflake in hand" },
  { question: "What has a name but no identity?", answer: "Label" },
  { question: "What changes everything yet stays invisible?", answer: "Time" },
  { question: "What walks without feet?", answer: "Thought" },
  { question: "What disappears when darkness falls?", answer: "Shadows" },
  { question: "What is heavier: 1kg cotton or 1kg iron?", answer: "Neither" },
  { question: "What grows without eating?", answer: "Age" },
  { question: "What appears once in a year but never in a month?", answer: "The letter Y" },
  { question: "What stands tall but is hollow?", answer: "Bamboo" },
  { question: "What goes far but stays in place?", answer: "Wi-Fi" },
  { question: "What has waves but no water?", answer: "Hair" },
  { question: "What has many sides but no inside?", answer: "Polygon" },
  { question: "What has rings but no sound?", answer: "Saturn" },
  { question: "What drinks but never eats?", answer: "Plant roots" },
  { question: "What loses its tail every day?", answer: "A comet joke" },
  { question: "What lives inside a shell but isn't a snail?", answer: "A nut" },
  { question: "What enjoys a bath but hates water?", answer: "A cat" },
  { question: "What goes grey without aging?", answer: "Clouds" },
  { question: "What can fly but is not alive?", answer: "Paper plane" },
  { question: "What is born loud but dies silent?", answer: "Fireworks" },
  { question: "What lies behind every question?", answer: "Curiosity" },
  { question: "What becomes useless when empty?", answer: "Pen" },
  { question: "What becomes stronger the more you cut?", answer: "Hair joke" },
  { question: "What makes no sound but can shatter roofs?", answer: "Lightning" },
  { question: "What has a home in your pocket?", answer: "Phone" },
  { question: "What travels faster than light?", answer: "Thought" },
  { question: "What speaks all languages?", answer: "Smile" },
  { question: "What is free but priceless?", answer: "Time" },
  { question: "What falls but is never injured?", answer: "Snow" },
  { question: "What can make you blind but isn't physical?", answer: "Anger" },
  { question: "What joins people but isn't physical?", answer: "Friendship" },
  { question: "What gets shorter with use but isn't alive?", answer: "Pencil" },
  { question: "What opens without keys?", answer: "Eyes" },
  { question: "What has no face but smiles?", answer: "Emoji" },
  { question: "What sleeps but never dreams?", answer: "A log" },
  { question: "What beats but never plays?", answer: "Heartbeat sound" },
  { question: "What has no end but begins?", answer: "Circle" },
  { question: "What goes out but never leaves?", answer: "Light" },
  { question: "What arrives broken?", answer: "Dawn" },
  { question: "What has no shadow?", answer: "Darkness" },
  { question: "What cannot be thrown?", answer: "Shadow" },
  { question: "What grows cold as it warms?", answer: "Ice cream" },
  { question: "What becomes more when shared?", answer: "Love" },
  { question: "What can run but not race?", answer: "Colors in paint" },
  { question: "What becomes smaller the more it grows?", answer: "Shadow at noon" },
  { question: "What exists but cannot be touched?", answer: "Time" },
  { question: "What rises but never climbs?", answer: "Hot air" },
  { question: "What gets lower the more you raise?", answer: "Flag" },
  { question: "What is always right but wrong to some?", answer: "Opinion" },
  { question: "What walks with you but isn't alive?", answer: "Imaginary friend joke" },
  { question: "What has a screen but never watches?", answer: "Phone" },
  { question: "What reads but never learns?", answer: "Barcode" },
  { question: "What can be caught but never thrown back?", answer: "Time" },
  { question: "What chases you but never catches?", answer: "Tomorrow" },
  { question: "What grows inside you but isn't alive?", answer: "Dreams" },
  { question: "What freezes when moving fast?", answer: "Camera frame" },
  { question: "What has hands but no arms?", answer: "Clock" },
  { question: "What eats nothing but grows?", answer: "Fire" },
  { question: "What breaks but still whole?", answer: "Record" },
  { question: "What comes only when you stop looking?", answer: "Sleep" },
  { question: "What shines without burning?", answer: "Reflection" },
  { question: "What travels but never moves?", answer: "Road" },
  { question: "What can fit everywhere but doesn't exist?", answer: "Imagination" },
  { question: "What moves mountains?", answer: "Earthquakes" },
  { question: "What gives light but no heat?", answer: "Glow stick" },
  { question: "What has no color but paints everything?", answer: "Light" },
  { question: "What gets tighter when stretched?", answer: "Rubber band" },
  { question: "What falls from the sky and isn't water?", answer: "Snow" },
  { question: "What arrives with no warning and leaves with no trace?", answer: "Thought" },
  { question: "What has no height but rises?", answer: "Sound" },
  { question: "What can lock but has no key?", answer: "Algorithm" },
  { question: "What is made of water but stops fire?", answer: "Ice" },
  { question: "What sleeps in the day but works at night?", answer: "Stars" },
  { question: "What speaks but never lies?", answer: "Time" },
  { question: "What rises but never flies?", answer: "Bread" },
  { question: "What grows on paper but isn't drawn?", answer: "Puzzle" },
  { question: "What can you lend but never get back fully?", answer: "Time" },
  { question: "What returns but never the same?", answer: "Echo" },
  { question: "What gets faster the slower you go?", answer: "Time perception" },
  { question: "What reflects but isn't glass?", answer: "Water" },
  { question: "What bites but leaves no mark?", answer: "Cold" },
  { question: "What grows old instantly?", answer: "News" },
  { question: "What has no roots but grows tall?", answer: "Tower" },
  { question: "What becomes far but stays near?", answer: "Sky" },
  { question: "What travels in groups but makes no noise?", answer: "Clouds" },
  { question: "What grows by removing?", answer: "Sculptures" },
  { question: "What can surround but never touch?", answer: "Sound" },
  { question: "What makes two become one?", answer: "Marriage joke" },
  { question: "What grows wild but isn't alive?", answer: "Fire" },
  { question: "What sinks but isn't heavy?", answer: "Sun at sunset" },
  { question: "What becomes empty when full?", answer: "Full moon (full = no shadow)" },
  { question: "What hugs you tightly but doesn't move?", answer: "Clothes" },
  { question: "What cools you but has no breeze?", answer: "Shade" },
  { question: "What is long but not wide?", answer: "Line" },
  { question: "What has value but no price?", answer: "Memories" },
  { question: "What asks but never answers?", answer: "Riddle" },
  { question: "What gives without receiving?", answer: "Sun" },
  { question: "What grows but cannot be planted?", answer: "Ideas" },
  { question: "What shines but is never bright?", answer: "Reflection" },
  { question: "What spreads without touching?", answer: "Smile" },
  { question: "What falls but stays?", answer: "Temperature" },
  { question: "What waits but never stops?", answer: "Time" },
  { question: "What has waves but no sea?", answer: "Radio" },
  { question: "What disappears when you share it?", answer: "Secret" },
  { question: "What has air but no lungs?", answer: "Balloon" },
  { question: "What can float but is not light?", answer: "Boat" },
  { question: "What becomes white when you write on it?", answer: "Blackboard" },
  { question: "What grows faster than trees?", answer: "Rumors" },
  { question: "What breaks but doesn't fall?", answer: "Promise" },
  { question: "What walks in winter but not summer?", answer: "Snowman" },
  { question: "What shines in the day but never at night?", answer: "Sun" },
  { question: "What goes up but down at the same time?", answer: "See-saw" },
  { question: "What laughs without sound?", answer: "Emoji" },
  { question: "What has no floor but ceilings?", answer: "Sky" },
  { question: "What grows inside but dies outside?", answer: "Candle flame" },
  { question: "What has a taste but no tongue?", answer: "Food smell" },
  { question: "What swims but never gets wet?", answer: "Fish on screen" },
  { question: "What has a home but no rooms?", answer: "Website" },
  { question: "What appears broken but works?", answer: "Waves" },
  { question: "What heats up when cold?", answer: "Friction" },
  { question: "What hugs tightly but cannot touch?", answer: "Gravity" },
  { question: "What hides behind every smile?", answer: "Teeth" },
  { question: "What melts but isn't ice?", answer: "Wax" },
  { question: "What bounces but isn't a ball?", answer: "Email" },
  { question: "What flies when born but walks when old?", answer: "Snowflake" },
  { question: "What travels with you but never leaves home?", answer: "Phone" },
  { question: "What has a job but no salary?", answer: "Clock" },
  { question: "What gets deeper the more you climb?", answer: "Well" },
  { question: "What has no corners but dozens of sides?", answer: "Cylinder" },
  { question: "What stretches but never breaks?", answer: "Horizon" },
  { question: "What freezes but never cold?", answer: "Video frame" },
  { question: "What grows on your face but isn't alive?", answer: "Beard" },
  { question: "What falls but isn't heavy?", answer: "Leaves" },
  { question: "What sleeps in shells?", answer: "Seeds" },
  { question: "What has leaves but no tree?", answer: "Book" },
  { question: "What reflects without a mirror?", answer: "Water" },
  { question: "What lights the dark but makes no sound?", answer: "Stars" },
  { question: "What grows in rows but never planted?", answer: "Queue" },
  { question: "What goes up but is always grounded?", answer: "Mountain" },
  { question: "What changes color without mood?", answer: "Chameleon" },
  { question: "What is open but never closes?", answer: "Sky" },
  { question: "What grows but never blooms?", answer: "Knowledge" },
  { question: "What never ends but can stop?", answer: "Time" },
  { question: "What has rings but no circle?", answer: "Phone" },
  { question: "What turns red but isn't angry?", answer: "Tomato" },
  { question: "What stores memories but isn't alive?", answer: "Camera" },
  { question: "What freezes when hot?", answer: "Ice cream" },
  { question: "What jumps but never lands?", answer: "Bubble" },
  { question: "What rolls without moving?", answer: "Dice image" },
  { question: "What grows but always alone?", answer: "Mountain peak" },
  { question: "What goes without moving?", answer: "Path" },
  { question: "What turns but stays in place?", answer: "Wheel" },
  { question: "What stops time?", answer: "Photo" },
  { question: "What swims on land?", answer: "Shadow of bird" },
  { question: "What warms but never hot?", answer: "Friendship" },
  { question: "What has points but no score?", answer: "Needles" },
  { question: "What grows backwards?", answer: "Shadow in evening" },
  { question: "What stretches to the sky?", answer: "Tree" },
  { question: "What flows upward?", answer: "Flame" },
  { question: "What makes noise but never speaks?", answer: "Leaves" },
  { question: "What changes without touching?", answer: "Weather" },
  { question: "What grows when you wait?", answer: "Patience" },
  { question: "What has a voice but no throat?", answer: "Radio" },
  { question: "What gets filled without touching?", answer: "Heart" },
  { question: "What blooms only in the dark?", answer: "Stars" },
  { question: "What has no taste but flavors everything?", answer: "Salt smell" },
  { question: "What follows the sun?", answer: "Shadows" },
  { question: "What has no future but changes yours?", answer: "Past" },
  { question: "What warms nights but burns day?", answer: "Campfire" },
  { question: "What can lift mountains?", answer: "Time" },
  { question: "What grows with time but shrinks when measured?", answer: "Confidence" },
  { question: "What moves the fastest?", answer: "Thought" },
  { question: "What opens hearts but closes eyes?", answer: "Music" },
  { question: "What has layers but no cake?", answer: "Clouds" },
  { question: "What sleeps but never lies down?", answer: "Wind" },
  { question: "What is broken every day?", answer: "Morning" },
  { question: "What follows the wind?", answer: "Leaves" },
  { question: "What gets lighter the more you remove?", answer: "Darkness" },
  { question: "What has a path but no way?", answer: "Rainbow" },
  { question: "What moves oceans?", answer: "Moon" },
  { question: "What blooms without roots?", answer: "Fire" },
  { question: "What runs without legs?", answer: "Electricity" },
  { question: "What fades but never dies?", answer: "Memory" },
  { question: "What grows on trees but isn't fruit?", answer: "Money (joke)" },
  { question: "What waves but doesn't move?", answer: "Hair" },
  { question: "What gets thinner with use?", answer: "Eraser" },
  { question: "What moves but stays?", answer: "Wind" },
  { question: "What grows when shared?", answer: "Joy" },
  { question: "What sees far but cannot walk?", answer: "Telescope" },
  { question: "What rises but isn't alive?", answer: "Bread" },
  { question: "What feels but cannot touch?", answer: "Heart" },
  { question: "What visits but never stays?", answer: "Night" },
  { question: "What appears when you look up?", answer: "Sky" },
  { question: "What dies when fed?", answer: "Fire" },
  { question: "What has a tongue but cannot talk?", answer: "A shoe" },
  { question: "What can run out but never runs?", answer: "Time" },
  { question: "What can fill a bucket but never gets inside?", answer: "A shadow" },
  { question: "What grows but doesn't breathe?", answer: "Crystal" },
  { question: "What can be left but never taken?", answer: "A fingerprint" },
  { question: "What stands on one leg but moves the world?", answer: "A compass" },
  { question: "What is full of holes but still holds weight?", answer: "A net" },
  { question: "What is light as air but impossible to lift?", answer: "A bubble you didn't catch" },
  { question: "What do you break by saying its name?", answer: "Silence" },
  { question: "What wakes you up without sound?", answer: "Sunlight" },
  { question: "What has a bed but never sleeps?", answer: "A river" },
  { question: "What stands but doesn't walk?", answer: "A tree" },
  { question: "What grows quicker when cut?", answer: "Nails" },
  { question: "What catches fire but is cold?", answer: "Firework powder" },
  { question: "What can eat metal?", answer: "Rust" },
  { question: "What rains without clouds?", answer: "Sprinkler" },
  { question: "What has a voice but can't speak?", answer: "Music" },
  { question: "What can sting but has no tail?", answer: "Words" },
  { question: "What dies if you drop it but survives if you carry it?", answer: "A phone" },
  { question: "What wakes up angry but sleeps calmly?", answer: "Volcano" },
  { question: "What moves on four legs in morning, two in afternoon, none at night?", answer: "Shadow joke" },
  { question: "What burns but doesn't produce flame?", answer: "Acid" },
  { question: "What floats after you drop it?", answer: "Balloon" },
  { question: "What has cities but no buildings?", answer: "Map" },
  { question: "What gets eaten but never hungry?", answer: "Plate (metaphor)" },
  { question: "What increases but never grows?", answer: "Speed" },
  { question: "What flies without feathers?", answer: "Time" },
  { question: "What gets lost when you find it?", answer: "Your temper" },
  { question: "What fills rooms but takes no space?", answer: "Music" },
  { question: "What turns everything around but stays still?", answer: "Mirror" },
  { question: "What grows the more you take from it?", answer: "A hole" },
  { question: "What is always running but never late?", answer: "River" },
  { question: "What breaks itself to help others?", answer: "Egg" },
  { question: "What shines in both day and night?", answer: "Sunlight reflection" },
  { question: "What has no body but travels the world?", answer: "News" },
  { question: "What gets lost but never moves?", answer: "Memory" },
  { question: "What comes in pieces but stays whole?", answer: "Puzzle" },
  { question: "What hurts without touching?", answer: "Words" },
  { question: "What has water but no rain?", answer: "Ocean" },
  { question: "What has planets but no universe?", answer: "Solar system model" },
  { question: "What cries without eyes?", answer: "Cloud" },
  { question: "What laughs without voice?", answer: "Emoji" },
  { question: "What burns without heat?", answer: "Shame" },
  { question: "What has a lock but no door?", answer: "Password" },
  { question: "What can lie down but never wake?", answer: "Road" },
  { question: "What rings but isn't metal?", answer: "Phone" },
  { question: "What grows in fire?", answer: "Heat" },
  { question: "What throws light but never touches?", answer: "Lamp" },
  { question: "What stands tall but bends easily?", answer: "Grass" },
  { question: "What has an edge but is never sharp?", answer: "Horizon" },
  { question: "What can die but never lived?", answer: "Battery" },
  { question: "What can follow but never lead?", answer: "Shadows" },
  { question: "What cures without medicine?", answer: "Time" },
  { question: "What gets more dangerous the more you remove?", answer: "Ice on road" },
  { question: "What is empty but holds everything?", answer: "Mind" },
  { question: "What can trap you without walls?", answer: "Fear" },
  { question: "What sleeps underground but wakes above?", answer: "Seed" },
  { question: "What gets colder as it heats up?", answer: "AC" },
  { question: "What comes stronger at night?", answer: "Dreams" },
  { question: "What has no life but grows old?", answer: "Photos" },
  { question: "What travels fast but leaves no trace?", answer: "Sound in space joke" },
  { question: "What comes from trees but isn't leaves?", answer: "Paper" },
  { question: "What lives in hands but never breathes?", answer: "Gloves" },
  { question: "What can be long or short but never measured?", answer: "Mood" },
  { question: "What becomes cleaner the more you use?", answer: "Soap" },
  { question: "What is never hungry but always eating?", answer: "Fire" },
  { question: "What keeps moving even when standing still?", answer: "Watch" },
  { question: "What has a home but no family?", answer: "Website" },
  { question: "What can drown but isn't alive?", answer: "Fire" },
  { question: "What flies without being seen?", answer: "Time" },
  { question: "What grows roots without soil?", answer: "Hair" },
  { question: "What bends light but isn't water?", answer: "Glass" },
  { question: "What breaks stone without force?", answer: "Ice" },
  { question: "What grows in water but isn't wet?", answer: "Reflection" },
  { question: "What shifts without movement?", answer: "Sand dune" },
  { question: "What fades when placed under light?", answer: "Shadow" },
  { question: "What begins with T, ends with T and contains T?", answer: "Teapot" },
  { question: "What floats in air but is heavy?", answer: "Cloud" },
  { question: "What becomes thinner when filled?", answer: "Balloon stretched" },
  { question: "What supports life but isn't alive?", answer: "Soil" },
  { question: "What ends everything that begins?", answer: "The letter G" },
  { question: "What can be measured but not seen?", answer: "Time" },
  { question: "What hides behind you but you never catch?", answer: "Shadow" },
  { question: "What works only when broken?", answer: "Glow stick" },
  { question: "What becomes slow when you rush?", answer: "Work" },
  { question: "What can freeze without cold?", answer: "Screen" },
  { question: "What follows a number but isn't counted?", answer: "Decimal" },
  { question: "What grows louder the more you hide it?", answer: "Secret" },
  { question: "What has light but no shadow?", answer: "Laser" },
  { question: "What breaks mountains but is soft?", answer: "Water" },
  { question: "What moves without wheels?", answer: "Train on tracks" },
  { question: "What rises without lifting?", answer: "Sun" },
  { question: "What grows but shrinks when scared?", answer: "Ego" },
  { question: "What sleeps but breathes?", answer: "Baby" },
  { question: "What grows with darkness?", answer: "Stars" },
  { question: "What brightens when broken?", answer: "Dawn" },
  { question: "What grows without weight?", answer: "Air in balloon" },
  { question: "What always stays ahead?", answer: "Future" },
  { question: "What can be read but never written?", answer: "Barcode" },
  { question: "What arrives but never starts?", answer: "Middle" },
  { question: "What burns like fire but isn't hot?", answer: "Spice" },
  { question: "What slips but never falls?", answer: "Time" },
  { question: "What has wings but cannot fly?", answer: "Building wings" },
  { question: "What carries news without speaking?", answer: "Newspaper" },
  { question: "What has a bow but no ribbon?", answer: "Rainbow" },
  { question: "What exists once in minute and twice in moment?", answer: "M" },
  { question: "What has a bank but no money?", answer: "River" },
  { question: "What travels the world without moving?", answer: "Postage stamp" },
  { question: "What can drown you but isn't water?", answer: "Work" },
  { question: "What breaks but heals?", answer: "Heart" },
  { question: "What has a driver but no wheels?", answer: "Driver ants" },
  { question: "What gets warmer when cold?", answer: "Blanket" },
  { question: "What grows around you but you never see?", answer: "Air" },
  { question: "What slithers without being alive?", answer: "Rope" },
  { question: "What continues even when stopped?", answer: "Time" },
  { question: "What falls only at night?", answer: "Stars" },
  { question: "What stands tall but dies lying down?", answer: "Tree" },
  { question: "What has a tail but no body?", answer: "Comet" },
  { question: "What grows shorter with rest?", answer: "Candle" },
  { question: "What shrinks when you share?", answer: "Fear" },
  { question: "What stays dry in water?", answer: "Shadow" },
  { question: "What freezes when touched?", answer: "Fear" },
  { question: "What becomes dark when you see light?", answer: "Pupil" },
  { question: "What grows when forgotten?", answer: "Mistakes" },
  { question: "What breaks even when whole?", answer: "Record" },
  { question: "What has a ring but no finger?", answer: "Alarm" },
  { question: "What watches you but cannot see?", answer: "Camera" },
  { question: "What lifts but never touches?", answer: "Levitation joke (air)" },
  { question: "What opens doors but has no hands?", answer: "Key idea" },
  { question: "What shines but hides?", answer: "Moon" },
  { question: "What appears in water but never wet?", answer: "Reflection" },
  { question: "What slows when you look at it?", answer: "Hour hand" },
  { question: "What tastes without eating?", answer: "Smell" },
  { question: "What knows all but says nothing?", answer: "Google joke" },
  { question: "What rains without storm?", answer: "Sprinkler" },
  { question: "What can blind even with eyes open?", answer: "Sun" },
  { question: "What follows the night but isn't morning?", answer: "Stars fading" },
  { question: "What has hands but can't clap?", answer: "Clock" },
  { question: "What can be held but never touched?", answer: "Breath" },
  { question: "What spreads without moving?", answer: "Rumor" },
  { question: "What grows under pressure?", answer: "Diamond" },
  { question: "What flows through cities but isn't water?", answer: "Traffic" },
  { question: "What flips but never turns?", answer: "Coin" },
  { question: "What grows dense with age?", answer: "Forest" },
  { question: "What breaks before you use it?", answer: "Egg" },
  { question: "What can trap you but you hold it?", answer: "Phone addiction" },
  { question: "What falls asleep but never wakes?", answer: "Dead battery" },
  { question: "What glows but isn't fire?", answer: "Neon light" },
  { question: "What is lost the more you gain?", answer: "Balance" },
  { question: "What rains inside buildings?", answer: "Sprinkler system" },
  { question: "What grows from dust?", answer: "Building" },
  { question: "What has lips but never speaks?", answer: "Bottle" },
  { question: "What rises at night and hides in day?", answer: "Stars" },
  { question: "What sharpens while dulling?", answer: "Pencil sharpener" },
  { question: "What washes but never dries?", answer: "River" },
  { question: "What is full but never spills?", answer: "Cloud" },
  { question: "What sees everything but can't look?", answer: "Camera lens" },
  { question: "What rushes without moving?", answer: "Wind sound" },
  { question: "What jumps but never lands?", answer: "Balloon in air" },
  { question: "What grows bright when broken?", answer: "Dawn" },
  { question: "What shouts without a voice?", answer: "Thunder" },
  { question: "What walks around the world but stays in one corner?", answer: "Stamp" },
  { question: "What tastes sweet but isn't food?", answer: "Compliments" },
  { question: "What moves when your back is turned?", answer: "Time" },
  { question: "What is hot but cold?", answer: "Volcano top" },
  { question: "What eats but never full?", answer: "Fire" },
  { question: "What breaks but cannot be fixed?", answer: "Time" },
  { question: "What runs but never sweats?", answer: "Electricity" },
  { question: "What grows when you sleep?", answer: "Dreams" },
  { question: "What stands but never sits?", answer: "Pole" },
  { question: "What waves but never gets tired?", answer: "Flag" },
  { question: "What blooms but never dies?", answer: "Stars" },
  { question: "What raises but never lifts?", answer: "Taxes joke" },
  { question: "What can hear but has no ears?", answer: "Ground vibrations" },
  { question: "What drips but never spills?", answer: "Time passing" },
  { question: "What stands but never grows?", answer: "Lamp post" },
  { question: "What climbs but never falls?", answer: "Water vapor" },
  { question: "What touches sky but stays on earth?", answer: "Mountains" },
  { question: "What warms without fire?", answer: "Hug" },
  { question: "What has letters but isn't a word?", answer: "Alphabet" },
  { question: "What flies but has no wings?", answer: "Time" },
  { question: "What sleeps but never dreams?", answer: "Stone" },
  { question: "What breaks but still used?", answer: "Record" },
  { question: "What shines in dark but no flame?", answer: "Glow paint" },
  { question: "What grows then shrinks?", answer: "Tides" },
  { question: "What rings but no bell?", answer: "Alarm" },
  { question: "What has a key but no lock?", answer: "Piano" },
  { question: "What works after death?", answer: "Battery" },
  { question: "What appears but never stays?", answer: "Rainbow" },
  { question: "What touches everything but feels nothing?", answer: "Light" },
  { question: "What tastes with no tongue?", answer: "Nose" },
  { question: "What can be cracked, told, or played?", answer: "Joke" },
  { question: "What grows tallest when watered?", answer: "Shadow" },
  { question: "What falls fastest?", answer: "Night" },
  { question: "What gives light but not heat?", answer: "Screen" },
  { question: "What grows in silence?", answer: "Plants" },
  { question: "What stops when it moves?", answer: "Clock hand broken" },
  { question: "What jumps higher than buildings?", answer: "Everything (buildings don't jump)" },
  { question: "What breaks with truth?", answer: "Lie" },
  { question: "What floats but isn't light?", answer: "Ship" },
  { question: "What has a tail but never wags?", answer: "Coin" },
  { question: "What gets sharper without cutting?", answer: "Mind" },
  { question: "What freezes but isn't cold?", answer: "Screen" },
  { question: "What hides even when seen?", answer: "Camouflage" },
  { question: "What grows deeper the more you add?", answer: "Mystery" },
  { question: "What bites without teeth?", answer: "Wind" },
  { question: "What burns without flame?", answer: "Shame" },
  { question: "What has pages but no words?", answer: "Calendar" },
  { question: "What walks without feet?", answer: "Robot vacuum joke" },
  { question: "What rings silently?", answer: "Memory" },
  { question: "What grows with patience?", answer: "Success" },
  { question: "What has roots but never blooms?", answer: "Hair" },
  { question: "What sees more when you close your eyes?", answer: "Imagination" },
  { question: "What eats nothing but destroys everything?", answer: "Time" },
  { question: "What comes with clouds but not rain?", answer: "Shade" },
  { question: "What climbs but cannot descend?", answer: "Age" },
  { question: "What opens many doors but no hands?", answer: "Key card" },
  { question: "What blows but no air?", answer: "Nose blowing" },
  { question: "What grows when you step back?", answer: "Perspective" },
  { question: "What goes up but makes things go down?", answer: "Elevator" },
  { question: "What melts but isn't hot?", answer: "Ice" },
  { question: "What shines only when broken?", answer: "Egg yolk" },
  { question: "What never changes shape but grows?", answer: "Mountain" },
  { question: "What has a leg but no foot?", answer: "Chair" },
  { question: "What can burn the world but isn't fire?", answer: "Anger" },
  { question: "What swims without water?", answer: "Fish symbol" },
  { question: "What stands in a field but never grows?", answer: "Scarecrow" },
  { question: "What rises without wings?", answer: "Smoke" },
  { question: "What runs but makes no sound?", answer: "Wi-Fi" },
  { question: "What greets you but never talks?", answer: "Sunrise" },
  { question: "What sleeps with one eye open?", answer: "Dolphin (fun fact)" },
  { question: "What has ears but cannot hear?", answer: "Cornfield" },
  { question: "What dries while wet?", answer: "Towel" },
  { question: "What opens when you close it?", answer: "Parachute" },
  { question: "What burns cold?", answer: "Dry ice" },
  { question: "What falls but rises?", answer: "Sun" },
  { question: "What lets light pass but stays?", answer: "Glass" },
  { question: "What coughs but no throat?", answer: "Engine" },
  { question: "What roars but isn't a lion?", answer: "Thunder" },
  { question: "What hides in water but isn't wet?", answer: "Reflection" },
  { question: "What grows soft then hard?", answer: "Cement" },
  { question: "What plays without sound?", answer: "Mime" },
  { question: "What can break even if soft?", answer: "Cloud" },
  { question: "What remembers but cannot think?", answer: "Hard drive" },
  { question: "What touches you but you can't touch?", answer: "Wind" },
  { question: "What warms without heat?", answer: "Smile" },
  { question: "What shrinks without drying?", answer: "Shadow" },
  { question: "What breaks ice but not water?", answer: "Icebreaker" },
  { question: "What flows uphill?", answer: "Road" },
  { question: "What disappears when standing still?", answer: "Breath" },
  { question: "What rises but cannot fall?", answer: "Age" },
  { question: "What sinks but stays afloat?", answer: "Submarine" },
  { question: "What spreads when you close your eyes?", answer: "Imagination" },
  { question: "What has lines but never drawn?", answer: "Hands on clock" },
  { question: "What buries mountains?", answer: "Time" },
  { question: "What moves skies?", answer: "Wind" },
  { question: "What blows cold but feels warm?", answer: "Hug" },
  { question: "What sits but never rests?", answer: "Chair" },
  { question: "What stretches horizons?", answer: "Travel" },
  { question: "What talks without voice?", answer: "Art" },
  { question: "What shouts but no mouth?", answer: "Alarm" },
  { question: "What stands tall at night but disappears in morning?", answer: "Shadow" },
  { question: "What sails but never docks?", answer: "Cloud" },
  { question: "What grows where light can't reach?", answer: "Thought" },
  { question: "What begins but doesn't start?", answer: "Book title" },
  { question: "What steps without moving?", answer: "Ladder" },
  { question: "What gives birth without mother?", answer: "Idea" },
  { question: "What has a roof but no walls?", answer: "Bus stop" },
  { question: "What travels to all corners?", answer: "News" },
  { question: "What works harder the less you do?", answer: "Brain" },
  { question: "What can scream but has no sound?", answer: "Silent alarm" },
  { question: "What shivers but isn't cold?", answer: "Jelly" },
  { question: "What changes size but stays same?", answer: "Cloud" },
  { question: "What shines then hides?", answer: "Lightning" },
  { question: "What always grows but stays same height?", answer: "Hair cut" },
  { question: "What swings but no rope?", answer: "Mood" },
  { question: "What blooms when cold?", answer: "Frost" },
  { question: "What grows invisible?", answer: "Bacteria" },
  { question: "What catches the sky?", answer: "Lake" },
  { question: "What sleeps in winter?", answer: "Bear" },
  { question: "What dances without music?", answer: "Leaves" },
  { question: "What is stronger when joined?", answer: "Chain" },
  { question: "What dulls the sharper it gets?", answer: "Knife on stone" },
  { question: "What cuts deep without blade?", answer: "Words" },
  { question: "What flies inside but never leaves?", answer: "Dust" },
  { question: "What falls but can rise?", answer: "Mood" },
  { question: "What grows when scared?", answer: "Goosebumps" },
  { question: "What runs under your feet?", answer: "Floor" },
  { question: "What turns everything around?", answer: "Mirror" },
  { question: "What piles up but stays small?", answer: "Snowflakes" },
  { question: "What cools you but no wind?", answer: "Shade" },
  { question: "What freezes even in heat?", answer: "Ice cream" },
  { question: "What is broken but never fixed?", answer: "Egg" },
  { question: "What rises with heat but not flame?", answer: "Smoke" },
  { question: "What moves slow but travels far?", answer: "Snail" },
  { question: "What falls but never breaks?", answer: "Night" },
  { question: "What grows on nothing?", answer: "Shadow" },
  { question: "What sees everything but itself?", answer: "Mirror" },
  { question: "What shouts silently?", answer: "Fire" },
  { question: "What eats but never chews?", answer: "Fire" }
];

// Random Tasks
export const tasks = [
  "Do 20 push-ups",
  "Read 10 pages of a book",
  "Meditate for 5 minutes",
  "Drink a glass of water",
  "Organize your desk",
  "Take a 10-minute walk",
  "Call a friend or family member",
  "Write 3 things you're grateful for",
  "Stretch for 5 minutes",
  "Learn 5 new words in a foreign language",
  "Clean one room in your house",
  "Practice a skill for 15 minutes",
  "Delete 10 unnecessary files from your phone",
  "Review your goals for the month",
  "Try a new recipe"
];

// Random Superhero Names
export const superheroNames = [
  "Shadow Strike", "Thunder Bolt", "Crystal Guardian", "Phoenix Flame",
  "Steel Sentinel", "Quantum Shift", "Frost Fury", "Neon Ninja",
  "Cosmic Crusader", "Viper Vision", "Blaze Runner", "Titan Force",
  "Storm Breaker", "Mystic Mind", "Iron Will", "Silver Spark",
  "Velocity Vortex", "Echo Knight", "Gravity Master", "Lightning Lance"
];

// Truth or Dare
export const truthQuestions = [
  "What's your biggest fear?",
  "Who was your first crush?",
  "What's the most embarrassing thing you've done?",
  "What's a secret you've never told anyone?",
  "What's your biggest regret?",
  "Who do you have a crush on right now?",
  "What's the worst lie you've ever told?",
  "What's something you're glad your parents don't know about you?",
  "Have you ever cheated on a test?",
  "What's the meanest thing you've ever said to someone?"
];

export const dareActions = [
  "Do 20 jumping jacks",
  "Sing a song out loud",
  "Dance with no music for 1 minute",
  "Do your best celebrity impression",
  "Speak in an accent for the next 3 rounds",
  "Let someone else style your hair",
  "Post an embarrassing photo on social media",
  "Call a random contact and sing to them",
  "Do 10 pushups",
  "Eat a spoonful of a condiment",
  "Wear socks on your hands for the next 10 minutes",
  "Tell a joke (if no one laughs, do another dare)",
  "Let the group go through your phone for 2 minutes",
  "Imitate another player until someone guesses who",
  "Do a handstand or headstand for 30 seconds"
];

// Motivational Quotes
export const motivationalQuotes = [
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Everything you've ever wanted is on the other side of fear. - George Addair",
  "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine. - Roy T. Bennett",
  "I learned that courage was not the absence of fear, but the triumph over it. - Nelson Mandela",
  "There is only one way to avoid criticism: do nothing, say nothing, and be nothing. - Aristotle",
  "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The only impossible journey is the one you never begin. - Tony Robbins",
  "In the middle of every difficulty lies opportunity. - Albert Einstein",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis"
];
