import { ToolMetadata } from "@shared/schema";
import { 
  Mail, 
  Lock, 
  QrCode, 
  ImageDown, 
  Type, 
  FileText, 
  Code, 
  Link2, 
  Palette, 
  User, 
  ShieldCheck,
  Sparkles,
  Brain,
  Maximize2,
  Binary,
  Barcode,
  ArrowRightLeft,
  FileCode,
  Wand2,
  Minimize2,
  Search,
  FileEdit,
  Code2,
  Diff,
  Image,
  Droplets,
  Square,
  Crop,
  Hash,
  FileImage,
  Smile,
  Repeat,
  Link,
  Eye,
  Clock,
  Tags,
  FileText as Invoice,
  Receipt,
  FileEdit as Estimate,
  Ruler,
  Calculator,
  TrendingDown,
  Percent,
  Calendar,
  CalendarClock,
  Wallet,
  Volume2,
  Mic,
  RefreshCw,
  FileStack,
  FilePlus,
  RotateCw,
  FileImage as FilePicture,
  Settings,
  DollarSign,
  PiggyBank,
  CreditCard,
  Divide,
  Shuffle,
  Eraser,
  Unlock,
  ArrowUpDown,
  Users,
  Radio,
  Superscript,
  Subscript,
  Zap,
  BarChart3,
  Space,
  Pipette,
  Grid3x3,
  FileX,
  Rainbow,
  RectangleHorizontal,
  Box,
  Highlighter,
  Plus,
  CheckCircle,
  ALargeSmall,
  FolderTree,
  SunDim,
  Sun,
  FlipHorizontal,
  Contrast,
  PenTool,
  Triangle,
  Circle,
  TrendingUp,
  Rabbit,
  MapPin,
  Film,
  Lightbulb,
  HelpCircle,
  PartyPopper,
  Heart,
  CheckSquare,
  FileDown,
  Instagram
} from "lucide-react";

export const tools: ToolMetadata[] = [
  {
    id: "text-to-file",
    name: "Word to File (Text to File)",
    description: "Convert your text into downloadable files like .txt, .doc, or .pdf instantly. No upload required, 100% private and offline-supported.",
    icon: "FileDown",
    path: "/tools/text-to-file",
    category: "utility",
    keywords: ["text to file", "word to file", "text to doc", "text to txt", "text to pdf", "convert text to file", "save text online"],
  },
  {
    id: "csv-viewer",
    name: "CSV Viewer & Editor",
    description: "Open, view and edit CSV files online instantly with full privacy. No upload required, works 100% in your browser. Search, filter and explore your data securely.",
    icon: "FileSpreadsheet",
    path: "/tools/csv-viewer",
    category: "utility",
    keywords: ["csv viewer", "open csv online", "view csv file", "csv reader", "privacy-focused", "browser csv viewer", "csv editor"],
  },
  {
    id: "temp-mail",
    name: "Temp Mail Generator",
    description: "Generate temporary disposable emails instantly. Protect your privacy and avoid spam with free temporary email addresses.",
    icon: "Mail",
    path: "/tools/temp-mail",
    category: "privacy",
    keywords: ["temp mail", "temporary email", "disposable email", "free email", "privacy", "spam protection"],
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Create strong, secure passwords instantly. Customize length and complexity for maximum security.",
    icon: "Lock",
    path: "/tools/password-generator",
    category: "privacy",
    keywords: ["password generator", "strong password", "secure password", "random password", "password maker"],
  },
  {
    id: "qr-maker",
    name: "QR Code Maker",
    description: "Generate custom QR codes for URLs, text, or contact information. Download instantly in high quality.",
    icon: "QrCode",
    path: "/tools/qr-maker",
    category: "generator",
    keywords: ["qr code generator", "qr maker", "create qr code", "free qr code", "qr code creator"],
  },
  {
    id: "image-compressor",
    name: "Image Compressor",
    description: "Compress images without losing quality. Reduce file size instantly and download optimized images.",
    icon: "ImageDown",
    path: "/tools/image-compressor",
    category: "utility",
    keywords: ["image compressor", "compress image", "reduce image size", "optimize image", "image optimizer"],
  },
  {
    id: "text-case-converter",
    name: "Text Case Converter",
    description: "Convert text to uppercase, lowercase, title case, camel case, and more. Fast and simple text transformation.",
    icon: "Type",
    path: "/tools/text-case-converter",
    category: "utility",
    keywords: ["text case converter", "uppercase", "lowercase", "title case", "camel case", "snake case", "text transform"],
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, and paragraphs instantly. Perfect for writers and students.",
    icon: "FileText",
    path: "/tools/word-counter",
    category: "utility",
    keywords: ["word counter", "character counter", "text analyzer", "word count", "writing tool", "text analyzer"],
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Beautify and validate JSON data. Format, minify, and fix JSON syntax errors instantly.",
    icon: "Code",
    path: "/tools/json-formatter",
    category: "generator",
    keywords: ["json formatter", "json beautifier", "json validator", "json minifier", "format json"],
  },
  {
    id: "url-encoder",
    name: "URL Encoder/Decoder",
    description: "Encode or decode URLs instantly. Convert special characters for safe URL transmission.",
    icon: "Link2",
    path: "/tools/url-encoder",
    category: "utility",
    keywords: ["url encoder", "url decoder", "encode url", "decode url", "url escape", "url shortener"],
  },
  {
    id: "color-picker",
    name: "Color Picker",
    description: "Select and copy colors in HEX, RGB, and HSL formats. Perfect for designers and developers.",
    icon: "Palette",
    path: "/tools/color-picker",
    category: "generator",
    keywords: ["color picker", "hex color", "rgb color", "color converter", "color tool"],
  },
  {
    id: "username-generator",
    name: "Username Generator",
    description: "Generate creative and unique usernames instantly. Perfect for gaming, social media, and more.",
    icon: "User",
    path: "/tools/username-generator",
    category: "generator",
    keywords: ["username generator", "random username", "gamer tag", "username ideas", "name generator"],
  },
  {
    id: "password-strength-checker",
    name: "Password Strength Checker",
    description: "Check how strong your password is. Get instant feedback and security recommendations.",
    icon: "ShieldCheck",
    path: "/tools/password-strength-checker",
    category: "privacy",
    keywords: ["password strength", "password checker", "security checker", "password test", "strong password"],
  },
  {
    id: "text-summarizer",
    name: "AI Text Summarizer",
    description: "Free online text summarizer that works 100% offline in your browser. Summarize essays, PDFs, articles and long text instantly. No login, no server, full privacy.",
    icon: "Brain",
    path: "/tools/text-summarizer",
    category: "utility",
    keywords: ["free text summarizer", "AI summarizing tool", "offline summarizer", "browser summarizer", "paragraph shortener", "article summary tool", "text summarizer", "summarize text", "pdf summarizer", "essay summarizer"],
  },
  {
    id: "image-resizer",
    name: "Image Resizer",
    description: "Resize JPG, PNG or WebP images online. Change width & height instantly. Fast, offline & private.",
    icon: "Maximize2",
    path: "/tools/image-resizer",
    category: "utility",
    keywords: ["image resizer", "resize image online", "image scaling tool", "change image size"],
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder/Decoder",
    description: "Convert text to Base64 or decode Base64 to text instantly. 100% offline, secure & fast.",
    icon: "Binary",
    path: "/tools/base64-encoder",
    category: "utility",
    keywords: ["base64 encoder", "base64 decoder online", "encode text", "decode base64"],
  },
  {
    id: "barcode-generator",
    name: "Barcode Generator",
    description: "Generate high-quality barcodes instantly. Supports Code128, EAN, UPC & more. Download in PNG.",
    icon: "Barcode",
    path: "/tools/barcode-generator",
    category: "generator",
    keywords: ["barcode generator", "code128 barcode", "ean barcode", "upc creator"],
  },
  {
    id: "json-csv-converter",
    name: "JSON to CSV Converter",
    description: "Convert JSON to CSV or CSV to JSON instantly. 100% free, offline, secure and runs completely in your browser.",
    icon: "ArrowRightLeft",
    path: "/tools/json-csv-converter",
    category: "utility",
    keywords: ["json to csv", "csv converter online", "convert json csv", "offline converter"],
  },
  {
    id: "json-yaml-converter",
    name: "JSON to YAML Converter",
    description: "Convert JSON to YAML or YAML to JSON instantly. Fast, free and 100% offline-secure.",
    icon: "FileCode",
    path: "/tools/json-yaml-converter",
    category: "utility",
    keywords: ["json to yaml", "yaml converter", "yaml to json"],
  },
  {
    id: "code-beautifier",
    name: "Code Beautifier",
    description: "Beautify and format HTML, CSS or JavaScript instantly. Offline, safe and free tool for developers.",
    icon: "Wand2",
    path: "/tools/code-beautifier",
    category: "utility",
    keywords: ["code beautifier", "html formatter", "css beautify", "js formatter"],
  },
  {
    id: "css-minifier",
    name: "CSS Minifier",
    description: "Compress and minify CSS code instantly with a fast offline tool. Free and fully private.",
    icon: "Minimize2",
    path: "/tools/css-minifier",
    category: "utility",
    keywords: ["css minifier", "compress css", "minimize css online"],
  },
  {
    id: "js-minifier",
    name: "JavaScript Minifier",
    description: "Minify JavaScript instantly. Free, offline and secure — no code uploaded or stored.",
    icon: "Minimize2",
    path: "/tools/js-minifier",
    category: "utility",
    keywords: ["js minifier", "javascript compressor", "minify js online"],
  },
  {
    id: "html-beautifier",
    name: "HTML Beautifier",
    description: "Format and clean messy HTML code instantly. Offline, quick and perfect for developers.",
    icon: "FileCode",
    path: "/tools/html-beautifier",
    category: "utility",
    keywords: ["html beautifier", "format html code", "html formatter online"],
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test and debug your regex patterns instantly with live results. Free, offline and secure.",
    icon: "Search",
    path: "/tools/regex-tester",
    category: "utility",
    keywords: ["regex tester", "regular expression tester", "test regex online"],
  },
  {
    id: "markdown-editor",
    name: "Markdown Editor",
    description: "Write or paste Markdown and see instant live HTML preview. Free, offline and private.",
    icon: "FileEdit",
    path: "/tools/markdown-editor",
    category: "utility",
    keywords: ["markdown editor", "markdown preview", "md editor online"],
  },
  {
    id: "api-snippet-builder",
    name: "API Snippet Builder",
    description: "Create API request snippets in cURL or JavaScript fetch instantly. Offline, secure and direct.",
    icon: "Code2",
    path: "/tools/api-snippet-builder",
    category: "utility",
    keywords: ["curl generator", "fetch code generator", "api request builder"],
  },
  {
    id: "text-differ",
    name: "Text Differ",
    description: "Compare two texts or code blocks instantly and highlight differences. Offline and free.",
    icon: "Diff",
    path: "/tools/text-differ",
    category: "utility",
    keywords: ["text compare", "code diff tool", "diff checker online"],
  },
  {
    id: "image-to-base64",
    name: "Image to Base64 Converter",
    description: "Convert JPG, PNG or WebP images to Base64 instantly. Fast, offline, secure and works on any device.",
    icon: "Image",
    path: "/tools/image-to-base64",
    category: "utility",
    keywords: ["image to base64", "convert image base64", "base64 generator", "jpg to base64", "png to base64"],
  },
  {
    id: "base64-to-image",
    name: "Base64 to Image Converter",
    description: "Paste Base64 code and download the decoded image in one click. Works offline and secure.",
    icon: "Image",
    path: "/tools/base64-to-image",
    category: "utility",
    keywords: ["base64 to image", "decode base64", "base64 converter online", "base64 decoder"],
  },
  {
    id: "hex-rgb-converter",
    name: "HEX to RGB Converter",
    description: "Convert HEX to RGB or RGB to HEX instantly. Perfect for designers and developers.",
    icon: "Palette",
    path: "/tools/hex-rgb-converter",
    category: "generator",
    keywords: ["hex to rgb", "rgb converter", "color converter online", "rgb to hex"],
  },
  {
    id: "color-palette-generator",
    name: "Color Palette Generator",
    description: "Generate beautiful color palettes instantly. Stunning random colors, hex codes & offline support.",
    icon: "Palette",
    path: "/tools/color-palette-generator",
    category: "generator",
    keywords: ["color palette generator", "color theme maker", "random colors", "palette creator"],
  },
  {
    id: "gradient-generator",
    name: "CSS Gradient Generator",
    description: "Create linear & radial gradients visually and copy CSS instantly. Works offline.",
    icon: "Droplets",
    path: "/tools/gradient-generator",
    category: "generator",
    keywords: ["css gradient generator", "gradient maker", "background generator", "linear gradient"],
  },
  {
    id: "box-shadow-generator",
    name: "CSS Box Shadow Generator",
    description: "Design box shadows visually and copy CSS instantly. No ads, no login, fully offline.",
    icon: "Square",
    path: "/tools/box-shadow-generator",
    category: "generator",
    keywords: ["css shadow generator", "box shadow maker", "shadow css tool", "box shadow css"],
  },
  {
    id: "border-radius-generator",
    name: "Border Radius Generator",
    description: "Create smooth border radius shapes visually & copy CSS with one click.",
    icon: "Square",
    path: "/tools/border-radius-generator",
    category: "generator",
    keywords: ["border radius generator", "css curve tool", "radius editor", "rounded corners"],
  },
  {
    id: "image-cropper",
    name: "Image Cropper",
    description: "Crop images in your browser. No upload, no server — fully private and fast.",
    icon: "Crop",
    path: "/tools/image-cropper",
    category: "utility",
    keywords: ["image cropper", "crop image online", "photo crop tool", "image crop"],
  },
  {
    id: "random-number-generator",
    name: "Random Number Generator",
    description: "Generate random numbers instantly in any range. Offline, free and secure.",
    icon: "Hash",
    path: "/tools/random-number-generator",
    category: "generator",
    keywords: ["random number generator", "number picker online", "rng tool", "random number"],
  },
  {
    id: "favicon-generator",
    name: "Favicon Generator",
    description: "Upload any image and instantly generate favicon icons (.ico, 16x16, 32x32). Free, offline, fast and no server upload.",
    icon: "FileImage",
    path: "/tools/favicon-generator",
    category: "generator",
    keywords: ["favicon generator", "create favicon", "icon maker", "favicon .ico generator", "16x16 icon", "32x32 icon"],
  },
  {
    id: "file-to-base64",
    name: "File to Base64 Converter",
    description: "Convert documents, images & files to Base64 instantly. Secure, offline and lightning fast.",
    icon: "FileCode",
    path: "/tools/file-to-base64",
    category: "utility",
    keywords: ["file to base64", "convert file base64", "base64 tool", "document converter"],
  },
  {
    id: "html-encoder-decoder",
    name: "HTML Encoder/Decoder",
    description: "Encode or decode HTML characters instantly. Perfect for developers, SEO and editors.",
    icon: "Code",
    path: "/tools/html-encoder-decoder",
    category: "utility",
    keywords: ["html encoder", "html decoder", "html escape characters", "encode html", "decode html"],
  },
  {
    id: "emoji-remover",
    name: "Emoji Remover",
    description: "Paste or type text and remove all emojis instantly. Perfect for professionals & writers.",
    icon: "Smile",
    path: "/tools/emoji-remover",
    category: "utility",
    keywords: ["emoji remover", "remove emojis", "clean text tool", "emoji delete", "strip emojis"],
  },
  {
    id: "text-repeater",
    name: "Text Repeater",
    description: "Repeat any text multiple times instantly. Fast, free, offline and perfect for creators.",
    icon: "Repeat",
    path: "/tools/text-repeater",
    category: "utility",
    keywords: ["text repeater", "repeat text tool", "repeat generator", "duplicate text"],
  },
  {
    id: "sentence-case-converter",
    name: "Sentence Case Converter",
    description: "Convert long paragraphs into proper sentence case in one click. Offline supported and free.",
    icon: "Type",
    path: "/tools/sentence-case-converter",
    category: "utility",
    keywords: ["sentence case converter", "text formatter", "capitalization tool", "sentence case"],
  },
  {
    id: "utm-builder",
    name: "UTM Link Builder",
    description: "Generate UTM tracking links for Google Analytics. Free, fast and 100% offline.",
    icon: "Link",
    path: "/tools/utm-builder",
    category: "utility",
    keywords: ["utm builder", "utm generator", "tracking link creator", "google analytics", "utm parameters"],
  },
  {
    id: "meta-tag-generator",
    name: "Meta Tag Generator",
    description: "Generate SEO-friendly meta tags for websites. Free, fast & offline.",
    icon: "Tags",
    path: "/tools/meta-tag-generator",
    category: "generator",
    keywords: ["meta tag generator", "seo meta generator", "meta description tool", "seo tags"],
  },
  {
    id: "og-preview",
    name: "OG Image Previewer",
    description: "Preview how your page will look on Facebook, Twitter, LinkedIn & WhatsApp. Offline and simple.",
    icon: "Eye",
    path: "/tools/og-preview",
    category: "utility",
    keywords: ["og preview", "open graph tool", "social preview generator", "facebook preview", "twitter card"],
  },
  {
    id: "timer-stopwatch",
    name: "Timer & Stopwatch",
    description: "Use a simple timer or stopwatch offline. Perfect for study, workouts, cooking and productivity.",
    icon: "Clock",
    path: "/tools/timer-stopwatch",
    category: "utility",
    keywords: ["online timer", "stopwatch tool", "countdown timer", "timer online", "stopwatch online"],
  },
  {
    id: "invoice-generator",
    name: "Invoice Generator",
    description: "Generate clean, professional invoices online and download as PDF. No login and 100% offline-supported.",
    icon: "Invoice",
    path: "/tools/invoice-generator",
    category: "generator",
    keywords: ["invoice generator", "create invoice pdf", "billing tool online", "invoice maker", "free invoice"],
  },
  {
    id: "receipt-generator",
    name: "Receipt Generator",
    description: "Create payment receipts instantly and download as PDF. Fully offline, private and free.",
    icon: "Receipt",
    path: "/tools/receipt-generator",
    category: "generator",
    keywords: ["receipt generator", "payment receipt pdf", "token receipt tool", "receipt maker"],
  },
  {
    id: "quotation-generator",
    name: "Quotation Generator",
    description: "Generate business quotes & estimates quickly. Free, professional and offline-ready.",
    icon: "Estimate",
    path: "/tools/quotation-generator",
    category: "generator",
    keywords: ["quotation generator", "estimate creator", "business quote maker", "quote tool"],
  },
  {
    id: "area-converter",
    name: "Area Unit Converter",
    description: "Convert land and plot measurement units instantly. Perfect for property dealers & buyers.",
    icon: "Ruler",
    path: "/tools/area-converter",
    category: "utility",
    keywords: ["area converter", "sqft to yard", "acre to bigha", "land unit converter", "property measurement"],
  },
  {
    id: "commission-calculator",
    name: "Commission Calculator",
    description: "Calculate real estate commission for deals instantly. Works offline and 100% accurate.",
    icon: "Calculator",
    path: "/tools/commission-calculator",
    category: "utility",
    keywords: ["commission calculator", "brokerage calculator", "real estate commission", "property commission"],
  },
  {
    id: "emi-calculator",
    name: "EMI Prepayment Calculator",
    description: "Calculate how much interest you save by prepaying your loan EMIs. Offline, free and accurate.",
    icon: "TrendingDown",
    path: "/tools/emi-calculator",
    category: "utility",
    keywords: ["emi prepayment calculator", "loan prepayment savings", "emi interest save", "loan calculator"],
  },
  {
    id: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages easily — increase, decrease, % of number, difference & more.",
    icon: "Percent",
    path: "/tools/percentage-calculator",
    category: "utility",
    keywords: ["percentage calculator", "calculate percent", "% increase tool", "percent change"],
  },
  {
    id: "age-calculator",
    name: "Age Calculator",
    description: "Calculate your exact age in years, months, days and next birthday. 100% free & offline.",
    icon: "Calendar",
    path: "/tools/age-calculator",
    category: "utility",
    keywords: ["age calculator", "calculate age online", "birthday calculator", "age in days"],
  },
  {
    id: "time-difference-calculator",
    name: "Time Difference Calculator",
    description: "Calculate time difference between two dates/times instantly. Offline and fast.",
    icon: "CalendarClock",
    path: "/tools/time-difference-calculator",
    category: "utility",
    keywords: ["time difference calculator", "hours between dates", "date difference tool", "time calculator"],
  },
  {
    id: "expense-tracker",
    name: "Daily Expense Tracker",
    description: "Track expenses daily with a clean, offline tool. No signup, no cloud — your data stays private.",
    icon: "Wallet",
    path: "/tools/expense-tracker",
    category: "utility",
    keywords: ["expense tracker", "daily expense app", "offline budget tool", "money tracker"],
  },
  {
    id: "text-to-speech",
    name: "Text to Speech",
    description: "Convert text into natural speech instantly using your browser's built-in voice engine. No login, no data upload, 100% private.",
    icon: "Volume2",
    path: "/tools/text-to-speech",
    category: "utility",
    keywords: ["text to speech", "tts reader", "text voice converter", "online voice generator", "read aloud"],
  },
  {
    id: "speech-to-text",
    name: "Speech to Text",
    description: "Type with your voice using your browser's speech engine. Fast, accurate, free & private. Perfect for notes & productivity.",
    icon: "Mic",
    path: "/tools/speech-to-text",
    category: "utility",
    keywords: ["speech to text", "voice typing tool", "dictation online", "speech converter", "voice to text"],
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    description: "Convert 100+ units including kg, lbs, meters, inches, Celsius, Fahrenheit, acres, liters, joules & more.",
    icon: "RefreshCw",
    path: "/tools/unit-converter",
    category: "utility",
    keywords: ["unit converter online", "length converter", "temperature converter", "area converter", "weight converter"],
  },
  {
    id: "pdf-merger",
    name: "PDF Merger",
    description: "Merge multiple PDFs into one document instantly. Uses PDF.js fully offline — secure & private.",
    icon: "FileStack",
    path: "/tools/pdf-merger",
    category: "utility",
    keywords: ["merge pdf", "pdf joiner", "combine pdf online free", "offline pdf merge", "pdf combiner"],
  },
  {
    id: "pdf-splitter",
    name: "PDF Splitter",
    description: "Split PDF pages or extract selected pages to a new document. No upload, completely offline.",
    icon: "FilePlus",
    path: "/tools/pdf-splitter",
    category: "utility",
    keywords: ["pdf splitter", "split pdf pages", "extract pdf tool", "pdf page extractor"],
  },
  {
    id: "pdf-rotator",
    name: "PDF Rotator",
    description: "Rotate any PDF page left or right and save the corrected PDF instantly. Fully browser-based.",
    icon: "RotateCw",
    path: "/tools/pdf-rotator",
    category: "utility",
    keywords: ["rotate pdf", "pdf orientation tool", "pdf rotate online", "fix pdf rotation"],
  },
  {
    id: "pdf-to-image",
    name: "PDF to Image",
    description: "Convert every PDF page to JPG or PNG instantly. No upload — secure & private local conversion.",
    icon: "FilePicture",
    path: "/tools/pdf-to-image",
    category: "utility",
    keywords: ["pdf to image", "convert pdf to jpg", "pdf image extractor", "pdf to png"],
  },
  {
    id: "image-to-pdf",
    name: "Image to PDF",
    description: "Turn one or multiple images into a single PDF instantly. Offline-supported and secure.",
    icon: "FileImage",
    path: "/tools/image-to-pdf",
    category: "utility",
    keywords: ["image to pdf", "jpg to pdf", "png to pdf converter", "convert images to pdf"],
  },
  {
    id: "character-map",
    name: "Character Map",
    description: "Browse & copy thousands of Unicode characters — arrows, math symbols, currency, emojis & more.",
    icon: "Smile",
    path: "/tools/character-map",
    category: "utility",
    keywords: ["character map online", "unicode copy", "text symbols", "special characters", "emoji picker"],
  },
  {
    id: "ascii-converter",
    name: "ASCII ⇄ Text Converter",
    description: "Convert plain text to ASCII codes or decode ASCII to readable text instantly. Clean & offline tool.",
    icon: "Binary",
    path: "/tools/ascii-converter",
    category: "utility",
    keywords: ["ascii converter", "text to ascii", "ascii decoder online", "ascii encoder"],
  },
  {
    id: "text-diff",
    name: "Text Difference Highlighter",
    description: "Compare two text blocks and highlight exact differences instantly. Offline, fast & perfect for editors and developers.",
    icon: "Diff",
    path: "/tools/text-diff",
    category: "utility",
    keywords: ["text diff checker", "compare text online", "highlight text differences", "text comparison tool"],
  },
  {
    id: "days-calculator",
    name: "Days Calculator",
    description: "Calculate the number of days between two dates, including weekends & weekdays. Accurate & offline-ready.",
    icon: "Calendar",
    path: "/tools/days-calculator",
    category: "utility",
    keywords: ["days calculator", "days between dates", "date duration calculator", "date difference"],
  },
  {
    id: "stopwatch",
    name: "Stopwatch + Lap Timer",
    description: "Track time accurately with laps and splits. Works offline, clean design & perfect for study sessions or workouts.",
    icon: "Clock",
    path: "/tools/stopwatch",
    category: "utility",
    keywords: ["stopwatch online", "lap timer", "time tracker tool", "online stopwatch"],
  },
  {
    id: "countdown-timer",
    name: "Countdown Timer",
    description: "Set countdown timers for productivity, Pomodoro, cooking or workouts. Clean, simple & offline.",
    icon: "Clock",
    path: "/tools/countdown-timer",
    category: "utility",
    keywords: ["countdown timer", "online timer", "study timer", "cooking timer", "pomodoro timer"],
  },
  {
    id: "currency-formatter",
    name: "Currency Formatter",
    description: "Convert plain numbers into currency format like INR, USD, EUR, GBP, AED etc. Offline & instant.",
    icon: "DollarSign",
    path: "/tools/currency-formatter",
    category: "utility",
    keywords: ["currency formatter", "format number to currency", "number to rupees converter", "currency converter"],
  },
  {
    id: "loan-calculator",
    name: "Loan Interest Calculator",
    description: "Calculate total interest using flat-rate or reducing balance methods. Accurate, easy & offline.",
    icon: "PiggyBank",
    path: "/tools/loan-calculator",
    category: "utility",
    keywords: ["loan interest calculator", "emi interest", "flat rate interest", "loan total interest", "reducing balance"],
  },
  {
    id: "mortgage-calculator",
    name: "Mortgage Calculator",
    description: "Calculate mortgage payments with interest, principal breakdown & amortization table. Offline & global currency support.",
    icon: "CreditCard",
    path: "/tools/mortgage-calculator",
    category: "utility",
    keywords: ["mortgage calculator", "home loan calculator", "mortgage interest", "mortgage payment calculator"],
  },
  {
    id: "tip-calculator",
    name: "Tip Calculator",
    description: "Calculate tip percentage and split bills between people in seconds. Offline & instant.",
    icon: "DollarSign",
    path: "/tools/tip-calculator",
    category: "utility",
    keywords: ["tip calculator", "bill split calculator", "restaurant tip tool", "split bill"],
  },
  {
    id: "average-calculator",
    name: "Average Calculator",
    description: "Calculate average, mean, sum and count of numbers instantly. Perfect for students & data work.",
    icon: "Divide",
    path: "/tools/average-calculator",
    category: "utility",
    keywords: ["average calculator", "mean calculator", "number average tool", "calculate mean"],
  },
  {
    id: "random-string-generator",
    name: "Random String Generator",
    description: "Generate random strings of any length using letters, numbers & symbols. Offline & secure.",
    icon: "Shuffle",
    path: "/tools/random-string-generator",
    category: "generator",
    keywords: ["random string generator", "random text generator", "secure string generator", "random password"],
  },
  {
    id: "fraction-calculator",
    name: "Fraction Calculator",
    description: "Solve fractions instantly with addition, subtraction, multiplication, division & simplification. Offline & accurate.",
    icon: "Calculator",
    path: "/tools/fraction-calculator",
    category: "utility",
    keywords: ["fraction calculator", "add fractions", "simplify fractions", "fraction solver", "multiply fractions"],
  },
  {
    id: "roman-numeral-converter",
    name: "Roman Numeral Converter",
    description: "Convert Roman numerals to numbers or numbers to Roman instantly. Offline, accurate & easy.",
    icon: "RefreshCw",
    path: "/tools/roman-numeral-converter",
    category: "utility",
    keywords: ["roman numeral converter", "number to roman", "roman calculator", "roman to number"],
  },
  {
    id: "text-cleaner",
    name: "Text Cleaner",
    description: "Clean messy text by removing extra spaces, duplicates, symbols, line breaks & formatting. Offline & fast.",
    icon: "Eraser",
    path: "/tools/text-cleaner",
    category: "utility",
    keywords: ["text cleaner", "remove spaces", "clean text online", "remove symbols", "text formatter"],
  },
  {
    id: "text-encrypt-decrypt",
    name: "Text Encrypt & Decrypt",
    description: "Encrypt or decrypt text with a password using offline browser crypto. Zero data storage. AES encryption.",
    icon: "Lock",
    path: "/tools/text-encrypt-decrypt",
    category: "privacy",
    keywords: ["text encrypt", "text decrypt", "offline encryption", "aes encrypt text", "secure text encryption"],
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA1 & SHA256 hashes instantly. Developer-friendly, offline & secure.",
    icon: "Hash",
    path: "/tools/hash-generator",
    category: "utility",
    keywords: ["md5 generator", "sha256 hash tool", "hash calculator", "sha1 online", "hash generator"],
  },
  {
    id: "number-sorter",
    name: "Number Sorter",
    description: "Sort large lists of numbers instantly. Offline, fast & suitable for math, data & business.",
    icon: "ArrowUpDown",
    path: "/tools/number-sorter",
    category: "utility",
    keywords: ["number sorter", "sort numbers online", "number ordering tool", "ascending descending sort"],
  },
  {
    id: "pay-split-calculator",
    name: "Pay Split Calculator",
    description: "Split bills evenly or assign custom percentages. Perfect for friends, families & groups.",
    icon: "Users",
    path: "/tools/pay-split-calculator",
    category: "utility",
    keywords: ["bill split calculator", "split payment", "group bill tool", "payment splitter"],
  },
  {
    id: "matrix-calculator",
    name: "Matrix Calculator",
    description: "Solve matrix addition, subtraction & multiplication offline. Fast, accurate & great for students.",
    icon: "Calculator",
    path: "/tools/matrix-calculator",
    category: "utility",
    keywords: ["matrix calculator", "matrix multiplication", "add matrices online", "matrix operations"],
  },
  {
    id: "case-randomizer",
    name: "Case Randomizer",
    description: "Convert text into random case or alternating case instantly. Fun, fast & offline.",
    icon: "Shuffle",
    path: "/tools/case-randomizer",
    category: "utility",
    keywords: ["random case generator", "crazy text", "alternating case", "mixed case generator"],
  },
  {
    id: "title-case-converter",
    name: "Title Case Converter",
    description: "Convert your text into clean and professional Title Case instantly. Offline & secure.",
    icon: "ALargeSmall",
    path: "/tools/title-case-converter",
    category: "utility",
    keywords: ["title case converter", "proper case generator", "text capitalizer"],
  },
  {
    id: "slug-generator",
    name: "Slug Generator",
    description: "Convert text into SEO-friendly URL slugs instantly. Free, fast, offline-safe.",
    icon: "Link2",
    path: "/tools/slug-generator",
    category: "generator",
    keywords: ["slug generator", "url slug generator", "seo slug tool"],
  },
  {
    id: "morse-code-translator",
    name: "Morse Code Translator",
    description: "Convert any text to Morse code and decode Morse instantly. Offline and secure.",
    icon: "Radio",
    path: "/tools/morse-code-translator",
    category: "utility",
    keywords: ["morse code translator", "text to morse", "morse decoder"],
  },
  {
    id: "nato-phonetic-converter",
    name: "NATO Phonetic Converter",
    description: "Convert any text into NATO phonetic alphabet words like Alpha, Bravo & Charlie.",
    icon: "Radio",
    path: "/tools/nato-phonetic-converter",
    category: "utility",
    keywords: ["nato converter", "alpha bravo converter", "phonetic alphabet tool"],
  },
  {
    id: "superscript-generator",
    name: "Superscript Generator",
    description: "Generate superscript characters for math & styling. Offline and private.",
    icon: "Superscript",
    path: "/tools/superscript-generator",
    category: "generator",
    keywords: ["superscript generator", "tiny text generator"],
  },
  {
    id: "subscript-generator",
    name: "Subscript Generator",
    description: "Convert text into subscript characters like H₂O, CO₂. Perfect for formulas.",
    icon: "Subscript",
    path: "/tools/subscript-generator",
    category: "generator",
    keywords: ["subscript generator", "chemical text generator"],
  },
  {
    id: "glitch-text-generator",
    name: "Glitch Text Generator",
    description: "Create glitchy, spooky Zalgo text instantly. Offline & fun.",
    icon: "Zap",
    path: "/tools/glitch-text-generator",
    category: "generator",
    keywords: ["glitch text", "zalgo generator", "crazy text"],
  },
  {
    id: "word-frequency-counter",
    name: "Word Frequency Counter",
    description: "Analyze text and count frequency of each word. Great for SEO & writing.",
    icon: "BarChart3",
    path: "/tools/word-frequency-counter",
    category: "utility",
    keywords: ["word frequency tool", "repeated words", "text analyzer"],
  },
  {
    id: "text-spacer",
    name: "Text Spacer",
    description: "Create spaced-out text easily. Offline & free.",
    icon: "Space",
    path: "/tools/text-spacer",
    category: "generator",
    keywords: ["text spacer", "spaced text generator"],
  },
  {
    id: "random-emoji-generator",
    name: "Random Emoji Generator",
    description: "Click to generate random emojis instantly. Fun, fast & offline.",
    icon: "Smile",
    path: "/tools/random-emoji-generator",
    category: "generator",
    keywords: ["random emoji generator", "emoji picker"],
  },
  {
    id: "dominant-color-finder",
    name: "Dominant Color Finder",
    description: "Upload image → detect its dominant color instantly. Fully offline.",
    icon: "Pipette",
    path: "/tools/dominant-color-finder",
    category: "utility",
    keywords: ["dominant color tool", "extract image color"],
  },
  {
    id: "image-pixelator",
    name: "Image Pixelator",
    description: "Pixelate any image instantly using Canvas. No uploads.",
    icon: "Grid3x3",
    path: "/tools/image-pixelator",
    category: "utility",
    keywords: ["pixelate image", "pixel effect generator"],
  },
  {
    id: "image-blur-tool",
    name: "Image Blur Tool",
    description: "Apply blur effect to images instantly. Canvas-based, 100% offline.",
    icon: "Image",
    path: "/tools/image-blur-tool",
    category: "utility",
    keywords: ["blur image tool", "photo blur online"],
  },
  {
    id: "exif-remover",
    name: "Image EXIF Remover",
    description: "Remove EXIF metadata from images using offline canvas method.",
    icon: "FileX",
    path: "/tools/exif-remover",
    category: "privacy",
    keywords: ["exif remover", "remove metadata image"],
  },
  {
    id: "gradient-text-generator",
    name: "Gradient Text Generator",
    description: "Generate stunning gradient text with live preview & CSS copy.",
    icon: "Rainbow",
    path: "/tools/gradient-text-generator",
    category: "generator",
    keywords: ["gradient text generator", "css text gradient tool"],
  },
  {
    id: "button-css-generator",
    name: "CSS Button Generator",
    description: "Design modern CSS buttons with hover + shadow + radius.",
    icon: "RectangleHorizontal",
    path: "/tools/button-css-generator",
    category: "generator",
    keywords: ["css button generator", "button maker tool"],
  },
  {
    id: "flexbox-playground",
    name: "Flexbox Playground",
    description: "Play with Flexbox properties visually. Copy CSS instantly.",
    icon: "Box",
    path: "/tools/flexbox-playground",
    category: "generator",
    keywords: ["flexbox generator", "css flex tool"],
  },
  {
    id: "css-grid-generator",
    name: "CSS Grid Generator",
    description: "Create CSS grid layouts visually and copy clean CSS code.",
    icon: "Grid3x3",
    path: "/tools/css-grid-generator",
    category: "generator",
    keywords: ["css grid generator", "grid maker tool"],
  },
  {
    id: "outline-css-generator",
    name: "Outline CSS Generator",
    description: "Generate CSS outlines with width, style & offset.",
    icon: "Square",
    path: "/tools/outline-css-generator",
    category: "generator",
    keywords: ["outline css generator", "css outline tool"],
  },
  {
    id: "variable-font-viewer",
    name: "Variable Font Viewer",
    description: "Experiment with variable fonts using sliders for weight, width & italics.",
    icon: "Type",
    path: "/tools/variable-font-viewer",
    category: "utility",
    keywords: ["variable font viewer", "font weight slider"],
  },
  {
    id: "random-hex-color",
    name: "Random Color Generator",
    description: "Generate random HEX & RGB colors in one click. Perfect for designers.",
    icon: "Palette",
    path: "/tools/random-hex-color",
    category: "generator",
    keywords: ["hex color generator", "random color picker"],
  },
  {
    id: "palette-shuffler",
    name: "Color Palette Shuffler",
    description: "Generate random color palettes instantly. Offline & useful for UI/UX.",
    icon: "Shuffle",
    path: "/tools/palette-shuffler",
    category: "generator",
    keywords: ["color palette generator", "random palette creator"],
  },
  {
    id: "advanced-box-shadow",
    name: "Advanced Box Shadow Generator",
    description: "Create complex multi-layer CSS box shadows visually.",
    icon: "Square",
    path: "/tools/advanced-box-shadow",
    category: "generator",
    keywords: ["box shadow generator", "advanced shadow tool"],
  },
  {
    id: "text-highlight-generator",
    name: "Text Highlight Generator",
    description: "Highlight text with custom colors using HTML <mark>. Offline tool.",
    icon: "Highlighter",
    path: "/tools/text-highlight-generator",
    category: "generator",
    keywords: ["text highlight", "html mark generator"],
  },
  {
    id: "fancy-text-generator",
    name: "Fancy Text Generator",
    description: "Create stylish fancy Unicode text with 50+ font styles.",
    icon: "Sparkles",
    path: "/tools/fancy-text-generator",
    category: "generator",
    keywords: ["fancy text generator", "stylish text online"],
  },
  {
    id: "ascii-art-generator",
    name: "ASCII Art Generator",
    description: "Convert text into ASCII art using predefined static ASCII styles.",
    icon: "Binary",
    path: "/tools/ascii-art-generator",
    category: "generator",
    keywords: ["ascii art generator", "text to ascii tool"],
  },
  {
    id: "symbol-combiner",
    name: "Symbol Combiner",
    description: "Combine symbols creatively for decoration & stylish designs.",
    icon: "Plus",
    path: "/tools/symbol-combiner",
    category: "generator",
    keywords: ["symbol combiner", "unicode mix tool"],
  },
  {
    id: "text-rotator",
    name: "Text Rotator",
    description: "Rotate text orientation into vertical, reversed or angled directions.",
    icon: "RotateCw",
    path: "/tools/text-rotator",
    category: "utility",
    keywords: ["text rotator", "rotate text online"],
  },
  {
    id: "pangram-checker",
    name: "Pangram Checker",
    description: "Check if a sentence contains all 26 letters of the English alphabet.",
    icon: "CheckCircle",
    path: "/tools/pangram-checker",
    category: "utility",
    keywords: ["pangram checker", "alphabet sentence tool"],
  },
  {
    id: "random-word-generator",
    name: "Random Word Generator",
    description: "Generate random English nouns, verbs & adjectives instantly.",
    icon: "Shuffle",
    path: "/tools/random-word-generator",
    category: "generator",
    keywords: ["random word generator", "english word picker"],
  },
  {
    id: "json-tree-viewer",
    name: "JSON Tree Viewer",
    description: "View JSON structure in expandable tree format offline.",
    icon: "FolderTree",
    path: "/tools/json-tree-viewer",
    category: "utility",
    keywords: ["json viewer", "json tree viewer"],
  },
  {
    id: "css-clamp-generator",
    name: "CSS Clamp Generator",
    description: "Generate CSS clamp() values for fluid responsive text.",
    icon: "Ruler",
    path: "/tools/css-clamp-generator",
    category: "generator",
    keywords: ["css clamp generator", "fluid text css"],
  },
  {
    id: "css-animation-generator",
    name: "CSS Animation Generator",
    description: "Create CSS animations visually and copy keyframe CSS instantly.",
    icon: "Sparkles",
    path: "/tools/css-animation-generator",
    category: "generator",
    keywords: ["css animation generator", "keyframe tool"],
  },
  {
    id: "html-minifier",
    name: "HTML Minifier",
    description: "Minify HTML by removing whitespace, tabs and blank lines.",
    icon: "Minimize2",
    path: "/tools/html-minifier",
    category: "utility",
    keywords: ["html minifier", "compress html"],
  },
  {
    id: "extract-numbers",
    name: "Extract Numbers",
    description: "Extract all numbers from a block of text using static JS.",
    icon: "Hash",
    path: "/tools/extract-numbers",
    category: "utility",
    keywords: ["extract numbers", "pull digits text"],
  },
  {
    id: "remove-numbers",
    name: "Remove Numbers",
    description: "Remove all numbers (0-9) from text instantly.",
    icon: "Eraser",
    path: "/tools/remove-numbers",
    category: "utility",
    keywords: ["remove numbers", "clean digits text"],
  },
  {
    id: "image-darken-tool",
    name: "Image Darken Tool",
    description: "Darken photos using canvas filters. Offline and fast.",
    icon: "SunDim",
    path: "/tools/image-darken-tool",
    category: "utility",
    keywords: ["darken image tool", "photo darkener"],
  },
  {
    id: "image-lighten-tool",
    name: "Image Lighten Tool",
    description: "Increase brightness of images using canvas.",
    icon: "Sun",
    path: "/tools/image-lighten-tool",
    category: "utility",
    keywords: ["lighten image", "brighten photo tool"],
  },
  {
    id: "image-mirror-tool",
    name: "Image Mirror Tool",
    description: "Flip any image horizontally. Perfect for selfies and edits.",
    icon: "FlipHorizontal",
    path: "/tools/image-mirror-tool",
    category: "utility",
    keywords: ["mirror image", "flip image tool"],
  },
  {
    id: "image-invert-tool",
    name: "Image Invert Tool",
    description: "Invert colors of any image using canvas filters.",
    icon: "Contrast",
    path: "/tools/image-invert-tool",
    category: "utility",
    keywords: ["invert image tool", "negative photo"],
  },
  {
    id: "image-grayscale-tool",
    name: "Image Grayscale Tool",
    description: "Convert images to grayscale (black & white).",
    icon: "Image",
    path: "/tools/image-grayscale-tool",
    category: "utility",
    keywords: ["grayscale image", "black white converter"],
  },
  {
    id: "image-rotate-tool",
    name: "Image Rotate Tool",
    description: "Rotate images left or right using canvas.",
    icon: "RotateCw",
    path: "/tools/image-rotate-tool",
    category: "utility",
    keywords: ["rotate image online", "rotate photo tool"],
  },
  {
    id: "signature-pad-tool",
    name: "Online Signature Generator",
    description: "Create your digital signature online — draw, type, or upload. Export as transparent PNG, JPG, or SVG. Free and 100% private.",
    icon: "PenTool",
    path: "/tools/signature-pad-tool",
    category: "utility",
    keywords: ["online signature generator", "draw signature online", "create e-signature", "digital signature maker", "free signature tool"],
  },
  {
    id: "prime-number-checker",
    name: "Prime Number Checker",
    description: "Instantly check whether a number is prime or composite. Fully offline prime verification tool.",
    icon: "Hash",
    path: "/tools/prime-number-checker",
    category: "utility",
    keywords: ["prime number checker", "is prime tool", "check prime number"],
  },
  {
    id: "prime-number-generator",
    name: "Prime Number Generator",
    description: "Generate prime numbers in a range. Offline, accurate list generator.",
    icon: "Hash",
    path: "/tools/prime-number-generator",
    category: "generator",
    keywords: ["prime number generator", "list of primes", "generate primes"],
  },
  {
    id: "prime-factorization",
    name: "Prime Factorization Calculator",
    description: "Break any number into prime factors instantly. Fast and accurate.",
    icon: "Divide",
    path: "/tools/prime-factorization",
    category: "utility",
    keywords: ["prime factorization", "factor number tool", "prime factors"],
  },
  {
    id: "lcm-hcf-calculator",
    name: "LCM HCF Calculator",
    description: "Calculate LCM and HCF/GCD of numbers instantly. Free offline calculator.",
    icon: "Calculator",
    path: "/tools/lcm-hcf-calculator",
    category: "utility",
    keywords: ["lcm calculator", "hcf calculator", "gcd calculator"],
  },
  {
    id: "ratio-simplifier",
    name: "Ratio Simplifier",
    description: "Simplify any ratio like 120:45 into simplest form instantly.",
    icon: "Divide",
    path: "/tools/ratio-simplifier",
    category: "utility",
    keywords: ["ratio simplifier", "simplify ratio", "reduce ratio"],
  },
  {
    id: "percentage-change-calculator",
    name: "Percentage Change Calculator",
    description: "Calculate percentage increase or decrease quickly. Free calculator.",
    icon: "Percent",
    path: "/tools/percentage-change-calculator",
    category: "utility",
    keywords: ["percentage change", "percent increase decrease", "percentage difference"],
  },
  {
    id: "mean-median-mode-calculator",
    name: "Mean Median Mode Calculator",
    description: "Calculate mean, median & mode of datasets offline. Free statistics tool.",
    icon: "BarChart3",
    path: "/tools/mean-median-mode-calculator",
    category: "utility",
    keywords: ["mean calculator", "mode calculator", "median calculator", "statistics tool"],
  },
  {
    id: "triangle-area-calculator",
    name: "Triangle Area Calculator",
    description: "Calculate triangle area using base-height or Heron formula. Free geometry tool.",
    icon: "Triangle",
    path: "/tools/triangle-area-calculator",
    category: "utility",
    keywords: ["triangle area calculator", "heron formula", "geometry calculator"],
  },
  {
    id: "circle-calculator",
    name: "Circle Calculator",
    description: "Compute area and circumference with radius/diameter. Fast and free.",
    icon: "Circle",
    path: "/tools/circle-calculator",
    category: "utility",
    keywords: ["circle calculator", "area of circle", "circumference calculator"],
  },
  {
    id: "fibonacci-generator",
    name: "Fibonacci Generator",
    description: "Generate Fibonacci sequence up to any length. Educational math tool.",
    icon: "Hash",
    path: "/tools/fibonacci-generator",
    category: "generator",
    keywords: ["fibonacci generator", "fibonacci numbers", "fibonacci sequence"],
  },
  {
    id: "quadratic-solver",
    name: "Quadratic Equation Solver",
    description: "Solve quadratic equations and show roots instantly. Free calculator.",
    icon: "Calculator",
    path: "/tools/quadratic-solver",
    category: "utility",
    keywords: ["quadratic equation solver", "quadratic calculator", "solve quadratic"],
  },
  {
    id: "modulo-calculator",
    name: "Modulo Calculator",
    description: "Compute modular arithmetic (a mod b) offline. Free remainder calculator.",
    icon: "Percent",
    path: "/tools/modulo-calculator",
    category: "utility",
    keywords: ["modulo calculator", "mod calculator", "remainder calculator"],
  },
  {
    id: "exponent-calculator",
    name: "Exponent Calculator",
    description: "Calculate powers like 8², 5³, etc instantly. Free power calculator.",
    icon: "Superscript",
    path: "/tools/exponent-calculator",
    category: "utility",
    keywords: ["exponent calculator", "power calculator", "calculate powers"],
  },
  {
    id: "simple-interest-calculator",
    name: "Simple Interest Calculator",
    description: "Calculate simple interest & total amount quickly. Free SI calculator.",
    icon: "DollarSign",
    path: "/tools/simple-interest-calculator",
    category: "utility",
    keywords: ["simple interest tool", "si calculator", "interest calculator"],
  },
  {
    id: "compound-interest-calculator",
    name: "Compound Interest Calculator",
    description: "Calculate compound interest over custom time periods. Free CI calculator.",
    icon: "TrendingUp",
    path: "/tools/compound-interest-calculator",
    category: "utility",
    keywords: ["compound interest calculator", "ci tool", "compound interest"],
  },
  {
    id: "age-gap-calculator",
    name: "Age Gap Calculator",
    description: "Calculate age gap between two birthdates. Shows years, months, and days.",
    icon: "Calendar",
    path: "/tools/age-gap-calculator",
    category: "utility",
    keywords: ["age gap calculator", "age difference tool", "calculate age gap"],
  },
  {
    id: "height-converter",
    name: "Height Converter",
    description: "Convert height between feet, cm and inches instantly. Free converter.",
    icon: "Ruler",
    path: "/tools/height-converter",
    category: "utility",
    keywords: ["height converter", "cm to feet", "feet to cm", "inches converter"],
  },
  {
    id: "random-animal-generator",
    name: "Random Animal Generator",
    description: "Generate random animals from a static list. Fun and educational.",
    icon: "Rabbit",
    path: "/tools/random-animal-generator",
    category: "generator",
    keywords: ["random animal", "animal picker", "random animal generator"],
  },
  {
    id: "random-object-generator",
    name: "Random Object Generator",
    description: "Generate random objects from dictionary list. Perfect for creativity.",
    icon: "Box",
    path: "/tools/random-object-generator",
    category: "generator",
    keywords: ["random object generator", "random item picker"],
  },
  {
    id: "random-fake-address",
    name: "Random Fake Address Generator",
    description: "Generate random Indian-style addresses (static safe). For testing only.",
    icon: "MapPin",
    path: "/tools/random-fake-address",
    category: "generator",
    keywords: ["fake address", "random indian address", "test address generator"],
  },
  {
    id: "random-movie-suggestion",
    name: "Random Movie Suggestion",
    description: "Get offline movie suggestions from a static list. Choose what to watch.",
    icon: "Film",
    path: "/tools/random-movie-suggestion",
    category: "generator",
    keywords: ["movie generator", "movie picker", "random movie suggester"],
  },
  {
    id: "random-hindi-name",
    name: "Random Hindi Name Generator",
    description: "Generate offline Indian names for characters, ideas, etc. Modern names.",
    icon: "User",
    path: "/tools/random-hindi-name",
    category: "generator",
    keywords: ["hindi name generator", "indian names", "random name generator"],
  },
  {
    id: "random-tech-stack",
    name: "Random Tech Stack Generator",
    description: "Randomly generate tech stacks for fun or projects. Popular stacks.",
    icon: "Code",
    path: "/tools/random-tech-stack",
    category: "generator",
    keywords: ["tech stack generator", "random technology stack", "web dev stack"],
  },
  {
    id: "random-startup-idea",
    name: "Random Startup Idea Generator",
    description: "Get random startup ideas from offline static library. Inspire innovation.",
    icon: "Lightbulb",
    path: "/tools/random-startup-idea",
    category: "generator",
    keywords: ["startup idea generator", "business idea generator", "random startup ideas"],
  },
  {
    id: "random-riddle",
    name: "Random Riddle Generator",
    description: "Generate random riddles from static list. Brain teasers for fun.",
    icon: "HelpCircle",
    path: "/tools/random-riddle",
    category: "generator",
    keywords: ["riddle generator", "riddles offline", "brain teasers"],
  },
  {
    id: "random-task",
    name: "Random Task Generator",
    description: "Generate challenge tasks (study, fitness, fun). Beat procrastination.",
    icon: "CheckSquare",
    path: "/tools/random-task",
    category: "generator",
    keywords: ["task generator", "challenge idea", "random task generator"],
  },
  {
    id: "random-superhero-name",
    name: "Random Superhero Name Generator",
    description: "Generate random superhero names offline. Perfect for games and stories.",
    icon: "Zap",
    path: "/tools/random-superhero-name",
    category: "generator",
    keywords: ["superhero name generator", "random superhero names", "hero name generator"],
  },
  {
    id: "random-truth-dare",
    name: "Random Truth or Dare Generator",
    description: "Get static truth & dare prompts for fun. Perfect party tool.",
    icon: "PartyPopper",
    path: "/tools/random-truth-dare",
    category: "generator",
    keywords: ["truth dare generator", "party game tool", "truth or dare"],
  },
  {
    id: "random-motivational-quote",
    name: "Random Motivational Quote Generator",
    description: "Generate offline motivational lines instantly. Daily inspiration.",
    icon: "Heart",
    path: "/tools/random-motivational-quote",
    category: "generator",
    keywords: ["motivational quote generator", "inspirational quotes", "random quotes"],
  },
  {
    id: "pdf-compressor",
    name: "PDF Compressor",
    description: "Compress PDF files online for free. Reduce PDF size by up to 90% while maintaining quality. Fast, secure, and works completely offline.",
    icon: "FileDown",
    path: "/tools/pdf-compressor",
    category: "pdf",
    keywords: ["pdf compressor", "reduce pdf size", "compress pdf online free", "pdf optimizer", "shrink pdf file", "pdf size reducer"],
  },
  {
    id: "pdf-password-remover",
    name: "PDF Password Remover",
    description: "Remove password protection from PDF files instantly. Unlock encrypted PDFs securely in your browser without uploading.",
    icon: "Unlock",
    path: "/tools/pdf-password-remover",
    category: "pdf",
    keywords: ["pdf password remover", "unlock pdf", "remove pdf password", "decrypt pdf", "pdf password unlock"],
  },
  {
    id: "pdf-watermark-adder",
    name: "PDF Watermark Adder",
    description: "Add text or image watermarks to PDF files. Protect your documents with custom watermarks. 100% offline processing.",
    icon: "FileImage",
    path: "/tools/pdf-watermark-adder",
    category: "pdf",
    keywords: ["add watermark to pdf", "pdf watermark tool", "watermark pdf online", "pdf protection", "brand pdf"],
  },
  {
    id: "pdf-watermark-remover",
    name: "PDF Watermark Remover",
    description: "Remove watermarks from PDF files easily. Clean your documents by removing unwanted text and image watermarks offline.",
    icon: "Eraser",
    path: "/tools/pdf-watermark-remover",
    category: "pdf",
    keywords: ["remove watermark from pdf", "pdf watermark remover", "clean pdf", "delete pdf watermark"],
  },
  {
    id: "heic-to-jpg",
    name: "HEIC to JPG Converter",
    description: "Convert HEIC images to JPG format instantly. Free iPhone photo converter works offline in your browser. No upload required.",
    icon: "RefreshCw",
    path: "/tools/heic-to-jpg",
    category: "image",
    keywords: ["heic to jpg", "heic converter", "iphone photo converter", "heic to jpeg online", "convert heic"],
  },
  {
    id: "jpg-to-png",
    name: "JPG to PNG Converter",
    description: "Convert JPG images to PNG format online free. Instant conversion with transparency support. Works completely offline.",
    icon: "ArrowRightLeft",
    path: "/tools/jpg-to-png",
    category: "image",
    keywords: ["jpg to png", "jpeg to png converter", "convert jpg to png", "image format converter"],
  },
  {
    id: "png-to-jpg",
    name: "PNG to JPG Converter",
    description: "Convert PNG images to JPG format instantly. Free online converter with quality control. 100% offline and secure.",
    icon: "ArrowRightLeft",
    path: "/tools/png-to-jpg",
    category: "image",
    keywords: ["png to jpg", "png to jpeg converter", "convert png to jpg", "image converter online"],
  },
  {
    id: "video-to-gif",
    name: "Video to GIF Converter",
    description: "Convert videos to animated GIF files. Free MP4 to GIF converter works offline in browser. Control size, fps, and duration.",
    icon: "Film",
    path: "/tools/video-to-gif",
    category: "media",
    keywords: ["video to gif", "mp4 to gif converter", "convert video to gif online", "gif maker", "animated gif"],
  },
  {
    id: "gif-compressor",
    name: "GIF Compressor",
    description: "Compress GIF files online for free. Reduce GIF size while maintaining quality. Fast, secure, works offline in your browser.",
    icon: "Film",
    path: "/tools/gif-compressor",
    category: "media",
    keywords: ["gif compressor", "compress gif online free", "reduce gif size", "gif optimizer", "shrink gif file"],
  },
  {
    id: "mp3-cutter",
    name: "MP3 Cutter",
    description: "Cut and trim MP3 audio files online free. Extract audio segments precisely. Works completely offline in your browser.",
    icon: "Volume2",
    path: "/tools/mp3-cutter",
    category: "media",
    keywords: ["mp3 cutter", "audio trimmer", "cut mp3 online", "trim audio file", "mp3 editor"],
  },
  {
    id: "video-compressor",
    name: "Video Compressor",
    description: "Compress video files online free. Reduce MP4 file size while maintaining quality. Fast, secure, works offline in browser.",
    icon: "Film",
    path: "/tools/video-compressor",
    category: "media",
    keywords: ["video compressor", "compress video online free", "reduce video size", "video optimizer", "shrink video file"],
  },
  {
    id: "background-remover",
    name: "Background Remover",
    description: "Remove image backgrounds instantly. Free online background eraser uses AI technology. Works offline, no upload needed.",
    icon: "Eraser",
    path: "/tools/background-remover",
    category: "image",
    keywords: ["background remover", "remove background", "background eraser", "transparent background", "remove bg"],
  },
  {
    id: "image-upscaler",
    name: "Image Upscaler",
    description: "Upscale and enhance image quality with AI. Free image enlarger increases resolution without losing quality. Offline processing.",
    icon: "Maximize2",
    path: "/tools/image-upscaler",
    category: "image",
    keywords: ["image upscaler", "upscale image", "enhance image quality", "image enlarger", "ai upscaler"],
  },
  {
    id: "excel-to-pdf",
    name: "Excel to PDF Converter",
    description: "Convert Excel files to PDF online for free. Transform XLSX, XLS spreadsheets to PDF format instantly. Works offline in browser.",
    icon: "FileText",
    path: "/tools/excel-to-pdf",
    category: "productivity",
    keywords: ["excel to pdf converter", "xlsx to pdf", "convert excel to pdf free", "spreadsheet to pdf", "xls to pdf online"],
  },
  {
    id: "excel-viewer",
    name: "XLSX Viewer & Editor",
    description: "View and edit Excel files online free. Open XLSX and XLS spreadsheets without Microsoft Excel. 100% offline viewer and editor.",
    icon: "Eye",
    path: "/tools/excel-viewer",
    category: "productivity",
    keywords: ["xlsx viewer", "excel viewer", "view xlsx online", "open excel file", "spreadsheet viewer", "xls reader", "xlsx editor", "excel editor"],
  },
  {
    id: "html-to-pdf",
    name: "HTML to PDF Converter",
    description: "Convert HTML to PDF online free. Transform web pages and HTML code to PDF documents. Works completely offline.",
    icon: "FileText",
    path: "/tools/html-to-pdf",
    category: "developer",
    keywords: ["html to pdf", "convert html to pdf", "html pdf converter", "webpage to pdf", "html2pdf"],
  },
  {
    id: "text-to-pdf",
    name: "Text to PDF Converter",
    description: "Convert plain text to PDF documents with custom formatting. Choose fonts, sizes, add titles, and select page orientation. Free, offline, no signup.",
    icon: "FileText",
    path: "/tools/text-to-pdf",
    category: "pdf",
    keywords: ["text to pdf converter", "convert text to pdf", "text to pdf online", "plain text to pdf", "text document to pdf"],
  },
  {
    id: "audio-noise-remover",
    name: "Audio Noise Remover",
    description: "Remove background noise from audio files free. Clean audio recordings with advanced noise reduction. Offline audio filter.",
    icon: "Mic",
    path: "/tools/audio-noise-remover",
    category: "media",
    keywords: ["audio noise remover", "remove background noise", "noise reduction", "clean audio", "audio filter"],
  },
  {
    id: "gif-to-mp4",
    name: "GIF to MP4 Converter",
    description: "Convert animated GIF to MP4 video format free. Reduce file size and improve quality. Works completely offline in browser.",
    icon: "Film",
    path: "/tools/gif-to-mp4",
    category: "media",
    keywords: ["gif to mp4", "gif to video converter", "convert gif to mp4", "gif converter", "animated gif to video"],
  },
  {
    id: "mp4-to-mp3",
    name: "MP4 to MP3 Converter",
    description: "Extract audio from MP4 video files. Convert MP4 to MP3 online free. Fast video to audio converter works offline.",
    icon: "Volume2",
    path: "/tools/mp4-to-mp3",
    category: "media",
    keywords: ["mp4 to mp3", "video to audio converter", "extract audio from video", "mp4 audio extractor", "convert mp4 to mp3"],
  },
  {
    id: "youtube-thumbnail-downloader",
    name: "YouTube Thumbnail Downloader",
    description: "Download YouTube video thumbnails in all available sizes. Fast, free, and 100% browser-based. No signup or API keys needed.",
    icon: "Image",
    path: "/tools/youtube-thumbnail-downloader",
    category: "media",
    keywords: ["youtube thumbnail downloader", "download youtube thumbnail", "yt thumbnail", "youtube video preview", "thumbnail extractor", "youtube thumbnail download"],
  },
  {
    id: "instagram-profile-picture-downloader",
    name: "Instagram Profile Picture Downloader",
    description: "Download Instagram profile pictures in high quality. Works for any public profile. Free, fast, and 100% browser-based.",
    icon: "Instagram",
    path: "/tools/instagram-profile-picture-downloader",
    category: "media",
    keywords: ["instagram profile picture downloader", "download instagram dp", "instagram profile photo", "ig dp downloader", "instagram avatar downloader"],
  },
  {
    id: "xlsx-to-csv-converter",
    name: "XLSX to CSV Converter",
    description: "Convert Excel XLSX files to CSV format instantly with preview and download. No signup required, 100% offline processing.",
    icon: "ArrowRightLeft",
    path: "/tools/xlsx-to-csv-converter",
    category: "developer",
    keywords: ["xlsx to csv converter", "excel to csv converter", "convert xlsx to csv", "csv converter", "xlsx converter", "excel converter"],
  },
  {
    id: "robots-txt-generator",
    name: "Robots.txt Generator",
    description: "Create SEO-friendly robots.txt files to control search engine crawler access. Generate templates and customize rules instantly.",
    icon: "Code2",
    path: "/tools/robots-txt-generator",
    category: "developer",
    keywords: ["robots.txt generator", "robots file generator", "seo robots.txt", "google crawl directives", "robots.txt maker"],
  },
  {
    id: "sitemap-xml-generator",
    name: "Sitemap.xml Generator",
    description: "Generate XML sitemaps instantly. Submit to Google Search Console. Help search engines discover all your pages.",
    icon: "Code2",
    path: "/tools/sitemap-xml-generator",
    category: "developer",
    keywords: ["sitemap generator", "sitemap.xml creator", "xml sitemap maker", "seo sitemap", "sitemap builder"],
  },
  {
    id: "meta-robots-tag-generator",
    name: "Meta Robots Tag Generator",
    description: "Create meta robots tags for SEO control. Manage indexing, snippets, and crawler behavior easily.",
    icon: "Code2",
    path: "/tools/meta-robots-tag-generator",
    category: "developer",
    keywords: ["meta robots tag generator", "robots meta tag", "seo meta tags", "robots noindex", "crawler directives"],
  },
  {
    id: "canonical-url-generator",
    name: "Canonical URL Generator",
    description: "Create canonical URL tags to prevent duplicate content issues. Fix SEO problems with rel canonical tags.",
    icon: "Code2",
    path: "/tools/canonical-url-generator",
    category: "developer",
    keywords: ["canonical url generator", "rel canonical", "duplicate content fix", "seo canonical tag", "canonical link"],
  },
  {
    id: "open-graph-tag-generator",
    name: "Open Graph Tag Generator",
    description: "Create Open Graph tags for social media sharing. Control how your content appears on Facebook, Twitter, and LinkedIn.",
    icon: "Code2",
    path: "/tools/open-graph-tag-generator",
    category: "developer",
    keywords: ["open graph generator", "og tags", "social media tags", "meta tags generator", "facebook og tags", "twitter card tags"],
  },
  {
    id: "ingredient-health-analyzer",
    name: "Ingredient Health Analyzer",
    description: "Paste any food product ingredient list and get an instant health report — risk levels, health score 0–100, warnings, and diet suitability. 100% private & offline.",
    icon: "Heart",
    path: "/tools/ingredient-health-analyzer",
    category: "utility",
    keywords: ["ingredient health analyzer", "food label checker", "ingredient scanner", "food additive checker", "healthy food analyzer", "ingredient risk checker"],
  },
];

export const getToolIcon = (iconName: string) => {
  const icons: Record<string, any> = {
    Mail,
    Lock,
    QrCode,
    ImageDown,
    Type,
    FileText,
    Code,
    Link2,
    Palette,
    User,
    ShieldCheck,
    Sparkles,
    Brain,
    Maximize2,
    Binary,
    Barcode,
    ArrowRightLeft,
    FileCode,
    Wand2,
    Minimize2,
    Search,
    FileEdit,
    Code2,
    Diff,
    Image,
    Droplets,
    Square,
    Crop,
    Hash,
    FileImage,
    Smile,
    Repeat,
    Link,
    Eye,
    Clock,
    Tags,
    Invoice,
    Receipt,
    Estimate,
    Ruler,
    Calculator,
    TrendingDown,
    Percent,
    Calendar,
    CalendarClock,
    Wallet,
    Volume2,
    Mic,
    RefreshCw,
    FileStack,
    FilePlus,
    RotateCw,
    FilePicture,
    Settings,
    DollarSign,
    PiggyBank,
    CreditCard,
    Divide,
    Shuffle,
    Eraser,
    Unlock,
    ArrowUpDown,
    Users,
    Radio,
    Superscript,
    Subscript,
    Zap,
    BarChart3,
    Space,
    Pipette,
    Grid3x3,
    FileX,
    Rainbow,
    RectangleHorizontal,
    Box,
    Highlighter,
    Plus,
    CheckCircle,
    ALargeSmall,
    FolderTree,
    SunDim,
    Sun,
    FlipHorizontal,
    Contrast,
    PenTool,
    Triangle,
    Circle,
    TrendingUp,
    Rabbit,
    MapPin,
    Film,
    Lightbulb,
    HelpCircle,
    PartyPopper,
    Heart,
    CheckSquare,
    FileDown,
    Instagram,
  };
  return icons[iconName] || Mail;
};

export const getToolById = (id: string) => {
  return tools.find((tool) => tool.id === id);
};

export const getRelatedTools = (currentToolId: string, count: number = 3) => {
  return tools.filter((tool) => tool.id !== currentToolId).slice(0, count);
};
