import { ToolMetadata } from "@shared/schema";
import { 
  Mail, 
  Lock, 
  QrCode, 
  ImageDown, 
  Type, 
  FileText, 
  Code, 
  Link2, 
  Palette, 
  User, 
  ShieldCheck,
  Sparkles,
  Maximize2,
  Binary,
  Barcode,
  ArrowRightLeft,
  FileCode,
  Wand2,
  Minimize2,
  Search,
  FileEdit,
  Code2,
  Diff
} from "lucide-react";

export const tools: ToolMetadata[] = [
  {
    id: "temp-mail",
    name: "Temp Mail Generator",
    description: "Generate temporary disposable emails instantly. Protect your privacy and avoid spam with free temporary email addresses.",
    icon: "Mail",
    path: "/tools/temp-mail",
    category: "privacy",
    keywords: ["temp mail", "temporary email", "disposable email", "free email", "privacy", "spam protection"],
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Create strong, secure passwords instantly. Customize length and complexity for maximum security.",
    icon: "Lock",
    path: "/tools/password-generator",
    category: "privacy",
    keywords: ["password generator", "strong password", "secure password", "random password", "password maker"],
  },
  {
    id: "qr-maker",
    name: "QR Code Maker",
    description: "Generate custom QR codes for URLs, text, or contact information. Download instantly in high quality.",
    icon: "QrCode",
    path: "/tools/qr-maker",
    category: "generator",
    keywords: ["qr code generator", "qr maker", "create qr code", "free qr code", "qr code creator"],
  },
  {
    id: "image-compressor",
    name: "Image Compressor",
    description: "Compress images without losing quality. Reduce file size instantly and download optimized images.",
    icon: "ImageDown",
    path: "/tools/image-compressor",
    category: "utility",
    keywords: ["image compressor", "compress image", "reduce image size", "optimize image", "image optimizer"],
  },
  {
    id: "text-case-converter",
    name: "Text Case Converter",
    description: "Convert text to uppercase, lowercase, title case, camel case, and more. Fast and simple text transformation.",
    icon: "Type",
    path: "/tools/text-case-converter",
    category: "utility",
    keywords: ["text case converter", "uppercase", "lowercase", "title case", "camel case", "snake case", "text transform"],
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, and paragraphs instantly. Perfect for writers and students.",
    icon: "FileText",
    path: "/tools/word-counter",
    category: "utility",
    keywords: ["word counter", "character counter", "text analyzer", "word count", "writing tool"],
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Beautify and validate JSON data. Format, minify, and fix JSON syntax errors instantly.",
    icon: "Code",
    path: "/tools/json-formatter",
    category: "generator",
    keywords: ["json formatter", "json beautifier", "json validator", "json minifier", "format json"],
  },
  {
    id: "url-encoder",
    name: "URL Encoder/Decoder",
    description: "Encode or decode URLs instantly. Convert special characters for safe URL transmission.",
    icon: "Link2",
    path: "/tools/url-encoder",
    category: "utility",
    keywords: ["url encoder", "url decoder", "encode url", "decode url", "url escape"],
  },
  {
    id: "color-picker",
    name: "Color Picker",
    description: "Select and copy colors in HEX, RGB, and HSL formats. Perfect for designers and developers.",
    icon: "Palette",
    path: "/tools/color-picker",
    category: "generator",
    keywords: ["color picker", "hex color", "rgb color", "color converter", "color tool"],
  },
  {
    id: "username-generator",
    name: "Username Generator",
    description: "Generate creative and unique usernames instantly. Perfect for gaming, social media, and more.",
    icon: "User",
    path: "/tools/username-generator",
    category: "generator",
    keywords: ["username generator", "random username", "gamer tag", "username ideas", "name generator"],
  },
  {
    id: "password-strength-checker",
    name: "Password Strength Checker",
    description: "Check how strong your password is. Get instant feedback and security recommendations.",
    icon: "ShieldCheck",
    path: "/tools/password-strength-checker",
    category: "privacy",
    keywords: ["password strength", "password checker", "security checker", "password test", "strong password"],
  },
  {
    id: "text-summarizer",
    name: "AI Text Summarizer",
    description: "Summarize any text with AI power. Upload PDFs or paste articles for instant summaries.",
    icon: "Sparkles",
    path: "/tools/text-summarizer",
    category: "utility",
    keywords: ["text summarizer", "ai summarizer", "summarize text", "pdf summarizer", "article summarizer"],
  },
  {
    id: "image-resizer",
    name: "Image Resizer",
    description: "Resize JPG, PNG or WebP images online. Change width & height instantly. Fast, offline & private.",
    icon: "Maximize2",
    path: "/tools/image-resizer",
    category: "utility",
    keywords: ["image resizer", "resize image online", "image scaling tool", "change image size"],
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder/Decoder",
    description: "Convert text to Base64 or decode Base64 to text instantly. 100% offline, secure & fast.",
    icon: "Binary",
    path: "/tools/base64-encoder",
    category: "utility",
    keywords: ["base64 encoder", "base64 decoder online", "encode text", "decode base64"],
  },
  {
    id: "barcode-generator",
    name: "Barcode Generator",
    description: "Generate high-quality barcodes instantly. Supports Code128, EAN, UPC & more. Download in PNG.",
    icon: "Barcode",
    path: "/tools/barcode-generator",
    category: "generator",
    keywords: ["barcode generator", "code128 barcode", "ean barcode", "upc creator"],
  },
  {
    id: "json-csv-converter",
    name: "JSON to CSV Converter",
    description: "Convert JSON to CSV or CSV to JSON instantly. 100% free, offline, secure and runs completely in your browser.",
    icon: "ArrowRightLeft",
    path: "/tools/json-csv-converter",
    category: "utility",
    keywords: ["json to csv", "csv converter online", "convert json csv", "offline converter"],
  },
  {
    id: "json-yaml-converter",
    name: "JSON to YAML Converter",
    description: "Convert JSON to YAML or YAML to JSON instantly. Fast, free and 100% offline-secure.",
    icon: "FileCode",
    path: "/tools/json-yaml-converter",
    category: "utility",
    keywords: ["json to yaml", "yaml converter", "yaml to json"],
  },
  {
    id: "code-beautifier",
    name: "Code Beautifier",
    description: "Beautify and format HTML, CSS or JavaScript instantly. Offline, safe and free tool for developers.",
    icon: "Wand2",
    path: "/tools/code-beautifier",
    category: "utility",
    keywords: ["code beautifier", "html formatter", "css beautify", "js formatter"],
  },
  {
    id: "css-minifier",
    name: "CSS Minifier",
    description: "Compress and minify CSS code instantly with a fast offline tool. Free and fully private.",
    icon: "Minimize2",
    path: "/tools/css-minifier",
    category: "utility",
    keywords: ["css minifier", "compress css", "minimize css online"],
  },
  {
    id: "js-minifier",
    name: "JavaScript Minifier",
    description: "Minify JavaScript instantly. Free, offline and secure — no code uploaded or stored.",
    icon: "Minimize2",
    path: "/tools/js-minifier",
    category: "utility",
    keywords: ["js minifier", "javascript compressor", "minify js online"],
  },
  {
    id: "html-beautifier",
    name: "HTML Beautifier",
    description: "Format and clean messy HTML code instantly. Offline, quick and perfect for developers.",
    icon: "FileCode",
    path: "/tools/html-beautifier",
    category: "utility",
    keywords: ["html beautifier", "format html code", "html formatter online"],
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test and debug your regex patterns instantly with live results. Free, offline and secure.",
    icon: "Search",
    path: "/tools/regex-tester",
    category: "utility",
    keywords: ["regex tester", "regular expression tester", "test regex online"],
  },
  {
    id: "markdown-editor",
    name: "Markdown Editor",
    description: "Write or paste Markdown and see instant live HTML preview. Free, offline and private.",
    icon: "FileEdit",
    path: "/tools/markdown-editor",
    category: "utility",
    keywords: ["markdown editor", "markdown preview", "md editor online"],
  },
  {
    id: "api-snippet-builder",
    name: "API Snippet Builder",
    description: "Create API request snippets in cURL or JavaScript fetch instantly. Offline, secure and direct.",
    icon: "Code2",
    path: "/tools/api-snippet-builder",
    category: "utility",
    keywords: ["curl generator", "fetch code generator", "api request builder"],
  },
  {
    id: "text-differ",
    name: "Text Differ",
    description: "Compare two texts or code blocks instantly and highlight differences. Offline and free.",
    icon: "Diff",
    path: "/tools/text-differ",
    category: "utility",
    keywords: ["text compare", "code diff tool", "diff checker online"],
  },
];

export const getToolIcon = (iconName: string) => {
  const icons: Record<string, any> = {
    Mail,
    Lock,
    QrCode,
    ImageDown,
    Type,
    FileText,
    Code,
    Link2,
    Palette,
    User,
    ShieldCheck,
    Sparkles,
    Maximize2,
    Binary,
    Barcode,
    ArrowRightLeft,
    FileCode,
    Wand2,
    Minimize2,
    Search,
    FileEdit,
    Code2,
    Diff,
  };
  return icons[iconName] || Mail;
};

export const getToolById = (id: string) => {
  return tools.find((tool) => tool.id === id);
};

export const getRelatedTools = (currentToolId: string, count: number = 3) => {
  return tools.filter((tool) => tool.id !== currentToolId).slice(0, count);
};
