import { PasswordGeneratorTool } from "@/components/tools/PasswordGeneratorTool";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { useSEO, StructuredData, generateFAQSchema, generateSoftwareApplicationSchema, OG_IMAGES, type FAQItem, generateBreadcrumbSchema } from "@/lib/seo";
import { getRelatedTools } from "@/lib/tools";
import { Copy, RefreshCw, Lock, Check, X, Shield, ShieldCheck, Users, Briefcase, Info, Mail, CreditCard, Code, WifiOff, Zap, Instagram, Facebook, Apple, Landmark, User, GraduationCap, Fingerprint } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { Link } from "wouter";
import { Breadcrumb } from "@/components/Breadcrumb";

export default function PasswordGenerator() {
  const [password, setPassword] = useState("");
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  useSEO({
    title: "Strong Password Generator (Free, Secure, No Signup) – 2026",
    description: "Generate secure random passwords instantly using Web Crypto API. 100% private, works offline, no signup required. Create 12–32 character strong passwords safely.",
    keywords: "strong password generator, password generator free, random password generator, secure password generator, password generator no signup, offline password generator, 16 character password generator",
    canonicalUrl: "https://tools.pixocraft.in/tools/password-generator",
    ogImage: OG_IMAGES.passwordGenerator,
  });

  const softwareSchema = generateSoftwareApplicationSchema({
    name: "Pixocraft Strong Password Generator",
    description: "Generate secure random passwords instantly using Web Crypto API. 100% private and offline.",
    url: "https://tools.pixocraft.in/tools/password-generator",
    category: "SecurityApplication"
  });

  const comparisonData = [
    { feature: "Runs Fully Offline", pixocraft: true, others: false },
    { feature: "Stores Passwords", pixocraft: false, others: true },
    { feature: "Requires Signup", pixocraft: false, others: true },
    { feature: "Uses Web Crypto API", pixocraft: true, others: false },
    { feature: "Tracks Users", pixocraft: false, others: true },
  ];

  const faqItems: FAQItem[] = [
    {
      question: "Is an online password generator safe to use?",
      answer: "Yes, provided the generator runs locally in your browser. Pixocraft's tool uses the Web Crypto API for cryptographically secure randomization and never transmits data to any server. Because all generation happens on your device, your passwords are never stored, logged, or intercepted. Once you close the browser tab, the data is completely wiped from memory, making it significantly safer than server-based generators."
    },
    {
      question: "Can hackers crack randomly generated passwords?",
      answer: "Randomly generated passwords with high entropy are computationally infeasible to crack. For example, a 16-character password with mixed character types has over 10^28 combinations. Even using massive GPU clusters that attempt a trillion guesses per second, it would take longer than the age of the universe to exhaust the search space. The combination of true cryptographic randomness and sufficient length (12+ characters) effectively removes patterns that attackers exploit in dictionary or rule-based attacks."
    },
    {
      question: "What is the best password length for security?",
      answer: "For most personal accounts, 12 to 16 characters is the industry standard recommended by NIST. However, for sensitive accounts like banking, primary email, or work credentials, we recommend 16 to 24 characters. Every additional character increases the difficulty of a brute-force attack exponentially. Our generator allows up to 128 characters for those requiring extreme high-security solutions."
    },
    {
      question: "Should I use different passwords for every account?",
      answer: "Absolutely. Password reuse is the leading cause of account takeovers. If a single service you use is compromised, attackers will use those credentials to try and log into other popular platforms (a technique called credential stuffing). By generating a unique, high-entropy password for every account, you ensure that a breach at one company doesn't compromise your entire digital identity."
    },
    {
      question: "Are passwords generated by this tool stored anywhere?",
      answer: "No. Pixocraft is built on a 'Privacy First' philosophy. The generation logic uses JavaScript's window.crypto API, which runs entirely on your local machine. No network requests are made during the generation process, and there is no database or logging system attached to this tool. Your privacy is guaranteed by the technical architecture of the application."
    },
    {
      question: "How should I store my generated passwords securely?",
      answer: "The most secure way to manage unique, complex passwords is by using a dedicated password manager like Bitwarden, 1Password, or Dashlane. These tools use zero-knowledge encryption to store your database. We strongly advise against storing passwords in plain text files, browser notes, or physical notebooks which can be easily lost or stolen."
    },
    {
      question: "What makes a password strong and secure?",
      answer: "A strong password is characterized by three pillars: Randomness, Length, and Complexity. Randomness ensures there are no predictable human patterns (like birthdates or common words). Length increases the search space for attackers. Complexity (mixing uppercase, lowercase, numbers, and symbols) forces attackers to use larger character sets, increasing the time required for any successful crack attempt."
    }
  ];

  const faqSchema = generateFAQSchema(faqItems);
  
  const breadcrumbSchema = generateBreadcrumbSchema([
    { name: "Home", url: "/" },
    { name: "Tools", url: "/tools" },
    { name: "Password Generator", url: "/tools/password-generator" }
  ]);
  
  return (
    <>
      <StructuredData data={faqSchema} />
      <StructuredData data={softwareSchema} />
      <StructuredData data={breadcrumbSchema} />
      <div className="mb-6 px-4 pt-4">
        <Breadcrumb
          items={[
            { label: "Home", url: "/" },
            { label: "Tools", url: "/tools" },
            { label: "Privacy Tools", url: "/tools/privacy" },
            { label: "Password Generator" },
          ]}
        />
      </div>
      <div className="min-h-screen py-12">
        <div className="container mx-auto px-4 max-w-7xl">

          {/* Page Header */}
          <div className="text-center space-y-8 mb-16">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-primary text-sm font-black uppercase tracking-widest animate-pulse border border-primary/20">
              <Zap className="h-4 w-4" /> 2026 Enhanced Security Edition
            </div>
            <h1 className="text-4xl md:text-6xl lg:text-7xl font-black tracking-tight leading-[1.1]">
              Strong Password Generator <span className="bg-gradient-to-r from-primary to-blue-600 bg-clip-text text-transparent block mt-2">100% Private & Secure</span>
            </h1>
            <p className="text-xl md:text-2xl text-muted-foreground max-w-3xl mx-auto leading-relaxed font-medium">
              Generate cryptographically secure random passwords instantly using <span className="text-foreground font-bold">Web Crypto API</span>. No signup, no tracking, works fully offline.
            </p>
            <div className="flex flex-wrap items-center justify-center gap-4 text-sm">
              <div className="flex items-center gap-2 px-4 py-2 rounded-2xl bg-green-500/10 text-green-600 dark:text-green-400 font-bold border border-green-500/20">
                <ShieldCheck className="h-4 w-4" /> Web Crypto API
              </div>
              <div className="flex items-center gap-2 px-4 py-2 rounded-2xl bg-blue-500/10 text-blue-600 dark:text-blue-400 font-bold border border-blue-500/20">
                <WifiOff className="h-4 w-4" /> Works Offline
              </div>
              <div className="flex items-center gap-2 px-4 py-2 rounded-2xl bg-orange-500/10 text-orange-600 dark:text-orange-400 font-bold border border-orange-500/20">
                <Lock className="h-4 w-4" /> Zero Logging
              </div>
            </div>
          </div>

          {/* Main Tool Interface */}
          <div className="max-w-3xl mx-auto mb-8 relative">
            <div className="absolute -inset-1 bg-gradient-to-r from-primary/20 to-blue-500/20 rounded-2xl blur opacity-25 group-hover:opacity-50 transition duration-1000 group-hover:duration-200"></div>
            <PasswordGeneratorTool initialLength={16} />
          </div>

          {/* Why Use Block */}
          <div className="max-w-3xl mx-auto mb-16">
            <Card className="bg-primary/5 border-primary/10 shadow-sm">
              <CardContent className="pt-6">
                <h2 className="text-lg font-black mb-4 flex items-center gap-2 text-primary uppercase tracking-tighter">
                  <Fingerprint className="h-5 w-5" /> Why Use Pixocraft Password Generator?
                </h2>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-3">
                  {[
                    "Uses cryptographically secure randomness",
                    "Runs entirely inside your browser",
                    "No data transmission or logging",
                    "Works even when offline",
                    "Generates high-entropy passwords instantly"
                  ].map((benefit, i) => (
                    <div key={i} className="flex items-center gap-2 text-sm font-bold text-muted-foreground">
                      <Check className="h-4 w-4 text-primary shrink-0" />
                      {benefit}
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Trust Badge Section */}
          <div className="max-w-5xl mx-auto mb-16">
            <h2 className="text-xl font-bold mb-8 text-center">Why Pixocraft Password Generator Is Trusted</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-6">
              {[
                { title: "Client-Side Generation", desc: "Passwords are created directly in your browser.", icon: ShieldCheck },
                { title: "Web Crypto API", desc: "Uses secure cryptographic randomness.", icon: Lock },
                { title: "No Server Storage", desc: "Passwords are never transmitted or stored.", icon: X },
                { title: "Works Offline", desc: "Generator functions without internet access.", icon: WifiOff },
                { title: "Zero Tracking", desc: "No analytics scripts or password logging.", icon: Users }
              ].map((item, i) => (
                <div key={i} className="flex flex-col items-center text-center p-4 rounded-xl bg-muted/20 border border-primary/5">
                  <item.icon className="h-8 w-8 text-primary mb-3" />
                  <h3 className="font-bold text-sm mb-1">{item.title}</h3>
                  <p className="text-xs text-muted-foreground">{item.desc}</p>
                </div>
              ))}
            </div>
          </div>

          {/* New Optimized Links Section */}
          <section className="mb-16">
            <div className="max-w-4xl mx-auto">
              <h2 className="text-3xl font-bold mb-8 text-center">Specialized Password Generators</h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                {[
                  { title: "Gmail Password", desc: "Secure your Google ecosystem", url: "/strong-password-for-gmail", icon: Mail },
                  { title: "Instagram Password", desc: "Protect your creator brand", url: "/strong-password-for-instagram", icon: Instagram },
                  { title: "Facebook Password", desc: "Social profile defense", url: "/strong-password-for-facebook", icon: Facebook },
                  { title: "Banking Password", desc: "Financial-grade security", url: "/banking-password-generator", icon: Landmark },
                  { title: "Apple ID Password", desc: "Secure your iCloud data", url: "/apple-id-password-generator", icon: Apple }
                ].map((tool, i) => (
                  <Link key={i} href={tool.url} className="group">
                    <Card className="hover-elevate transition-all border-primary/5">
                      <CardHeader className="p-5">
                        <div className="flex items-center gap-3 mb-2">
                          <div className="p-2 rounded-lg bg-primary/10 text-primary group-hover:bg-primary group-hover:text-white transition-colors">
                            <tool.icon className="h-5 w-5" />
                          </div>
                          <CardTitle className="text-lg group-hover:text-primary transition-colors">{tool.title}</CardTitle>
                        </div>
                        <CardDescription>{tool.desc}</CardDescription>
                      </CardHeader>
                    </Card>
                  </Link>
                ))}
              </div>
            </div>
          </section>

          {/* Comparison Table Section */}
          <section className="mb-16">
            <h2 className="text-3xl font-bold mb-8 text-center">Why Pixocraft Password Generator is More Private</h2>
            <div className="max-w-4xl mx-auto overflow-hidden rounded-xl border bg-card shadow-lg">
              <table className="w-full text-left">
                <thead className="bg-muted/50 border-b">
                  <tr>
                    <th className="px-6 py-4 font-bold">Feature</th>
                    <th className="px-6 py-4 font-bold text-primary">Pixocraft</th>
                    <th className="px-6 py-4 font-bold text-muted-foreground">Most Online Generators</th>
                  </tr>
                </thead>
                <tbody className="divide-y">
                  {comparisonData.map((row, i) => (
                    <tr key={i} className="hover:bg-muted/30 transition-colors">
                      <td className="px-6 py-4 font-medium">{row.feature}</td>
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-2 text-green-600 font-bold">
                          {row.pixocraft ? <Check className="h-5 w-5" /> : <X className="h-5 w-5 text-destructive" />}
                          {row.pixocraft ? "Yes" : "Never"}
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-2 text-muted-foreground">
                          {row.others ? <X className="h-5 w-5 text-destructive" /> : <Check className="h-5 w-5 text-green-600" />}
                          {row.others ? "Often / Sometimes" : "No"}
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          {/* Internal Linking Cluster */}
          <section className="mb-16">
            <h2 className="text-2xl font-bold mb-6 text-center">Specific Password Length Generators</h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-4xl mx-auto">
              {[
                { length: 12, label: "12 Characters", href: "/12-character-password-generator" },
                { length: 16, label: "16 Characters", href: "/16-character-password-generator" },
                { length: 20, label: "20 Characters", href: "/20-character-password-generator" },
                { length: 32, label: "32 Characters", href: "/32-character-password-generator" },
              ].map((item) => (
                <Link key={item.length} href={item.href} className="flex flex-col items-center justify-center p-4 rounded-xl border bg-card hover:border-primary transition-all hover-elevate group text-center">
                  <div className="h-10 w-10 rounded-full bg-primary/5 flex items-center justify-center mb-2 group-hover:bg-primary group-hover:text-white transition-colors">
                    <ShieldCheck className="h-5 w-5" />
                  </div>
                  <span className="text-sm font-bold group-hover:text-primary transition-colors">{item.label}</span>
                </Link>
              ))}
            </div>
          </section>

          {/* Technical Authority Sections */}
          <section className="prose prose-slate dark:prose-invert max-w-4xl mx-auto space-y-12">
            <div className="bg-card p-8 rounded-2xl border shadow-sm not-prose">
              <h2 className="text-3xl font-bold mb-4">How Our Secure Password Generator Works</h2>
              <p className="text-lg leading-relaxed text-muted-foreground">
                Unlike traditional generators that use <code>Math.random()</code>, which is predictable and not suitable for security, our tool uses the <strong>Web Crypto API</strong> (<code>window.crypto.getRandomValues</code>). This provides <strong>cryptographically secure pseudo-random numbers (CSPRNG)</strong>, ensuring that your passwords have maximum entropy and are computationally infeasible to crack with current technology.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 not-prose">
              <Card className="bg-muted/30 border-primary/10 shadow-none">
                <CardHeader>
                  <CardTitle className="text-xl flex items-center gap-2"><Lock className="h-5 w-5 text-primary" /> 100% Private & Offline</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground leading-relaxed text-sm">
                    Your privacy is our priority. This tool runs entirely in your browser. No data is sent to our servers, no passwords are logged, and no tracking is used. You can even use this tool while offline.
                  </p>
                </CardContent>
              </Card>
              <Card className="bg-muted/30 border-primary/10 shadow-none">
                <CardHeader>
                  <CardTitle className="text-xl flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary" /> Computationally Infeasible Security</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground leading-relaxed text-sm">
                    A 16-character password generated here has more combinations than there are atoms in the observable universe. It would take current supercomputers trillions of years to crack.
                  </p>
                </CardContent>
              </div>

            {/* Security Transparency Section */}
            <div id="security-transparency" className="not-prose space-y-8">
              <h2 className="text-3xl font-bold text-center pt-8">Security Transparency: How Pixocraft Generates Passwords</h2>
              <div className="bg-card p-8 rounded-2xl border space-y-8 shadow-sm">
                <p className="text-lg leading-relaxed text-muted-foreground text-center max-w-3xl mx-auto">
                  Pixocraft Tools uses modern browser cryptography to generate truly unpredictable passwords. Unlike many basic generators that rely on predictable random functions, this tool uses the Web Crypto API to produce cryptographically secure randomness suitable for protecting sensitive credentials.
                </p>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                  <div className="space-y-4">
                    <h3 className="text-xl font-bold flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary" /> Cryptographically Secure Randomness</h3>
                    <p className="text-muted-foreground leading-relaxed text-sm">
                      Passwords are generated using the browser's native cryptographic random number generator: <code>window.crypto.getRandomValues()</code>. This API produces CSPRNG values designed for security-critical operations, ensuring maximum entropy and unpredictability.
                    </p>
                  </div>
                  <div className="space-y-4">
                    <h3 className="text-xl font-bold flex items-center gap-2"><X className="h-5 w-5 text-destructive" /> Why We Never Use Math.random()</h3>
                    <p className="text-muted-foreground leading-relaxed text-sm">
                      Traditional random functions such as <code>Math.random()</code>, timestamp seeded randomness, or predictable algorithms are not suitable for security applications because they can produce patterns that attackers may exploit. Pixocraft avoids these methods entirely.
                    </p>
                  </div>
                </div>

                <div className="pt-6 border-t">
                  <h3 className="text-xl font-bold mb-4">Client-Side Password Generation</h3>
                  <p className="text-muted-foreground leading-relaxed text-sm mb-4">
                    All password generation occurs inside your browser. This guarantees:
                  </p>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    {[
                      "No password transmission",
                      "No server-side logging",
                      "No password storage",
                      "No external API calls"
                    ].map((item, i) => (
                      <div key={i} className="flex items-center gap-2 text-sm text-muted-foreground font-medium">
                        <Check className="h-4 w-4 text-green-500" /> {item}
                      </div>
                    ))}
                  </div>
                  <p className="mt-6 text-sm font-black text-primary italic bg-primary/5 p-3 rounded-lg border border-primary/10 inline-block">Your generated password never leaves your device.</p>
                </div>
              </div>
            </div>

            {/* Entropy Education Section */}
            <div id="entropy-meaning" className="not-prose space-y-8">
              <h2 className="text-3xl font-bold text-center pt-8">What Does 105 Bits of Entropy Actually Mean?</h2>
              <div className="bg-muted/30 p-8 rounded-2xl border space-y-8 shadow-inner">
                <p className="text-lg leading-relaxed text-muted-foreground">
                  Entropy measures how unpredictable a password is. A typical 16-character password generated by this tool contains approximately 105 bits of entropy. This represents the size of the possible search space attackers must explore.
                </p>
                
                <div className="bg-background p-6 rounded-xl border shadow-sm text-center">
                  <h3 className="font-bold mb-4 text-primary">Example: 105 Bits of Entropy</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed mb-4">
                    A password with 105 bits of entropy has approximately <strong>2<sup>105</sup></strong> possible combinations. This number is astronomically large. Even extremely powerful GPU clusters attempting billions of guesses per second would require longer than the age of the universe to brute-force such a password.
                  </p>
                  <p className="text-xs font-bold text-muted-foreground/60 uppercase tracking-widest">Entropy grows exponentially with password length.</p>
                </div>

                <div className="overflow-hidden rounded-xl border bg-background shadow-sm">
                  <table className="w-full text-left text-sm">
                    <thead className="bg-muted border-b">
                      <tr>
                        <th className="px-6 py-4 font-bold">Password Length</th>
                        <th className="px-6 py-4 font-bold">Approx Entropy</th>
                        <th className="px-6 py-4 font-bold">Security Level</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y">
                      <tr><td className="px-6 py-4">12 characters</td><td className="px-6 py-4">~78 bits</td><td className="px-6 py-4 font-black text-blue-600">Strong</td></tr>
                      <tr className="bg-primary/5">
                        <td className="px-6 py-4 font-black text-primary">16 characters</td>
                        <td className="px-6 py-4 font-black text-primary">~105 bits</td>
                        <td className="px-6 py-4 font-black text-primary">Very Strong</td>
                      </tr>
                      <tr><td className="px-6 py-4">20 characters</td><td className="px-6 py-4">~131 bits</td><td className="px-6 py-4 font-black text-emerald-600">High Security</td></tr>
                      <tr><td className="px-6 py-4">32 characters</td><td className="px-6 py-4">~210 bits</td><td className="px-6 py-4 font-black text-primary">Extreme</td></tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

            {/* Password Strength Science Section */}
            <div id="strength-science" className="not-prose space-y-8">
              <h2 className="text-3xl font-bold text-center pt-8">How Password Strength Is Calculated</h2>
              <Card className="border-primary/5 shadow-sm overflow-hidden">
                <CardContent className="p-0">
                  <div className="bg-muted/50 p-8 flex justify-center border-b">
                    <code className="text-xl md:text-3xl font-black text-primary tracking-tight">
                      Entropy = L × log<sub>2</sub>(R)
                    </code>
                  </div>
                  <div className="p-8 space-y-8">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                      <div className="space-y-4">
                        <h4 className="font-bold text-sm uppercase tracking-widest text-muted-foreground">The Formula Variables</h4>
                        <ul className="space-y-2 text-sm">
                          <li><strong>L:</strong> Password Length</li>
                          <li><strong>R:</strong> Size of Character Set (Pool)</li>
                        </ul>
                      </div>
                      <div className="space-y-4">
                        <h4 className="font-bold text-sm uppercase tracking-widest text-muted-foreground">Common Pool Sizes (R)</h4>
                        <div className="flex flex-wrap gap-2">
                          <Badge variant="secondary">Lowercase: 26</Badge>
                          <Badge variant="secondary">Uppercase: 26</Badge>
                          <Badge variant="secondary">Numbers: 10</Badge>
                          <Badge variant="secondary">Symbols: ~33</Badge>
                        </div>
                      </div>
                    </div>
                    <div className="p-6 rounded-xl bg-primary/5 border border-primary/10">
                      <p className="text-sm text-muted-foreground leading-relaxed">
                        Total possible characters ≈ 95. Each additional character multiplies the number of possible combinations dramatically. A 16-character password using a 95-character set produces approximately <strong>105 bits of entropy</strong>, making brute-force attacks <strong>computationally infeasible</strong> using modern hardware.
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* Why Random Passwords Section */}
            <div id="why-random" className="not-prose space-y-8">
              <h2 className="text-3xl font-bold text-center pt-8">Why Random Passwords Are More Secure</h2>
              <div className="bg-card p-8 rounded-2xl border shadow-sm space-y-6">
                <p className="text-lg leading-relaxed text-muted-foreground">
                  Human-generated passwords are fundamentally predictable. Even when we try to be "creative," we often fall into patterns that are easily cracked by modern attack tools. Here is why cryptographically random passwords are superior:
                </p>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                  <div className="space-y-4">
                    <h3 className="text-xl font-bold flex items-center gap-2 text-primary"><Users className="h-5 w-5" /> Human Predictability</h3>
                    <p className="text-sm text-muted-foreground leading-relaxed">
                      Humans tend to use meaningful dates, names, or common keyboard patterns (like "qwerty" or "12345"). Attackers use <strong>dictionary attacks</strong> that target these known linguistic and behavioral patterns, bypassing even long passwords if they are based on natural language.
                    </p>
                  </div>
                  <div className="space-y-4">
                    <h3 className="text-xl font-bold flex items-center gap-2 text-primary"><ShieldCheck className="h-5 w-5" /> Eliminating Patterns</h3>
                    <p className="text-sm text-muted-foreground leading-relaxed">
                      Cryptographically random passwords remove all predictable logic. Because there are no "words" or "sequences," an attacker cannot use intelligence to narrow down the search. They are forced to use <strong>brute-force attacks</strong>, which must explore every possible combination—a task that is <strong>computationally infeasible</strong> for high-entropy passwords.
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Password Security Best Practices Section */}
            <div id="security-best-practices" className="not-prose space-y-8 pb-12">
              <h2 className="text-3xl font-bold text-center pt-8">Password Security Best Practices</h2>
              <div className="bg-primary/5 p-8 rounded-2xl border border-primary/20 space-y-8 shadow-sm">
                <div className="grid grid-cols-1 gap-4">
                  {[
                    "Use at least 16 characters for important accounts",
                    "Never reuse passwords across multiple services",
                    "Enable Two-Factor Authentication (2FA) wherever possible",
                    "Store passwords in a secure password manager",
                    "Avoid dictionary words, names, or predictable patterns"
                  ].map((item, i) => (
                    <div key={i} className="flex items-start gap-4 p-4 rounded-xl bg-background border shadow-sm">
                      <div className="h-6 w-6 rounded-full bg-primary/10 flex items-center justify-center shrink-0 mt-0.5">
                        <Check className="h-4 w-4 text-primary" />
                      </div>
                      <span className="font-bold text-lg leading-tight">{item}</span>
                    </div>
                  ))}
                </div>
                
                <div className="pt-8 border-t border-primary/10 space-y-4">
                  <p className="font-black uppercase tracking-widest text-xs text-muted-foreground">Internal Security Resources</p>
                  <div className="flex flex-wrap gap-3">
                    <Link href="/tools/password-strength-checker">
                      <Button variant="outline" size="sm" className="rounded-xl font-bold hover:bg-primary hover:text-white transition-all">Password Strength Checker</Button>
                    </Link>
                    <Link href="/20-character-password-generator">
                      <Button variant="outline" size="sm" className="rounded-xl font-bold hover:bg-primary hover:text-white transition-all">20-Char Generator</Button>
                    </Link>
                    <Link href="/strong-password-for-gmail">
                      <Button variant="outline" size="sm" className="rounded-xl font-bold hover:bg-primary hover:text-white transition-all">Gmail Generator</Button>
                    </Link>
                    <Link href="/banking-password-generator">
                      <Button variant="outline" size="sm" className="rounded-xl font-bold hover:bg-primary hover:text-white transition-all">Banking Generator</Button>
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* FAQ Section */}
          <section className="bg-muted/30 p-8 rounded-2xl border border-primary/10 max-w-4xl mx-auto mb-16">
            <h2 className="text-3xl font-bold mb-6 text-center">Frequently Asked Questions</h2>
            <Accordion type="single" collapsible className="w-full">
              {faqItems.map((item, i) => (
                <AccordionItem key={i} value={`faq-${i}`} className="border-b-primary/10">
                  <AccordionTrigger className="text-left font-bold hover:text-primary transition-colors py-4">
                    {item.question}
                  </AccordionTrigger>
                  <AccordionContent className="text-muted-foreground leading-relaxed text-sm pb-4">
                    {item.answer}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </section>

          {/* Related Tools Section */}
          <section className="max-w-4xl mx-auto">
            <h2 className="text-2xl font-bold mb-8 text-center">Explore More Tools</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {relatedTools.map((tool) => (
                <Link key={tool.path} href={tool.path}>
                  <Card className="hover-elevate cursor-pointer h-full border-primary/5">
                    <CardHeader className="p-5">
                      <CardTitle className="text-lg flex items-center gap-2">
                        <tool.icon className="h-5 w-5 text-primary" />
                        {tool.title}
                      </CardTitle>
                      <CardDescription className="line-clamp-2">{tool.description}</CardDescription>
                    </CardHeader>
                  </Card>
                </Link>
              ))}
            </div>
          </section>
        </div>
      </div>
    </>
  );
}
