import { useState } from "react";
import { Link } from "wouter";
import {
  useSEO,
  StructuredData,
  generateFAQSchema,
  generateSoftwareApplicationSchema,
  generateBreadcrumbSchema,
  generateHowToSchema,
} from "@/lib/seo";
import { Breadcrumb } from "@/components/Breadcrumb";
import { SignatureTopPromo, SignatureRelatedTools } from "@/components/SignatureInternalLinks";
import SignatureToolSection from "@/components/SignatureToolSection";
import {
  Shield, Zap, Check, FileText, ChevronDown, ChevronUp,
  ArrowRight, Lock, BadgeCheck, Download, Smartphone,
  Star, Users, XCircle, CreditCard, Landmark, Phone,
  FileCheck, UserCheck, Building2, AlertCircle,
} from "lucide-react";

const CANONICAL = "https://tools.pixocraft.in/tools/signature-for-aadhaar";
const LAST_UPDATED = "March 2026";

const FAQS = [
  {
    question: "Is a signature required on Aadhaar card?",
    answer:
      "Aadhaar card itself does not have a signature field. However, your signature is required on Aadhaar-related forms — such as the Aadhaar enrolment form, correction form, and UIDAI update requests — where you sign manually or upload an image of your signature.",
  },
  {
    question: "Can I add a signature to my Aadhaar card?",
    answer:
      "No, you cannot add a signature directly onto the Aadhaar card image or document. Aadhaar is a UIDAI-issued identity document and cannot be modified. Your signature is only used on the forms and applications that reference your Aadhaar number.",
  },
  {
    question: "What is Aadhaar eSign?",
    answer:
      "Aadhaar eSign is a government-backed electronic signature service provided by UIDAI and licensed Authorised Signatory Applications (ASPs). It uses OTP-based authentication on your Aadhaar number to apply a legally valid digital signature on documents. It is different from a handwritten image signature — it carries legal weight under the IT Act 2000.",
  },
  {
    question: "What size should a signature be for Aadhaar-related forms?",
    answer:
      "For most Aadhaar-related forms and portals, a signature image of 140×60 px to 200×80 px as a PNG or JPEG is typically accepted. File size should be under 50 KB. Pixocraft exports at high resolution and you can resize before uploading to UIDAI or banking portals.",
  },
  {
    question: "Can I use a typed signature for Aadhaar forms?",
    answer:
      "Many government portals accept a scanned image of a handwritten signature or a drawn digital signature. A typed name in cursive font (generated by Pixocraft) is generally acceptable for forms submitted digitally. For official UIDAI physical forms, a hand-signed ink signature is still required.",
  },
  {
    question: "Is an image-based signature legally valid for Aadhaar-linked forms?",
    answer:
      "An image-based handwritten signature is valid for most general-purpose forms that reference Aadhaar, such as bank KYC forms, SIM card applications, and loan applications. For high-security filings or digitally verified documents, you may need Aadhaar eSign or a Class 3 DSC.",
  },
  {
    question: "What format is accepted for signature upload in UIDAI portals?",
    answer:
      "UIDAI portals typically accept JPEG and PNG formats for signature uploads. The recommended file size is under 50 KB and dimensions are usually 140×60 px. Use Pixocraft to draw your signature and download a transparent PNG, then resize as needed before uploading.",
  },
  {
    question: "How do I add a signature to an Aadhaar-linked PDF?",
    answer:
      "Create and download your signature as a transparent PNG from Pixocraft. Then open your PDF in any PDF editor (Adobe Acrobat, Foxit, or Pixocraft's Add Signature to PDF tool). Insert your PNG in the signature field and save the document.",
  },
  {
    question: "Is Pixocraft's signature tool free for Aadhaar use?",
    answer:
      "Yes — completely free, forever. No login, no watermark, no data upload. Create your signature in the browser and download it instantly as a transparent PNG suitable for Aadhaar-related forms and KYC documents.",
  },
  {
    question: "Does my signature get uploaded or stored when I use Pixocraft?",
    answer:
      "No. All signature creation happens inside your browser. Your name, drawing strokes, and the final PNG are never sent to any server. Everything stays on your device — 100% private and GDPR-safe.",
  },
  {
    question: "Can I use the same signature for multiple Aadhaar-linked accounts?",
    answer:
      "Yes. Download your signature PNG once and reuse it across bank KYC forms, SIM card applications, government scheme registrations, and any other Aadhaar-linked document. Save it in a permanent folder for quick access.",
  },
  {
    question: "What is the difference between Aadhaar eSign and an image signature?",
    answer:
      "Aadhaar eSign is a government-certified cryptographic signature authenticated via your Aadhaar OTP — it is legally binding under the IT Act 2000. An image signature (PNG of your handwriting) is a visual representation acceptable for most forms but does not carry cryptographic proof. Use eSign for legal contracts and high-security filings.",
  },
];

const HOWTO_STEPS = [
  {
    name: "Open the Pixocraft signature tool",
    text: "The signature tool is available at the top of this page. No login or account is required.",
  },
  {
    name: "Draw, type, or upload your signature",
    text: "Use the Draw tab to sign with your mouse or touchscreen, or switch to the Type tab to choose a cursive font that resembles your handwriting.",
  },
  {
    name: "Adjust thickness and style",
    text: "Use the thickness slider to match the weight of your pen signature. Choose ink colour if needed — black is standard for most forms.",
  },
  {
    name: "Preview your signature",
    text: "See a live preview before downloading. Ensure your signature is clear and proportionate for form use.",
  },
  {
    name: "Download as PNG",
    text: "Click Download → PNG. You receive a transparent PNG with no watermark — suitable for UIDAI forms, bank KYC, and other Aadhaar-related documents.",
  },
  {
    name: "Use in Aadhaar-linked forms or PDFs",
    text: "Insert the PNG into any form that accepts a digital signature image. For PDFs, use a PDF editor to place the signature in the designated field.",
  },
];

const USE_CASES = [
  {
    icon: <CreditCard className="h-5 w-5 text-primary" />,
    title: "Bank KYC & Account Opening",
    desc: "Banks require your signature for Aadhaar-linked account opening, KYC updates, and loan applications. Use your PNG across all branches instantly.",
  },
  {
    icon: <Phone className="h-5 w-5 text-primary" />,
    title: "SIM Card Activation",
    desc: "Telecom operators need a signed Aadhaar-linked form for new SIM registration. Upload your signature PNG directly on the activation form.",
  },
  {
    icon: <Landmark className="h-5 w-5 text-primary" />,
    title: "Government Schemes & Benefits",
    desc: "Schemes like PM-KISAN, PMJAY, and MGNREGA require signed Aadhaar-linked application forms. Reuse your signature for each registration.",
  },
  {
    icon: <FileCheck className="h-5 w-5 text-primary" />,
    title: "PAN–Aadhaar Linking",
    desc: "Some offline PAN-linking forms still require a wet or digital signature. Your PNG is accepted for most submission formats.",
  },
  {
    icon: <Building2 className="h-5 w-5 text-primary" />,
    title: "UIDAI Correction & Update Forms",
    desc: "Updating your name, date of birth, or address on Aadhaar requires a signed physical form. Use your PNG to prepare signed copies.",
  },
  {
    icon: <UserCheck className="h-5 w-5 text-primary" />,
    title: "eKYC for Mutual Funds & Insurance",
    desc: "SEBI-registered entities require Aadhaar-linked eKYC with a signature. Upload your transparent PNG directly to the portal.",
  },
];

const COMMON_MISTAKES = [
  {
    icon: <XCircle className="h-5 w-5 text-destructive shrink-0 mt-0.5" />,
    title: "Uploading JPEG with white background",
    desc: "A white background creates a visible box over the form. Always use transparent PNG so the signature blends cleanly into the document.",
  },
  {
    icon: <XCircle className="h-5 w-5 text-destructive shrink-0 mt-0.5" />,
    title: "File size too large",
    desc: "UIDAI and banking portals often have a 50 KB file size limit. Export at lower resolution or compress the PNG before uploading.",
  },
  {
    icon: <XCircle className="h-5 w-5 text-destructive shrink-0 mt-0.5" />,
    title: "Modifying the Aadhaar card itself",
    desc: "Never attempt to add or alter anything on the Aadhaar card image — this is a legal offence under UIDAI regulations.",
  },
  {
    icon: <XCircle className="h-5 w-5 text-destructive shrink-0 mt-0.5" />,
    title: "Confusing image signature with Aadhaar eSign",
    desc: "A PNG signature is for form use. Aadhaar eSign is a government-certified cryptographic tool. Do not use one in place of the other for legal contracts.",
  },
  {
    icon: <XCircle className="h-5 w-5 text-destructive shrink-0 mt-0.5" />,
    title: "Not saving the PNG for reuse",
    desc: "Keep a permanent copy of your signature PNG in a safe folder or cloud drive. You will need it for multiple Aadhaar-linked submissions over time.",
  },
];

const COMPARISON_ROWS = [
  { feature: "Cost",                  pixocraft: "Free",             others: "Paid / Freemium" },
  { feature: "Login required",        pixocraft: "No",               others: "Usually yes" },
  { feature: "Data upload",           pixocraft: "None",             others: "Server upload" },
  { feature: "Works offline",         pixocraft: "Yes",              others: "Mostly no" },
  { feature: "Transparent PNG",       pixocraft: "Yes",              others: "Often watermarked" },
  { feature: "Mobile support",        pixocraft: "Full",             others: "Partial" },
  { feature: "Speed",                 pixocraft: "Under 60 seconds", others: "2–5 minutes" },
];

const INTERNAL_LINKS = [
  { href: "/tools/signature-generator",         label: "Signature Generator" },
  { href: "/tools/signature-for-pdf",           label: "Signature for PDF" },
  { href: "/tools/email-signature-generator",   label: "Email Signature Generator" },
  { href: "/tools/signature-font-generator",    label: "Signature Font Generator" },
  { href: "/tools/signature-for-gst-invoice",   label: "Signature for GST Invoice" },
  { href: "/tools/digital-signature-generator", label: "Digital Signature Generator" },
];

export default function SignatureForAadhaar() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  useSEO({
    title: "Signature for Aadhaar Online Free – Create & Download",
    description:
      "Create Aadhaar-ready signature online free. Download PNG, use for KYC, forms, and UIDAI updates. No login, private & secure tool.",
    canonicalUrl: CANONICAL,
    ogType: "website",
    ogImage: "https://tools.pixocraft.in/images/aadhaar-signature-tool.png",
    keywords:
      "signature for aadhaar, aadhaar signature online, aadhaar signature size, aadhaar esign, how to add signature in aadhaar card, esign aadhaar online free",
  });

  const schemas = [
    generateFAQSchema(FAQS),
    generateHowToSchema({
      name: "How to Create Signature for Aadhaar Online",
      description:
        "Create a transparent PNG signature for Aadhaar-related forms and KYC documents using Pixocraft — free, no login, fully private.",
      steps: HOWTO_STEPS,
    }),
    generateSoftwareApplicationSchema({
      name: "Signature for Aadhaar Tool",
      description:
        "Free online Aadhaar signature generator. Create, download, and use signature for KYC, forms, and UIDAI processes.",
      url: CANONICAL,
      applicationCategory: "UtilityApplication",
      operatingSystem: "Web",
      offers: { price: "0", priceCurrency: "INR" },
    }),
    generateBreadcrumbSchema([
      { name: "Home",                   url: "https://tools.pixocraft.in" },
      { name: "Tools",                  url: "https://tools.pixocraft.in/tools" },
      { name: "Signature Tools",        url: "https://tools.pixocraft.in/tools/signature-tools" },
      { name: "Signature for Aadhaar",  url: CANONICAL },
    ]),
  ];

  return (
    <div className="min-h-screen bg-background">
      {schemas.map((schema, i) => (
        <StructuredData key={i} data={schema} />
      ))}

      <div className="max-w-4xl mx-auto px-4 py-8 space-y-10">

        {/* ── BREADCRUMB ───────────────────────────────────────────────────── */}
        <Breadcrumb
          items={[
            { label: "Home",                  url: "/" },
            { label: "Tools",                 url: "/tools" },
            { label: "Signature Tools",       url: "/tools/signature-tools" },
            { label: "Signature Generator", url: "/tools/signature-generator" },
            { label: "Signature for Aadhaar" },
          ]}
        />

        {/* ── PRIMARY TOOL LINK ─────────────────────────────────────────────── */}
        <SignatureTopPromo />

        {/* ── HERO ─────────────────────────────────────────────────────────── */}
        <div className="space-y-4">
          <div className="flex items-center gap-3">
            <div className="h-12 w-12 rounded-xl bg-primary/10 flex items-center justify-center shrink-0">
              <FileCheck className="h-6 w-6 text-primary" />
            </div>
            <h1 className="text-3xl sm:text-4xl font-bold text-foreground leading-tight">
              Signature for Aadhaar –{" "}
              <span className="text-primary">Create & Download Free Online</span>
            </h1>
          </div>
          <p className="text-lg text-muted-foreground leading-relaxed">
            Create an Aadhaar-ready signature instantly — for KYC forms, UIDAI updates, bank verification, and government scheme applications.
            Download a <strong>transparent PNG</strong> with no watermark, no login, and no data upload. Works offline.
          </p>
          <p className="text-base font-semibold text-foreground">
            <strong>Create your Aadhaar signature in under 60 seconds — no login, no upload, fully private.</strong>
          </p>
          <div className="flex flex-wrap gap-2">
            {[
              { icon: <Lock className="h-3.5 w-3.5" />,       label: "No Login" },
              { icon: <Star className="h-3.5 w-3.5" />,       label: "Transparent PNG" },
              { icon: <BadgeCheck className="h-3.5 w-3.5" />, label: "KYC Ready" },
              { icon: <Shield className="h-3.5 w-3.5" />,     label: "100% Private" },
              { icon: <Zap className="h-3.5 w-3.5" />,        label: "Works Offline" },
              { icon: <Smartphone className="h-3.5 w-3.5" />, label: "Mobile Ready" },
            ].map(({ icon, label }) => (
              <span
                key={label}
                className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-medium bg-primary/5 text-primary border border-primary/20"
              >
                {icon}{label}
              </span>
            ))}
          </div>
        </div>

        {/* ── FEATURED SNIPPET ─────────────────────────────────────────────── */}
        <div className="rounded-xl border-2 border-primary/20 bg-primary/5 px-6 py-5 space-y-3">
          <p className="text-xs font-bold uppercase tracking-widest text-primary">Quick Answer</p>
          <h2 className="text-lg font-bold text-foreground">
            What is a signature for Aadhaar and how to create it online?
          </h2>
          <p className="text-sm text-foreground leading-relaxed">
            A signature for Aadhaar is a handwritten or digital signature image used on Aadhaar-linked forms — such as KYC documents, bank applications, and UIDAI update requests. Aadhaar card itself does not carry a signature. Use Pixocraft to draw your signature and download a transparent PNG in under 60 seconds — free, no login required.
          </p>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-1">
            {[
              { label: "Format",        value: "PNG (Transparent)" },
              { label: "Ideal size",    value: "140–200px width" },
              { label: "File size",     value: "Under 50 KB" },
              { label: "Cost",          value: "Free Forever" },
            ].map(({ label, value }) => (
              <div key={label} className="rounded-lg bg-background border p-3 text-center">
                <p className="text-[10px] text-muted-foreground uppercase tracking-wider font-medium">{label}</p>
                <p className="font-semibold text-foreground text-sm mt-0.5">{value}</p>
              </div>
            ))}
          </div>
        </div>

        {/* ── TOOL ─────────────────────────────────────────────────────────── */}
        <SignatureToolSection
          mode="draw"
          caption="Draw or type your signature · Download as transparent PNG · Aadhaar-ready format · No watermark"
        />

        {/* ── WHAT IS AADHAAR SIGNATURE ─────────────────────────────────────── */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-foreground">What is a Signature for Aadhaar?</h2>
          <div className="rounded-xl border bg-card px-6 py-5 space-y-3">
            <p className="text-foreground leading-relaxed">
              The <strong>Aadhaar card</strong> issued by UIDAI does not contain a signature field — your biometric data (fingerprints and iris scan) serve as your identifier. However, your <strong>handwritten signature</strong> is required in many Aadhaar-related processes:
            </p>
            <ul className="space-y-2">
              {[
                "Aadhaar enrolment and correction forms (physical submission)",
                "Bank account opening and KYC verification linked to Aadhaar",
                "PAN–Aadhaar linking offline forms",
                "Government scheme applications referencing your Aadhaar number",
                "Loan, insurance, and mutual fund applications with eKYC",
                "SIM card activation requiring Aadhaar-verified identity",
              ].map((item) => (
                <li key={item} className="flex gap-2 text-sm text-muted-foreground items-start">
                  <Check className="h-4 w-4 text-primary shrink-0 mt-0.5" />
                  {item}
                </li>
              ))}
            </ul>
            <p className="text-sm text-muted-foreground pt-1">
              Pixocraft lets you create a clean, consistent digital signature that you can reuse across all of these touchpoints — without ever uploading your data to a server.
            </p>
          </div>
        </section>

        {/* ── WHERE AADHAAR SIGNATURE IS USED ──────────────────────────────── */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-foreground">Where is Aadhaar Signature Required?</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {USE_CASES.map(({ icon, title, desc }) => (
              <div key={title} className="flex gap-4 p-5 rounded-xl border bg-card">
                <div className="shrink-0 h-10 w-10 rounded-lg bg-primary/10 flex items-center justify-center">{icon}</div>
                <div className="space-y-1">
                  <p className="font-semibold text-foreground">{title}</p>
                  <p className="text-sm text-muted-foreground leading-relaxed">{desc}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ── SIZE & FORMAT ─────────────────────────────────────────────────── */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-foreground">Aadhaar Signature Size & Format</h2>
          <div className="rounded-xl border bg-card px-6 py-5 space-y-3">
            <p className="text-foreground font-medium">
              Most Aadhaar-related portals and forms accept a signature image between <strong>140×60 px and 200×80 px</strong> in <strong>PNG or JPEG format</strong>, with a file size under <strong>50 KB</strong>.
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Always choose <strong>transparent PNG</strong> over JPEG — PNG avoids the white box that JPEG creates on coloured form backgrounds. Pixocraft exports your signature at high resolution; resize as needed before uploading to a portal.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            {[
              { label: "Recommended dimensions", value: "140–200 px width" },
              { label: "Best format",             value: "PNG (Transparent)" },
              { label: "Max file size",           value: "Under 50 KB" },
            ].map(({ label, value }) => (
              <div key={label} className="rounded-lg border bg-card p-4 text-center">
                <p className="text-[11px] text-muted-foreground uppercase tracking-wider font-medium">{label}</p>
                <p className="font-semibold text-foreground text-sm mt-1">{value}</p>
              </div>
            ))}
          </div>
        </section>

        {/* ── HOW TO CREATE ────────────────────────────────────────────────── */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-foreground">How to Create Signature for Aadhaar – Step by Step</h2>
          <p className="text-muted-foreground">The entire process takes under 60 seconds, no account needed.</p>
          <ol className="space-y-3">
            {HOWTO_STEPS.map(({ name, text }, i) => (
              <li key={i} className="flex gap-4 p-4 rounded-xl border bg-card">
                <span className="shrink-0 h-8 w-8 rounded-full bg-primary/10 text-primary font-bold text-sm flex items-center justify-center">{i + 1}</span>
                <div>
                  <p className="font-semibold text-foreground">{name}</p>
                  <p className="text-sm text-muted-foreground mt-0.5">{text}</p>
                </div>
              </li>
            ))}
          </ol>
        </section>

        {/* ── HOW TO ADD SIGNATURE IN AADHAAR DOCUMENTS ────────────────────── */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-foreground">How to Add Signature in Aadhaar-Linked Documents</h2>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {[
              {
                icon: <FileText className="h-5 w-5 text-primary" />,
                title: "Add to a PDF",
                desc: "Open your PDF in any editor (Adobe Acrobat, Foxit, or Pixocraft's PDF Signature tool). Insert the PNG in the signature field and save.",
              },
              {
                icon: <Download className="h-5 w-5 text-primary" />,
                title: "Upload to a Portal",
                desc: "Most UIDAI-linked portals have a 'Upload Signature' field. Select your downloaded PNG and upload it directly — resize to meet size limits.",
              },
              {
                icon: <FileCheck className="h-5 w-5 text-primary" />,
                title: "Print & Sign a Form",
                desc: "Insert your PNG into a Word or Google Doc form template, print it, and submit physically to a bank or government office.",
              },
            ].map(({ icon, title, desc }) => (
              <div key={title} className="flex flex-col gap-3 p-5 rounded-xl border bg-card">
                <div className="h-10 w-10 rounded-lg bg-primary/10 flex items-center justify-center">{icon}</div>
                <p className="font-semibold text-foreground">{title}</p>
                <p className="text-sm text-muted-foreground leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
          <div className="flex">
            <Link href="/tools/signature-for-pdf">
              <span className="inline-flex items-center gap-2 text-sm font-semibold text-primary hover:underline underline-offset-2" data-testid="link-signature-for-pdf">
                Open the PDF Signature Tool <ArrowRight className="h-4 w-4" />
              </span>
            </Link>
          </div>
        </section>

        {/* ── SAVE & REUSE ─────────────────────────────────────────────────── */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-foreground">Save & Reuse Your Signature</h2>
          <div className="rounded-xl border bg-card px-6 py-5 space-y-3">
            <p className="text-foreground font-medium">
              Download your signature PNG once and store it in a permanent folder — your Desktop, Documents, or Google Drive. Reuse it across:
            </p>
            <ul className="space-y-2">
              {[
                "All Aadhaar-linked bank KYC submissions",
                "SIM activation forms at any telecom operator",
                "Government scheme applications (PM-KISAN, PMJAY, etc.)",
                "Mutual fund, insurance, and loan application forms",
                "Any PDF document requiring a signature image",
                "Email footers and letterheads",
              ].map((item) => (
                <li key={item} className="flex gap-2 text-sm text-muted-foreground items-start">
                  <Check className="h-4 w-4 text-primary shrink-0 mt-0.5" />
                  {item}
                </li>
              ))}
            </ul>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-2">
              {[
                { icon: <Lock className="h-4 w-4" />,         label: "No Login" },
                { icon: <Shield className="h-4 w-4" />,       label: "100% Private" },
                { icon: <Zap className="h-4 w-4" />,          label: "Works Offline" },
                { icon: <Smartphone className="h-4 w-4" />,   label: "Mobile Ready" },
              ].map(({ icon, label }) => (
                <div key={label} className="flex flex-col items-center gap-1.5 p-3 rounded-lg border bg-background text-center">
                  <span className="text-primary">{icon}</span>
                  <p className="text-xs font-semibold text-foreground">{label}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── LEGAL CLARITY ─────────────────────────────────────────────────── */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-foreground">Legal Clarity – Aadhaar Signature vs Aadhaar eSign</h2>
          <div className="rounded-xl border bg-card px-6 py-5 space-y-4">
            <div className="flex gap-3 p-3 rounded-lg bg-amber-500/10 border border-amber-500/20">
              <AlertCircle className="h-5 w-5 text-amber-600 shrink-0 mt-0.5" />
              <p className="text-sm text-foreground leading-relaxed">
                <strong>Important:</strong> Pixocraft creates a <strong>handwritten image signature</strong> — this is NOT an Aadhaar eSign or Digital Signature Certificate (DSC). It is valid for most general-purpose forms but should not be used for legally binding contracts or high-security government filings that mandate cryptographic authentication.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-1">
              {[
                {
                  title: "Image Signature (Pixocraft PNG)",
                  items: [
                    "Accepted for KYC forms, bank applications, SIM cards",
                    "Valid for physical and PDF submissions",
                    "No cryptographic proof",
                    "Free to create, no authority needed",
                  ],
                  ok: true,
                },
                {
                  title: "Aadhaar eSign (UIDAI Certified)",
                  items: [
                    "Required for legally binding digital contracts",
                    "Authenticated via Aadhaar OTP",
                    "Carries legal weight under IT Act 2000",
                    "Requires licensed eSign service provider",
                  ],
                  ok: false,
                },
              ].map(({ title, items, ok }) => (
                <div key={title} className="rounded-lg border bg-background p-4 space-y-2">
                  <p className="font-semibold text-foreground text-sm">{title}</p>
                  {items.map((item) => (
                    <div key={item} className="flex gap-2 items-start">
                      {ok
                        ? <Check className="h-3.5 w-3.5 text-green-600 shrink-0 mt-0.5" />
                        : <BadgeCheck className="h-3.5 w-3.5 text-primary shrink-0 mt-0.5" />
                      }
                      <p className="text-xs text-muted-foreground">{item}</p>
                    </div>
                  ))}
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── COMMON MISTAKES ──────────────────────────────────────────────── */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-foreground">Common Mistakes to Avoid</h2>
          <div className="space-y-3">
            {COMMON_MISTAKES.map(({ icon, title, desc }) => (
              <div key={title} className="flex gap-4 p-4 rounded-xl border bg-card">
                {icon}
                <div>
                  <p className="font-semibold text-foreground text-sm">{title}</p>
                  <p className="text-sm text-muted-foreground mt-0.5">{desc}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ── COMPARISON ───────────────────────────────────────────────────── */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-foreground">Pixocraft vs Other Signature Tools</h2>
          <div className="rounded-xl border bg-card overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b bg-muted/40">
                    <th className="text-left px-4 py-3 font-semibold text-foreground">Feature</th>
                    <th className="text-left px-4 py-3 font-semibold text-primary">Pixocraft</th>
                    <th className="text-left px-4 py-3 font-semibold text-foreground">Other Tools</th>
                  </tr>
                </thead>
                <tbody>
                  {COMPARISON_ROWS.map(({ feature, pixocraft, others }, i) => (
                    <tr key={feature} className={i % 2 === 0 ? "" : "bg-muted/20"}>
                      <td className="px-4 py-3 text-muted-foreground font-medium">{feature}</td>
                      <td className="px-4 py-3 text-primary font-semibold">{pixocraft}</td>
                      <td className="px-4 py-3 text-muted-foreground">{others}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </section>

        {/* ── FAQ ──────────────────────────────────────────────────────────── */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-foreground">Frequently Asked Questions</h2>
          <div className="space-y-2">
            {FAQS.map((faq, i) => (
              <div
                key={i}
                className="rounded-xl border bg-card overflow-hidden"
                data-testid={`faq-item-${i}`}
              >
                <button
                  className="w-full flex items-center justify-between gap-4 px-5 py-4 text-left"
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  data-testid={`faq-toggle-${i}`}
                >
                  <span className="font-semibold text-foreground text-sm leading-snug">{faq.question}</span>
                  {openFaq === i
                    ? <ChevronUp className="h-4 w-4 text-muted-foreground shrink-0" />
                    : <ChevronDown className="h-4 w-4 text-muted-foreground shrink-0" />
                  }
                </button>
                {openFaq === i && (
                  <div className="px-5 pb-4">
                    <p className="text-sm text-muted-foreground leading-relaxed">{faq.answer}</p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>

        {/* ── MORE SIGNATURE TOOLS ─────────────────────────────────────── */}
        <SignatureRelatedTools links={[
          { href: "/tools/signature-generator",          label: "Signature Generator",          desc: "The main tool — draw, type, or upload and download a transparent PNG in seconds." },
          { href: "/tools/signature-generator-india",    label: "Signature Generator India",    desc: "Optimised for Indian business, GST, banking, and government document workflows." },
          { href: "/tools/signature-for-gst-invoice",    label: "Signature for GST Invoice",    desc: "Sign GST invoices for TallyPrime, Zoho Books, and ClearTax with a transparent PNG." },
          { href: "/tools/signature-for-tally",          label: "Signature for Tally",          desc: "Add your signature to TallyPrime invoices using the built-in image insertion feature." },
          { href: "/tools/digital-signature-generator",  label: "Digital Signature Generator",  desc: "Create a legally valid digital signature compliant with India's IT Act 2000." },
        ]} />

        {/* ── BOTTOM BREADCRUMB ─────────────────────────────────────────────── */}
        <div className="pt-4 border-t">
          <Breadcrumb
            items={[
              { label: "Home",                  url: "/" },
              { label: "Tools",                 url: "/tools" },
              { label: "Signature Tools",       url: "/tools/signature-tools" },
              { label: "Signature for Aadhaar" },
            ]}
          />
          <p className="text-xs text-muted-foreground mt-3">
            Last Updated: {LAST_UPDATED} · Made in India · By the Pixocraft Team
          </p>
        </div>

      </div>
    </div>
  );
}
